/**
 * caseSummaryEngine.ts
 *
 * Enhancement 3 – AI Case Summary Engine
 *
 * Parses a user's free-expression narrative (text or transcribed voice) into a
 * structured CaseSummaryCard. The card is presented to the user for endorsement
 * before a formal case session starts.
 *
 * Safety contract:
 *  - The engine NEVER diagnoses, prescribes, or replaces emergency services.
 *  - "emergency" urgencyFlag cards are returned to the caller so they can
 *    short-circuit to a crisis flow immediately without human expert review.
 *  - All text generation is purely parsing / classification — no LLM is called
 *    here; the heavy AI is deferred to the evaluation pipeline.
 *
 * Domain firewall:
 *  - Domain A (scientific) keywords drive urgencyFlag and keySymptoms.
 *  - Domain B (cultural) keywords affect suggestedStrands only and never
 *    influence urgency or symptom classification.
 */

import type { KnowledgeStrandType } from "@/lib/knowledge/types";

// ─── Types ────────────────────────────────────────────────────────────────────

export type UrgencyFlag = "none" | "watch" | "urgent" | "emergency";
export type StrandTier = "biomedical" | "evidence-informed" | "traditional" | "cultural";

export interface SuggestedStrandDetail {
  strand: KnowledgeStrandType;
  tier: StrandTier;
  rationale: string;
}

export type CaseDomain =
  | "wellbeing"
  | "relationships"
  | "career"
  | "legal"
  | "social"
  | "spiritual";

export interface CaseSummaryCard {
  /** Unique ID for the card — generated by the caller when persisting to DB */
  id?: string;
  endorsedByUser?: boolean;
  /** Original narrative text submitted by the user */
  rawNarrative: string;
  /** English translation of the narrative when input was in Amharic */
  aiTranslation?: string;
  /** One-line summary of the concern */
  headline: string;
  /** Primary domain selected by the engine */
  domain: CaseDomain;
  /** Finer-grained sub-category (e.g. "marital_conflict", "job_search") */
  subDomain: string;
  /** Short description of what the user is seeking */
  userIntention: string;
  /** Key symptom or concern phrases extracted from the narrative */
  keySymptoms: string[];
  /** Emergency / urgency flag */
  urgencyFlag: UrgencyFlag;
  emergencyDetected: boolean;
  emergencySignals: string[];
  suggestedStrandDetails: SuggestedStrandDetail[];
  /** Crisis resource message — only populated when urgencyFlag === "emergency" */
  crisisMessage?: string;
  /** Strands recommended for the case evaluation pipeline */
  suggestedStrands: KnowledgeStrandType[];
  /** Engine confidence score 0–100 */
  aiConfidence: number;
}

// ─── Domain classification dictionaries ───────────────────────────────────────

const DOMAIN_SIGNALS: Record<CaseDomain, string[]> = {
  wellbeing: [
    "pain", "tired", "fatigue", "sick", "health", "headache", "stomach",
    "fever", "cough", "blood", "medication", "hospital", "doctor", "pregnant",
    "diabetes", "pressure", "ህመም", "ደከምኩ", "ሕጽረት", "ሕመም", "ሕክምና",
  ],
  relationships: [
    "wife", "husband", "marriage", "divorce", "partner", "family", "child",
    "mother", "father", "conflict", "abuse", "love", "relationship",
    "ሚስቴ", "ባሌ", "ቤተሰብ", "ፍቅር", "ፍቺ", "ልጅ",
  ],
  career: [
    "job", "work", "career", "salary", "unemployed", "business", "promotion",
    "fired", "office", "company", "employment", "ሥራ", "ደሞዝ", "ቢዝነስ", "ሚስጥር",
  ],
  legal: [
    "court", "lawyer", "legal", "police", "arrest", "contract", "property",
    "rights", "inheritance", "land", "ፍርድ", "ጠበቃ", "ህግ", "ፖሊስ", "ቤት",
  ],
  social: [
    "community", "neighbour", "discrimination", "poverty", "social",
    "network", "isolation", "society", "ማህበረሰብ", "ድህነት", "ማህበራዊ",
  ],
  spiritual: [
    "pray", "church", "mosque", "spiritual", "faith", "god", "holy",
    "baptism", "blessing", "devil", "soul", "ቤተክርስቲያን", "ጸሎት", "ሃይማኖት",
    "ቅዱስ", "ጋኔን", "ፈውስ", "መንፈሳዊ",
  ],
};

// Sub-domain hints for finer classification
const SUB_DOMAIN_MAP: Record<string, string> = {
  pregnant: "maternal_health",
  pregnancy: "maternal_health",
  diabetes: "chronic_disease_management",
  blood_pressure: "cardiovascular_health",
  pressure: "hypertension",
  divorce: "marital_conflict",
  abuse: "domestic_safety",
  unemployed: "job_search",
  fired: "job_loss",
  court: "civil_litigation",
  land: "property_dispute",
  inheritance: "estate_law",
  poverty: "economic_hardship",
  isolation: "social_exclusion",
  pray: "prayer_guidance",
  blessing: "ritual_support",
};

// ─── Emergency keyword triggers (exact match inside word boundary) ─────────────

const EMERGENCY_PATTERNS: Array<{ label: string; pattern: RegExp }> = [
  { label: "self-harm or suicide risk", pattern: /\b(suicid\w*|kill myself|end my life|self[- ]harm|want to die)\b/i },
  { label: "chest pain", pattern: /\b(chest pain|crushing chest pain|heart attack)\b/i },
  { label: "breathing difficulty", pattern: /\b(can't breathe|cannot breathe|unable to breathe|choking)\b/i },
  { label: "severe bleeding", pattern: /\b(severe bleeding|heavy bleeding|hemorrhage|major blood loss)\b/i },
  { label: "loss of consciousness", pattern: /\b(unconscious|loss of consciousness|fainted and unresponsive)\b/i },
  { label: "seizure", pattern: /\b(seizure|convulsion)\b/i },
  { label: "severe head injury", pattern: /\b(severe head injury|head trauma|hit my head and lost consciousness)\b/i },
  { label: "sexual or violent assault", pattern: /\b(rape|sexual assault|violent attack)\b/i },
  { label: "emergency signal (Amharic)", pattern: /ራሴን ልግደል|ሕይወቴን ማጥፋት|ልቤ ያመኛል|የልብ ህመም|መተንፈስ አልችልም|ደም መፍሰስ|ንቃተ ህሊና ማጣት|መንቀጥቀጥ|የጭንቅላት ጉዳት|የጾታ ጥቃት/i },
];

const URGENT_TRIGGERS = [
  "bleeding", "unconscious", "faint", "chest pain", "cannot breathe",
  "stroke", "seizure", "emergency",
];

const WATCH_TRIGGERS = [
  "severe", "worsening", "cannot eat", "cannot sleep", "not eating",
  "collapsed", "high fever",
];

// ─── Strand mapping by domain ─────────────────────────────────────────────────

const DOMAIN_DEFAULT_STRANDS: Record<CaseDomain, KnowledgeStrandType[]> = {
  wellbeing: [
    "biological", "biochemical", "dietary", "ecological",
    "epidemiological", "medication",
  ],
  relationships: [
    "psychological", "socioeconomic", "cultural", "biological",
  ],
  career: [
    "psychological", "socioeconomic", "cultural", "astrological",
  ],
  legal: [
    "socioeconomic", "psychological", "cultural",
  ],
  social: [
    "socioeconomic", "epidemiological", "psychological", "ecological",
  ],
  spiritual: [
    "cultural", "astrological", "psychological",
  ],
};

const STRAND_TIER_DETAILS: Record<KnowledgeStrandType, Omit<SuggestedStrandDetail, "strand">> = {
  biological: { tier: "biomedical", rationale: "Biological and clinical evidence" },
  biochemical: { tier: "biomedical", rationale: "Biochemical evidence and mechanisms" },
  medication: { tier: "biomedical", rationale: "Medication safety and pharmacology" },
  epidemiological: { tier: "biomedical", rationale: "Population health and epidemiological evidence" },
  dietary: { tier: "evidence-informed", rationale: "Nutrition and dietary evidence" },
  ecological: { tier: "evidence-informed", rationale: "Environmental and regional context" },
  psychological: { tier: "evidence-informed", rationale: "Evidence-informed psychological context" },
  socioeconomic: { tier: "evidence-informed", rationale: "Social and economic context" },
  addiction: { tier: "evidence-informed", rationale: "Evidence-informed substance-use context" },
  cultural: { tier: "cultural", rationale: "Cultural reflection; not clinical evidence" },
  astrological: { tier: "cultural", rationale: "Spiritual reflection; not clinical evidence" },
};

export function detectEmergency(text: string): { detected: boolean; signals: string[] } {
  const signals = EMERGENCY_PATTERNS
    .filter(({ pattern }) => pattern.test(text))
    .map(({ label }) => label);
  return { detected: signals.length > 0, signals };
}

// ─── Core engine function ─────────────────────────────────────────────────────

/**
 * Parses a free-expression narrative into a CaseSummaryCard.
 *
 * @param narrative - The raw text (or voice-transcribed text) the user submitted.
 * @param preferredLanguage - "en" or "am". When "am" the rawNarrative is also
 *   stored as aiTranslation (a live translation call would be wired in production).
 * @returns A fully populated CaseSummaryCard — never throws.
 */
export function parseCaseNarrative(
  narrative: string,
  preferredLanguage: "en" | "am" = "en"
): CaseSummaryCard {
  const lower = narrative.toLowerCase().trim();

  // ─── 1. Urgency classification ───────────────────────────────────────────
  let urgencyFlag: UrgencyFlag = "none";
  let crisisMessage: string | undefined;
  const emergency = detectEmergency(narrative);

  if (emergency.detected) {
    urgencyFlag = "emergency";
    crisisMessage =
      "Your message indicates you or someone you know may be in immediate danger. " +
      "Please call your local emergency number or reach out " +
      "to a trusted person right now. The platform's counsellors are NOT a substitute " +
      "for emergency services.";
  } else if (URGENT_TRIGGERS.some((t) => lower.includes(t.toLowerCase()))) {
    urgencyFlag = "urgent";
  } else if (WATCH_TRIGGERS.some((t) => lower.includes(t.toLowerCase()))) {
    urgencyFlag = "watch";
  }

  // ─── 2. Domain classification ─────────────────────────────────────────────
  const domainScores = Object.entries(DOMAIN_SIGNALS).map(([domain, signals]) => {
    const score = signals.reduce(
      (acc, signal) => acc + (lower.includes(signal.toLowerCase()) ? 1 : 0),
      0
    );
    return { domain: domain as CaseDomain, score };
  });
  domainScores.sort((a, b) => b.score - a.score);
  const primaryDomain: CaseDomain =
    domainScores[0].score > 0 ? domainScores[0].domain : "wellbeing";

  // ─── 3. Sub-domain ───────────────────────────────────────────────────────
  let subDomain = "general";
  for (const [keyword, sub] of Object.entries(SUB_DOMAIN_MAP)) {
    if (lower.includes(keyword.replace(/_/g, " "))) {
      subDomain = sub;
      break;
    }
  }

  // ─── 4. Key symptoms / concerns ──────────────────────────────────────────
  const allSignals = Object.values(DOMAIN_SIGNALS).flat();
  const keySymptoms = [...new Set(
    allSignals.filter((s) => lower.includes(s.toLowerCase()) && s.length > 3)
  )].slice(0, 8);

  // ─── 5. Suggested strands ─────────────────────────────────────────────────
  const suggestedStrands: KnowledgeStrandType[] = [
    ...DOMAIN_DEFAULT_STRANDS[primaryDomain],
  ];
  // Addiction strand if substance keywords present
  if (
    lower.includes("alcohol") ||
    lower.includes("khat") ||
    lower.includes("areke") ||
    lower.includes("addiction") ||
    lower.includes("drug")
  ) {
    suggestedStrands.push("addiction");
  }

  // ─── 6. Headline generation ───────────────────────────────────────────────
  const domainLabel: Record<CaseDomain, string> = {
    wellbeing: "Health & Wellbeing",
    relationships: "Relationships & Family",
    career: "Career & Work",
    legal: "Legal Matter",
    social: "Social & Community",
    spiritual: "Spiritual & Cultural",
  };

  const wordCount = narrative.trim().split(/\s+/).length;
  const headline =
    wordCount <= 12
      ? narrative.trim()
      : `${domainLabel[primaryDomain]} — ${subDomain.replace(/_/g, " ")}`;

  // ─── 7. User intention ───────────────────────────────────────────────────
  const userIntention =
    urgencyFlag === "emergency"
      ? "Crisis support requested"
      : `Seeking guidance and insight on ${domainLabel[primaryDomain].toLowerCase()}`;

  // ─── 8. Confidence score ─────────────────────────────────────────────────
  const matchedSignals = domainScores[0].score;
  const aiConfidence = Math.min(
    95,
    Math.max(30, 40 + matchedSignals * 10 - (preferredLanguage === "am" ? 5 : 0))
  );
  const uniqueStrands = [...new Set(suggestedStrands)];

  return {
    rawNarrative: narrative,
    ...(preferredLanguage === "am" ? { aiTranslation: narrative } : {}),
    headline,
    domain: primaryDomain,
    subDomain,
    userIntention,
    keySymptoms,
    urgencyFlag,
    emergencyDetected: emergency.detected,
    emergencySignals: emergency.signals,
    suggestedStrandDetails: uniqueStrands.map((strand) => ({
      strand,
      ...STRAND_TIER_DETAILS[strand],
    })),
    ...(crisisMessage ? { crisisMessage } : {}),
    suggestedStrands: uniqueStrands as KnowledgeStrandType[],
    aiConfidence,
  };
}

/**
 * Validates that a CaseSummaryCard passes the mandatory safety gate
 * before being allowed to proceed to a paid expert session.
 *
 * Emergency cards are NOT blocked — they are routed differently (crisis flow).
 * Returns { allowed: true } or { allowed: false, reason: string }.
 */
export function validateSummaryCardForSession(card: CaseSummaryCard): {
  allowed: boolean;
  reason?: string;
} {
  if (card.emergencyDetected || card.urgencyFlag === "emergency") {
    return { allowed: false, reason: "Emergency signals must use the emergency support route instead of a standard case session." };
  }
  if (!card.headline || card.headline.trim().length < 3) {
    return { allowed: false, reason: "Headline is too short to start a session." };
  }
  if (card.aiConfidence < 25) {
    return {
      allowed: false,
      reason:
        "Confidence is too low to proceed. Please provide more detail about your concern.",
    };
  }
  if (!card.endorsedByUser) {
    return {
      allowed: false,
      reason: "You must confirm the summary card before the session can begin.",
    };
  }
  return { allowed: true };
}

// ─── Extended type with endorsement flag ──────────────────────────────────────

export interface EndorsedCaseSummaryCard extends CaseSummaryCard {
  endorsedByUser: boolean;
  endorsedAt?: Date;
}
