/**
 * Enhancement 9: Lowland Vector-Safe Iron Protocol Engine
 *
 * In Ethiopian lowlands (<2,000m) endemic for Plasmodium falciparum / P. vivax, Anopheles arabiensis
 * transmission surges during and following rainy seasons (September to December; May to June).
 * High-dose elemental iron supplementation during high-transmission periods provides free iron that accelerates
 * plasmodial schizogony, increasing the severity of malarial fevers.
 * This engine detects vector transmission risks and enforces the WHO/Ethiopian Ministry of health
 * vector-safe iron dosing protocols.
 */

export interface VectorRiskInput {
  altitudeMeters: number;
  region: string;
  month?: number; // 0-indexed (0 = Jan, 8 = Sept, etc.)
  intendedIronSupplementDoseMg?: number;
  isSleepingUnderInsecticideTreatedNet?: boolean;
}

export interface VectorSafeIronAssessment {
  isMalariaEndemicZone: boolean;
  isPeakTransmissionSeason: boolean;
  vectorRiskLevel: "minimal" | "moderate" | "high" | "critical";
  ironSafetyGateAction: "allow_standard" | "modify_to_food_sources_only" | "block_high_dose_supplement";
  gateWarningTitle?: string;
  clinicalRationale: string;
  recommendedDietaryIronAlternatives: string[];
  indigenousBotanicalRepellents: {
    plantName: string;
    botanicalName: string;
    applicationMethod: string;
    activeConstituents: string;
  }[];
}

const MALARIA_ENDEMIC_REGIONS = [
  "Gambela",
  "Benishangul-Gumuz",
  "Afar",
  "Metema",
  "Humera",
  "Awash",
  "Arba Minch",
  "Dire Dawa",
  "Somali",
  "Rift Valley Lowlands",
  "South Omo",
];

export function evaluateVectorSafeIron(input: VectorRiskInput): VectorSafeIronAssessment {
  const isLowlandAltitude = input.altitudeMeters < 2000;
  const isEndemicRegion = MALARIA_ENDEMIC_REGIONS.some((r) =>
    input.region.toLowerCase().includes(r.toLowerCase())
  );
  const isMalariaZone = isLowlandAltitude || isEndemicRegion;

  const month = input.month !== undefined ? input.month : new Date().getMonth();
  // Peak transmission: Post-Kiremt (Sept - Dec: months 8, 9, 10, 11) and Belg (May - June: months 4, 5)
  const isPeakTransmission = [8, 9, 10, 11, 4, 5].includes(month);

  let vectorRisk: VectorSafeIronAssessment["vectorRiskLevel"] = "minimal";
  if (isMalariaZone) {
    if (isPeakTransmission) {
      vectorRisk = input.isSleepingUnderInsecticideTreatedNet ? "high" : "critical";
    } else {
      vectorRisk = "moderate";
    }
  }

  const ironDose = input.intendedIronSupplementDoseMg || 0;
  let gateAction: VectorSafeIronAssessment["ironSafetyGateAction"] = "allow_standard";
  let gateWarning: string | undefined;

  if (isMalariaZone && ironDose >= 30) {
    gateAction = "block_high_dose_supplement";
    gateWarning = "SAFETY INTERCEPT: High-Dose Elemental Iron Supplementation Deferred in Malaria Zone";
  } else if (isMalariaZone && ironDose > 0) {
    gateAction = "modify_to_food_sources_only";
    gateWarning = "CAUTION: Recommend Dietary Iron Sources Rather than High-Concentration Salts";
  }

  return {
    isMalariaEndemicZone: isMalariaZone,
    isPeakTransmissionSeason: isPeakTransmission,
    vectorRiskLevel: vectorRisk,
    ironSafetyGateAction: gateAction,
    gateWarningTitle: gateWarning,
    clinicalRationale: isMalariaZone
      ? "Circulating non-transferrin-bound iron (NTBI) generated by high-dose oral iron supplements directly accelerates the erythrocytic cycle of Plasmodium falciparum. In vector transmission areas, prioritize iron from bioavailable fermented whole foods (teff, lentils, spinach) and ensure concurrent malaria screening before therapeutic pharmacologic iron is administered."
      : "Lowland vector risk is absent in highland elevations (>2,000m, e.g. Addis Ababa, Debre Berhan). Standard altitude-adjusted iron supplementation protocols apply safely.",
    recommendedDietaryIronAlternatives: [
      "Naturally Fermented 4-Day Teff Injera (high phytase-released iron without sudden serum NTBI spikes)",
      "Misir Wot (Red lentils stewed with red onions, garlic, and tomato)",
      "Sprouted Faba Beans (Baqela Nifro) paired with ascorbic acid from lemon or sweet peppers",
    ],
    indigenousBotanicalRepellents: [
      {
        plantName: "Damakesse",
        botanicalName: "Ocimum lamiifolium",
        applicationMethod: "Crush fresh leaves between palms and apply vapor close to face and extremities, or burn on charcoal embers.",
        activeConstituents: "Eugenol, linalool, and bornyl acetate exhibiting proven spatial deterrence against Anopheles arabiensis.",
      },
      {
        plantName: "Koseret",
        botanicalName: "Lippia abyssinica",
        applicationMethod: "Dry aerial leaves infused in domestic vapor fumigation or topical lipid extract.",
        activeConstituents: "Limonene and camphor acting as mild botanical spatial insect repellent.",
      },
    ],
  };
}
