/**
 * Column helpers for the MySQL 8 schema.
 *
 * The schema files describe tables with a small vocabulary (uuid, timestamp, jsonb, numeric …).
 * These helpers give that vocabulary one MySQL meaning, in one place:
 *
 *   uuid        CHAR-sized VARCHAR(36); ids are generated by the application (`defaultRandom`)
 *   timestamp   DATETIME(3), always UTC (the connection's time zone is pinned to +00:00)
 *   jsonb       JSON; parsed defensively because some drivers return JSON columns as text
 *   numeric     DECIMAL, returned as a string so no precision is lost
 *   date        DATE as a "YYYY-MM-DD" string
 *   bigserial   BIGINT UNSIGNED AUTO_INCREMENT
 *
 * Tables are declared with `mysqlTable` from this file. When DB_TABLE_PREFIX is set (for example
 * `wa_`, to share a database with another application) every table is read and written under
 * that prefix; the migration runner creates them the same way (scripts/table-prefix.mjs).
 */
import { sql, type ColumnBuilderBase, type HasDefault, type HasRuntimeDefault } from "drizzle-orm";
import {
  bigint,
  boolean,
  customType,
  date as mysqlDate,
  datetime,
  decimal,
  double,
  float,
  index,
  int,
  mysqlTableCreator,
  primaryKey,
  smallint,
  text,
  unique,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";

/** The validated DB_TABLE_PREFIX, or "" when the application has a database to itself. */
export function tablePrefix(): string {
  const prefix = (process.env.DB_TABLE_PREFIX ?? "").trim();
  if (!prefix) return "";
  // The same rule as scripts/table-prefix.mjs: the two must always agree on table names.
  if (!/^[a-z][a-z0-9]{0,10}_$/.test(prefix)) {
    throw new Error(`DB_TABLE_PREFIX "${prefix}" is not valid. Use 1–11 lowercase letters or digits followed by one underscore, for example wa_.`);
  }
  return prefix;
}

export const mysqlTable = mysqlTableCreator((name) => `${tablePrefix()}${name}`);

/** A new row id. Ids are created here rather than by the database, so inserts know them up front. */
export const newId = () => globalThis.crypto.randomUUID();

interface DefaultRandom {
  /** Fills the column with a new UUID when the insert does not supply one. */
  defaultRandom<T extends ColumnBuilderBase>(this: T): HasRuntimeDefault<HasDefault<T>>;
}

export function uuid<TName extends string>(name: TName) {
  const builder = varchar(name, { length: 36 });
  const withDefault: DefaultRandom = {
    defaultRandom(this: any) {
      return this.$defaultFn(newId);
    },
  };
  return Object.assign(builder, withDefault);
}

interface DefaultNow {
  /** The database's current time (UTC, millisecond precision) when the insert does not supply one. */
  defaultNow<T extends ColumnBuilderBase>(this: T): HasDefault<T>;
}

/** `withTimezone` is accepted for readability at call sites; every timestamp is stored in UTC. */
export function timestamp<TName extends string>(name: TName, _options?: { withTimezone?: boolean }) {
  const builder = datetime(name, { mode: "date", fsp: 3 });
  const withDefault: DefaultNow = {
    defaultNow(this: any) {
      return this.default(sql`CURRENT_TIMESTAMP(3)`);
    },
  };
  return Object.assign(builder, withDefault);
}

const json = customType<{ data: unknown; driverData: unknown }>({
  dataType: () => "json",
  toDriver: (value) => JSON.stringify(value),
  // MySQL drivers can return JSON columns as parsed values or JSON text.
  fromDriver: (value) => (typeof value === "string" ? JSON.parse(value) : value),
});

export function jsonb<TName extends string>(name: TName) {
  return json(name);
}

export function date<TName extends string>(name: TName) {
  return mysqlDate(name, { mode: "string" });
}

export function bigserial<TName extends string>(name: TName, _options?: { mode?: "number" | "bigint" }) {
  // Use BIGINT explicitly to avoid SERIAL's additional UNIQUE constraint.
  return bigint(name, { mode: "number", unsigned: true }).autoincrement();
}

export const integer = int;
export const numeric = decimal;
export const real = float;
export const doublePrecision = double;

export { boolean, decimal, index, primaryKey, smallint, text, unique, uniqueIndex, varchar };
