import { INTENSIVE_TRADITIONAL_MEDICINES, toMedicinalPlant } from "./traditionalMedicineDatabase";

export type PubMedEvidence = {
  pmid?: string;
  title: string;
  journal?: string;
  pubDate?: string;
  abstract?: string;
  source: "pubmed";
};

export type MedicinalPlant = {
  id: string;
  scientificName: string;
  vernacularName: string;
  amharicName?: string;
  growthForm: string;
  habitat: string;
  location?: string;
  geographicalDistribution?: string;
  plantParts: string[];
  traditionalUse: string;
  action?: string;
  modeOfAction?: string;
  modeOfPreparation?: string;
  dosage?: string;
  biochemicalComposition?: string[];
  activeIngredients?: string[];
  safetyNotes?: string;
  diseasesTreated: string[];
  source: string;
  sourceUrl?: string;
  pubmedEvidence?: PubMedEvidence[];
};

export const EPHI_ETHNOBOTANICAL_SOURCE_URL =
  "https://ephi.gov.et/research/traditional-modern-medicine/an-ethnobotanical-study-of-medicinal-plants-by-wereda/";

const RAW_MEDICINAL_PLANTS: MedicinalPlant[] = [
  {
    id: "acacia-abyssinica",
    scientificName: "Acacia abyssinica Hochst ex. Benth",
    vernacularName: "Qontir",
    amharicName: "ቆንቲር",
    growthForm: "Tree",
    habitat: "Deciduous bushland",
    plantParts: ["Leaves"],
    traditionalUse: "Used to treat goiter.",
    diseasesTreated: ["Goiter"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "acacia-nilotica",
    scientificName: "Acacia nilotica (L.) Del.",
    vernacularName: "Girar",
    amharicName: "ግራር",
    growthForm: "Tree",
    habitat: "Dry bushland",
    plantParts: ["Fruits", "Leaflets"],
    traditionalUse: "Traditionally used for diarrhea, diabetes, sore gums, hemorrhage, loose teeth, and stomach sickness.",
    diseasesTreated: ["Diarrhea", "Diabetes", "Sore gum", "Hemorrhage", "Stomach sickness"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "acacia-albida",
    scientificName: "Acacia albida Del.",
    vernacularName: "Grar",
    amharicName: "ግራር",
    growthForm: "Tree",
    habitat: "Dry bushland",
    plantParts: ["Latex"],
    traditionalUse: "Latex mixed with honey is used for amebiasis and fire wounds.",
    diseasesTreated: ["Amebiasis", "Fire wound"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "acmella-caulirhiza",
    scientificName: "Acmella caulirhiza Del.",
    vernacularName: "Yemdir berbere",
    amharicName: "የምድር በርበሬ",
    growthForm: "Herb",
    habitat: "Wetlands, forest floors, stream banks",
    plantParts: ["Leaves", "Flowers"],
    traditionalUse: "Flowers are chewed and spat onto tonsillitis lesions.",
    diseasesTreated: ["Tonsillitis"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "allium-sativum",
    scientificName: "Allium sativum L.",
    vernacularName: "Garlic",
    amharicName: "ነጭ ሽንኩርት",
    growthForm: "Herb",
    habitat: "Irrigable cultivated land, home garden",
    plantParts: ["Bulb"],
    traditionalUse: "Used to prevent and treat malaria.",
    diseasesTreated: ["Malaria"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "aloe-monticola",
    scientificName: "Aloe monticola Reynolds",
    vernacularName: "Eret",
    amharicName: "ኤረት",
    growthForm: "Herb",
    habitat: "Steep bare mountain slopes",
    plantParts: ["Root"],
    traditionalUse: "Root pounded and mixed with cold water and local alcohol to treat anthrax.",
    diseasesTreated: ["Anthrax"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "aloe-macrocarpa",
    scientificName: "Aloe macrocarpa Reynolds",
    vernacularName: "Aloe",
    amharicName: "አሎው",
    growthForm: "Herb",
    habitat: "Rocky slopes",
    plantParts: ["Leaves"],
    traditionalUse: "Leaf powder mixed with honey is used to prevent warts.",
    diseasesTreated: ["Wart"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "artemisia-abyssinica",
    scientificName: "Artemisia abyssinica Sch. Bip. ex Rich",
    vernacularName: "Chigugn",
    amharicName: "ቺጉን",
    growthForm: "Herb",
    habitat: "Juniper forest, open grassland, fallow fields",
    plantParts: ["Fresh root"],
    traditionalUse: "Crushed root is smelled and drunk in water to prevent evil spirit.",
    diseasesTreated: ["Evil spirit"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "asparagus-africanus",
    scientificName: "Asparagus africanus L.",
    vernacularName: "Yeset qest",
    amharicName: "የሴት ቀስት",
    growthForm: "Herb",
    habitat: "Acacia woodland; forest margins",
    plantParts: ["Roots"],
    traditionalUse: "Used for uterine and breast cancer.",
    diseasesTreated: ["Uterine cancer", "Breast cancer"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "bersama-abyssinica",
    scientificName: "Bersama abyssinica Fresen.",
    vernacularName: "Azamir",
    amharicName: "አዛሚር",
    growthForm: "Tree",
    habitat: "Riverine forest, rainforest",
    plantParts: ["Leaves", "Stem"],
    traditionalUse: "Leaf juice is squeezed onto wounds.",
    diseasesTreated: ["Wound"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "brucea-anti-dysenterica",
    scientificName: "Brucea anti dysenterica Fresen.",
    vernacularName: "Abalo",
    amharicName: "አባሎ",
    growthForm: "Shrub/Tree",
    habitat: "Montane evergreen forest margins",
    plantParts: ["Leaves"],
    traditionalUse: "Used for cancer, skin problems, leprosy, and external parasites.",
    diseasesTreated: ["Cancer", "Skin disease", "Leprosy", "External parasite"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "buddleja-polystachya",
    scientificName: "Buddleja polystachya Fresen.",
    vernacularName: "Anfar",
    amharicName: "አንፈር",
    growthForm: "Tree",
    habitat: "Degraded woodland around houses and cultivated fields",
    plantParts: ["Leaves"],
    traditionalUse: "Chewed and spat on cattle eye disease.",
    diseasesTreated: ["Cattle eye disease"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "calpurnia-aurea",
    scientificName: "Calpurnia aurea (Ait.) Benth.",
    vernacularName: "Digita",
    amharicName: "ድግታ",
    growthForm: "Shrub",
    habitat: "Forest margins, bushland/grassland",
    plantParts: ["Leaves", "Roots", "Seeds"],
    traditionalUse: "Boiled leaves with honey are used for snake bites; roots are used for amebiasis; seeds are used as fish poison and for dysentery.",
    diseasesTreated: ["Snake bite", "Amebiasis", "Dysentery"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "capparis-tomentosa",
    scientificName: "Capparis tomentosa Lam",
    vernacularName: "Capparis",
    amharicName: "ካፕራሪስ",
    growthForm: "Shrub",
    habitat: "Riverine forest, grassland with scattered trees",
    plantParts: ["Bark"],
    traditionalUse: "Powdered bark mixed with hot water is used for sore, anthrax, and evil eye.",
    diseasesTreated: ["Sore", "Anthrax", "Evil eye"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "carica-papaya",
    scientificName: "Carica papaya L.",
    vernacularName: "Papaya",
    amharicName: "ፓፓያ",
    growthForm: "Tree",
    habitat: "Home gardens, small and large plantations",
    plantParts: ["Seeds"],
    traditionalUse: "Ground boiled seeds with honey are used for diarrhea and ascariasis.",
    diseasesTreated: ["Diarrhea", "Ascariasis"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "carissa-edulis",
    scientificName: "Carissa edulis (Forsk.)",
    vernacularName: "Agam",
    amharicName: "አጋም",
    growthForm: "Shrub",
    habitat: "Open Acacia bushland",
    plantParts: ["Root"],
    traditionalUse: "Used to shorten labor just before delivery.",
    diseasesTreated: ["Labor facilitation"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "carissa-spinarum",
    scientificName: "Carissa spinarum L.",
    vernacularName: "Agam",
    amharicName: "አጋም",
    growthForm: "Shrub",
    habitat: "Disturbed areas, roadsides, riverine vegetation",
    plantParts: ["Roots"],
    traditionalUse: "Smoked roots are used for evil eye and powder is applied to wounds.",
    diseasesTreated: ["Evil eye", "Wound"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "clausena-anisata",
    scientificName: "Clausena anisata (Wild.) Benth.",
    vernacularName: "Limich",
    amharicName: "ሊሚች",
    growthForm: "Shrub",
    habitat: "Montane forest margins, moist forest, secondary bushland",
    plantParts: ["Leaves"],
    traditionalUse: "Pounded with Solanecio gigas and Justicia schimperiana leaves for skin irritation.",
    diseasesTreated: ["Skin irritation"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "citrus-aurantifolia",
    scientificName: "Citrus aurantifolia Swingle",
    vernacularName: "Bahre-Lomi",
    amharicName: "ባሕረ ሎሚ",
    growthForm: "Tree",
    habitat: "Lowlands, evergreen forest",
    plantParts: ["Fruit"],
    traditionalUse: "Used for dermatophyte-related skin disease.",
    diseasesTreated: ["Dermatophyte"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "citrus-sinensis",
    scientificName: "Citrus sinensis (L.) Engl.",
    vernacularName: "Birtukan",
    amharicName: "ብርቱካን",
    growthForm: "Shrub",
    habitat: "Cultivated in irrigable areas",
    plantParts: ["Fruit", "Bark"],
    traditionalUse: "Used for stomach infection and wound care.",
    diseasesTreated: ["Stomach infection", "Wound"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "clematis-hirsuta",
    scientificName: "Clematis hirsuta Per.",
    vernacularName: "Nech Azo hareg",
    amharicName: "ነች አዞ ሐረግ",
    growthForm: "Climber",
    habitat: "Forest edges, roadsides, paths",
    plantParts: ["Leaves", "Stems", "Bark"],
    traditionalUse: "Applied to tumors or cancers on the neck.",
    diseasesTreated: ["Neck tumor", "Cancer"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "clematis-simensis",
    scientificName: "Clematis simensis Fresen.",
    vernacularName: "Hareg",
    amharicName: "ሐረግ",
    growthForm: "Climber",
    habitat: "Forest edge and paths",
    plantParts: ["Leaves", "Root"],
    traditionalUse: "Used for wounds and stomachache.",
    diseasesTreated: ["Wound", "Stomachache"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "coffee-arabica",
    scientificName: "Coffee arabica L.",
    vernacularName: "Buna",
    amharicName: "ቡና",
    growthForm: "Shrub",
    habitat: "Shaded coffee plantations",
    plantParts: ["Seeds"],
    traditionalUse: "Pounded with honey for diarrhea.",
    diseasesTreated: ["Diarrhea"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "cordia-africana",
    scientificName: "Cordia africana Lam.",
    vernacularName: "Wanza",
    amharicName: "ዋንዛ",
    growthForm: "Tree",
    habitat: "Moist evergreen forest, riverine vegetation, woodland, grassland",
    plantParts: ["Roots"],
    traditionalUse: "Root powder is applied to itchy skin.",
    diseasesTreated: ["Itching"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "crinum-abyssinicum",
    scientificName: "Crinum abyssinicum",
    vernacularName: "Yejb shinkurt",
    amharicName: "የጅብ ሽንኩርት",
    growthForm: "Herb",
    habitat: "Waterlogged valley grasslands, swampy stream banks, fallow fields",
    plantParts: ["Leaves"],
    traditionalUse: "Used for tumor treatment in general.",
    diseasesTreated: ["Tumor"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "croton-macrostachyus",
    scientificName: "Croton macrostachyus Hochst. ex Del.",
    vernacularName: "Bisana",
    amharicName: "ቢሳና",
    growthForm: "Tree",
    habitat: "Forest margins, road edges, disturbed areas, woodland",
    plantParts: ["Bark"],
    traditionalUse: "Used for splenomegaly and gonorrhea.",
    diseasesTreated: ["Splenomegaly", "Gonorrhea"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "datura-stramonium",
    scientificName: "Datura stramonium L.",
    vernacularName: "Atse-faris",
    amharicName: "አፅ ፈሪስ",
    growthForm: "Herb",
    habitat: "Disturbed places, waste ground, roadsides, near water holes",
    plantParts: ["Seed"],
    traditionalUse: "Used to treat depression.",
    diseasesTreated: ["Depression"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "echinops-kebericho",
    scientificName: "Echinops kebericho, Mesfin",
    vernacularName: "Kebericho",
    amharicName: "ከበሪቾ",
    growthForm: "Herb/Shrub",
    habitat: "Montane Acacia woodland, disturbed bushland",
    plantParts: ["Root"],
    traditionalUse: "Used for toothache, vomiting, and headache.",
    diseasesTreated: ["Toothache", "Vomiting", "Headache"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "eucalyptus-globulus",
    scientificName: "Eucalyptus globulus Labill.",
    vernacularName: "Nech-bahirzaf",
    amharicName: "ነች ባሕርዛፍ",
    growthForm: "Tree",
    habitat: "Plantations and widely distributed sites",
    plantParts: ["Leaves"],
    traditionalUse: "Used for influenza and allergy.",
    diseasesTreated: ["Influenza", "Allergy"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "euclea-racemosa",
    scientificName: "Euclea racemosa L.",
    vernacularName: "Dedeho",
    amharicName: "ዴዴሆ",
    growthForm: "Shrub",
    habitat: "Open montane and bushland, clearings, margins",
    plantParts: ["Roots"],
    traditionalUse: "Used for evil spirit, evil eye, and heartburn.",
    diseasesTreated: ["Evil spirit", "Evil eye", "Heartburn"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "euphorbia-tirucalli",
    scientificName: "Euphorbia tirucalli L.",
    vernacularName: "Qinchib",
    amharicName: "ቅንጭብ",
    growthForm: "Shrub",
    habitat: "Live fence of home garden",
    plantParts: ["Roots", "Latex"],
    traditionalUse: "Used to treat tumor and cancer.",
    diseasesTreated: ["Tumor", "Cancer"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "euphorbia-abyssinica",
    scientificName: "Euphorbia abyssinica J.F. Gmel.",
    vernacularName: "Qulkual",
    amharicName: "ቁልቁል",
    growthForm: "Tree",
    habitat: "Steep rocky hillsides, church compounds, higher altitudes",
    plantParts: ["Latex"],
    traditionalUse: "Latex is used for skin cancer.",
    diseasesTreated: ["Skin cancer"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "ficus-sycomorus",
    scientificName: "Ficus sycomorus L.",
    vernacularName: "Banba",
    amharicName: "ባንባ",
    growthForm: "Tree",
    habitat: "River and lake margins, woodland, forest edges, wooded grassland",
    plantParts: ["Bark"],
    traditionalUse: "Used for hepatitis.",
    diseasesTreated: ["Hepatitis"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "gladiolus-schweinfurthii",
    scientificName: "Gladiolus schweinfurthii (Baker) Goldblatt and M.P. de Vos",
    vernacularName: "Milas golgul",
    amharicName: "ሚላስ ጎልጎል",
    growthForm: "Herb",
    habitat: "Open grassland; Acacia woodland; rocky limestone slope",
    plantParts: ["Root"],
    traditionalUse: "Used for headache.",
    diseasesTreated: ["Headache"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "guizotia-scabra",
    scientificName: "Guizotia scabra (Vis.) Chiov.",
    vernacularName: "Mechi",
    amharicName: "መቺ",
    growthForm: "Herb",
    habitat: "Open wasteland, grassland, cultivation, riverbanks",
    plantParts: ["Leaves"],
    traditionalUse: "Applied as a wound treatment.",
    diseasesTreated: ["Wound"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "hagenia-abyssinica",
    scientificName: "Hagenia abyssinica (Bruccie) T.F. Gmel",
    vernacularName: "Kosso",
    amharicName: "ኮሶ",
    growthForm: "Tree",
    habitat: "Montane forest and grassland; moist evergreen forest",
    plantParts: ["Fruits"],
    traditionalUse: "Traditional antihelmintic for tapeworm.",
    diseasesTreated: ["Tapeworm"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "justicia-schimperiana",
    scientificName: "Justicia schimperiana Hochst. ex A. Nees T. Anders",
    vernacularName: "Sensel",
    amharicName: "ሰንሰል",
    growthForm: "Shrub",
    habitat: "Open woodland, riverine vegetation, house live fence",
    plantParts: ["Leaves"],
    traditionalUse: "Used to prevent bat urine exposure-related harm.",
    diseasesTreated: ["Bat urine exposure"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "moringa-stenopetala",
    scientificName: "Moringa stenopetala (E.G. Baker) Cufod.",
    vernacularName: "Shiferaw",
    amharicName: "ሽፈራው",
    growthForm: "Tree",
    habitat: "Cultivated in terraced fields, gardens, small towns, riverine woodland",
    plantParts: ["Root"],
    traditionalUse: "Used for asthma relief.",
    diseasesTreated: ["Asthma"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "nigella-sativa",
    scientificName: "Nigella sativa L.",
    vernacularName: "Tikur azmud",
    amharicName: "ጥቁር አዝሙድ",
    growthForm: "Herb",
    habitat: "Cultivated in homesteads and fields",
    plantParts: ["Seed"],
    traditionalUse: "Used for headache.",
    diseasesTreated: ["Headache"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "ocimum-lamiifolium",
    scientificName: "Ocimum lamiifolium Hochst. ex. Benth.",
    vernacularName: "Damakesie",
    amharicName: "ዳማከሴ",
    growthForm: "Shrub",
    habitat: "Acacia-Commiphora bushland, limestone slopes, home gardens",
    plantParts: ["Leaves"],
    traditionalUse: "Used for febrile illness.",
    diseasesTreated: ["Febrile illness"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "olea-europaea",
    scientificName: "Olea europaea L.",
    vernacularName: "Woira",
    amharicName: "ወይራ",
    growthForm: "Tree",
    habitat: "Home garden, monasteries, churches, woody vegetation",
    plantParts: ["Leaves", "Roots"],
    traditionalUse: "Used for dysentery, wounds, stomachache, and bone tuberculosis.",
    diseasesTreated: ["Dysentery", "Wound", "Stomachache", "Bone TB"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "opuntia-ficus-indica",
    scientificName: "Opuntia ficus-indica (L.) Miller",
    vernacularName: "Yebereha qulkual",
    amharicName: "የበረሀ ቁልቁል",
    growthForm: "Shrub",
    habitat: "Disturbed and degraded areas; live fence of houses",
    plantParts: ["Leaves"],
    traditionalUse: "Used as a malaria vector control plant.",
    diseasesTreated: ["Malaria vector control"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "plumbago-zeylanica",
    scientificName: "Plumbago zeylanica L.",
    vernacularName: "Amira",
    amharicName: "አሚራ",
    growthForm: "Herb",
    habitat: "Disturbed habitats by roads and paths; bushland, savannah",
    plantParts: ["Root"],
    traditionalUse: "Used to prevent gonorrhea, hemorrhoids, and toothache.",
    diseasesTreated: ["Gonorrhea", "Hemorrhoids", "Toothache"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "premna-schimperi",
    scientificName: "Premna schimperi Engl.",
    vernacularName: "Chocho",
    amharicName: "ቾቾ",
    growthForm: "Shrub",
    habitat: "Degraded and secondary forests, grassy meadows, paths",
    plantParts: ["Root", "Leaves"],
    traditionalUse: "Use for mastitis and boils.",
    diseasesTreated: ["Mastitis", "Boils"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "solanum-nigrum",
    scientificName: "Solanum nigrum",
    vernacularName: "Embuay",
    amharicName: "እምቡአይ",
    growthForm: "Herb",
    habitat: "Cultivation and ruderal areas, roadsides, bushlands",
    plantParts: ["Leaves", "Roots", "Stems"],
    traditionalUse: "Used for cancerous sores, wounds, dysmenorrhea, dysentery, and sore throat.",
    diseasesTreated: ["Cancerous sore", "Wound", "Dysmenorrhea", "Dysentery", "Sore throat"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "solanum-incanum",
    scientificName: "Solanum incanum L.",
    vernacularName: "Tikur awud",
    amharicName: "ጥቁር አውድ",
    growthForm: "Herb",
    habitat: "Cultivated and riverine gallery forest, disturbed habitats",
    plantParts: ["Leaves", "Roots"],
    traditionalUse: "Used for bleeding, menstruation, and amebiasis.",
    diseasesTreated: ["Bleeding", "Menstruation", "Amebiasis"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "stephania-abyssinica",
    scientificName: "Stephania abyssinica (Dill. and A. Rich.) Walp.",
    vernacularName: "Yayit hareg",
    amharicName: "ያይት ሐረግ",
    growthForm: "Climber",
    habitat: "Thickets, forest margins, hillsides, cultivated fields",
    plantParts: ["Root"],
    traditionalUse: "Used for external tumors and stomachache.",
    diseasesTreated: ["External tumor", "Stomachache"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "stereospermum-kunthianum",
    scientificName: "Stereospermum kunthianum Cham.",
    vernacularName: "Arziniya",
    amharicName: "አርዚኒያ",
    growthForm: "Shrub/Tree",
    habitat: "Open woodland and savanna",
    plantParts: ["Bark"],
    traditionalUse: "Juice from bark is drunk for kidney problems.",
    diseasesTreated: ["Kidney disease"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "tamarindus-indica",
    scientificName: "Tamarindus indica L.",
    vernacularName: "Humer/Roqa",
    amharicName: "ሑመር/ሮቃ",
    growthForm: "Tree",
    habitat: "Grassland, woodland, Combretum bushland, riparian",
    plantParts: ["Fruit"],
    traditionalUse: "Fruit juice with hot water is used for stomachache, bile, and intestinal worms.",
    diseasesTreated: ["Stomachache", "Bile", "Intestinal worm"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "thymus-capitatus",
    scientificName: "Thymus capitatus (L.) Link",
    vernacularName: "Tosign",
    amharicName: "ጦስኝ",
    growthForm: "Herb",
    habitat: "Not reported",
    plantParts: ["Leaves"],
    traditionalUse: "Used for stomach disease, cough, and asthma.",
    diseasesTreated: ["Stomach disease", "Cough", "Asthma"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "tribulus-terrestris",
    scientificName: "Tribulus terrestris L.",
    vernacularName: "Kurnchit",
    amharicName: "ኩርንቺት",
    growthForm: "Herb",
    habitat: "Open disturbed places, sandy soils",
    plantParts: ["Stem", "Fruit", "Seed"],
    traditionalUse: "Used for scabrous skin disease, headache, hepatitis, liver problems, vertigo, stomatitis, kidney issues, anemia, hemorrhoids, and cough.",
    diseasesTreated: ["Scabrous skin disease", "Headache", "Hepatitis", "Vertigo", "Stomatitis", "Kidney issue", "Anemia", "Hemorrhoids", "Cough"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "urtica-pilulifera",
    scientificName: "Urtica pilulifera L.",
    vernacularName: "Sama",
    amharicName: "ሳማ",
    growthForm: "Herb",
    habitat: "Unknown",
    plantParts: ["Leaves"],
    traditionalUse: "Leaf juice mixed with oil is used for sore joints, rheumatism, and hemorrhage.",
    diseasesTreated: ["Sore joints", "Rheumatism", "Hemorrhage"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "vernonia-amygdalina",
    scientificName: "Vernonia amygdalina Del.",
    vernacularName: "Girawa",
    amharicName: "ግራዋ",
    growthForm: "Shrub",
    habitat: "Bush/woodland, forest habitats, home gardens",
    plantParts: ["Leaves"],
    traditionalUse: "Used for headache, intestinal worms, and general tumor/cancer treatment.",
    diseasesTreated: ["Headache", "Intestinal worm", "Tumor", "Cancer"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "ximenia-americana",
    scientificName: "Ximenia americana L.",
    vernacularName: "Enkoy",
    amharicName: "እንቆይ",
    growthForm: "Shrub",
    habitat: "Acacia woodland and wooded grassland",
    plantParts: ["Fruit", "Kernel", "Root"],
    traditionalUse: "Fruit kernel oil is applied to wounds; roots are used for stomachache and tonsillitis.",
    diseasesTreated: ["Wound", "Stomachache", "Tonsillitis"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "withania-somnifera",
    scientificName: "Withania somnifera L. Dunal",
    vernacularName: "Gizawa",
    amharicName: "ጊዛዋ",
    growthForm: "Shrub",
    habitat: "Cultivations, highland disturbed places, lake shores, riverbanks",
    plantParts: ["Leaves"],
    traditionalUse: "Used for malaria.",
    diseasesTreated: ["Malaria"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
  {
    id: "ziziphus-spina-christi",
    scientificName: "Ziziphus spina-christi (L.) Desf",
    vernacularName: "Qurqura",
    amharicName: "ቁርቁራ",
    growthForm: "Tree",
    habitat: "Wooded grassland, dry riverbeds, home gardens",
    plantParts: ["Fruits"],
    traditionalUse: "Used for stomachache, tonic, toothache, and tumors.",
    diseasesTreated: ["Stomachache", "Toothache", "Tumor"],
    source: "IntechOpen chapter 66996 (Moges & Moges, 2019)",
  },
];

function inferPreparationFromTraditionalUse(text: string): string {
  const normalizedText = text.toLowerCase();
  if (/mixed with honey|honey/.test(normalizedText)) return "Mixed with honey or warm preparation";
  if (/boiled|decoction/.test(normalizedText)) return "Boiled decoction";
  if (/powder/.test(normalizedText)) return "Powdered preparation";
  if (/chewed|spat/.test(normalizedText)) return "Direct chewing / topical application";
  if (/squeezed|juice|leaf juice/.test(normalizedText)) return "Fresh juice or expressed extract";
  if (/smelled|inhaled|drunk in water/.test(normalizedText)) return "Inhalation or water-based oral preparation";
  return "Traditional preparation recorded by local ethnobotanical practice";
}

const mappedIntensive = INTENSIVE_TRADITIONAL_MEDICINES.map(toMedicinalPlant);
const seenNames = new Set<string>();
const combinedRawPlants: MedicinalPlant[] = [];

for (const p of [...mappedIntensive, ...RAW_MEDICINAL_PLANTS]) {
  const normKey = p.scientificName.toLowerCase().trim();
  if (!seenNames.has(normKey)) {
    seenNames.add(normKey);
    combinedRawPlants.push(p);
  }
}

export const ETHIOPIAN_MEDICINAL_PLANTS: MedicinalPlant[] = combinedRawPlants.map((plant) => ({
  ...plant,
  location: plant.location ?? plant.habitat,
  action: plant.action ?? plant.traditionalUse,
  modeOfPreparation: plant.modeOfPreparation ?? inferPreparationFromTraditionalUse(plant.traditionalUse),
  sourceUrl: plant.sourceUrl ?? EPHI_ETHNOBOTANICAL_SOURCE_URL,
}));

export * from "./traditionalMedicineDatabase";

export const MEDICINAL_PLANT_DISEASES = [
  "Goiter",
  "Diarrhea",
  "Malaria",
  "Wound",
  "Headache",
  "Asthma",
  "Stomachache",
  "Cancer",
  "Tonsillitis",
  "Skin disease",
  "Kidney disease",
  "Tuberculosis",
  "Dysentery",
  "Evil eye",
  "Anthrax",
  "Snake bite",
  "Tumor",
  "Toothache",
  "Amebiasis",
  "Rheumatism",
  "Hemorrhoids",
  "Tapeworm",
  "Intestinal worm",
  "Mastitis",
  "Boils",
];

export function filterMedicinalPlants(query: string, disease?: string, plants?: MedicinalPlant[]) {
  const searchSpace = plants ?? ETHIOPIAN_MEDICINAL_PLANTS;
  const normalizedQuery = query.trim().toLowerCase();
  return searchSpace.filter((plant) => {
    const matchesDisease = !disease || disease === "all" || (plant.diseasesTreated || []).some((entry) => entry.toLowerCase().includes(disease.toLowerCase()));
    const matchesQuery =
      !normalizedQuery ||
      [
        plant.scientificName,
        plant.vernacularName,
        plant.amharicName ?? "",
        plant.habitat ?? "",
        plant.location ?? plant.habitat ?? "",
        plant.traditionalUse ?? "",
        plant.action ?? plant.traditionalUse ?? "",
        plant.modeOfPreparation ?? "",
        (plant.diseasesTreated || []).join(" "),
        plant.sourceUrl ?? "",
      ].some((value) => (value ?? "").toLowerCase().includes(normalizedQuery));
    return matchesDisease && matchesQuery;
  });
}
