import { MedicinalPlant } from "./ethiopianMedicinalPlants";

const ATTACHMENT_SOURCE =
  "User-provided Ethiopian medicinal-plant review (Pasted text #1)";

/**
 * Review-only records transcribed from the attached text.
 * Traditional use, pharmacological activity, and toxicity claims are not
 * clinical recommendations and require independent scientific review.
 */
const ATTACHMENT_PLANTS: MedicinalPlant[] = [
  {
    id: "hagenia-abyssinica",
    scientificName: "Hagenia abyssinica (Bruce) J.F.Gmel.",
    vernacularName: "Kosso",
    growthForm: "Tree",
    habitat: "Montane forest",
    location: "Ethiopian highlands, especially Bale and Kofele",
    geographicalDistribution: "Ethiopian highlands and eastern Africa",
    plantParts: ["Bark", "Flowers"],
    traditionalUse: "Traditional anthelmintic use, especially for tapeworm; also reported for fever, abdominal pain, respiratory complaints, wounds, diarrhea, and malaria.",
    action: "Anthelmintic activity is traditionally reported; pharmacological claims remain research-only.",
    modeOfAction: "Reported activity is associated with kosins and other phenolic constituents; clinical mechanism and efficacy are not established.",
    diseasesTreated: ["Tapeworm", "Fever", "Abdominal pain", "Respiratory illness", "Wound", "Diarrhea", "Malaria"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "croton-macrostachyus-attachment",
    scientificName: "Croton macrostachyus Hochst. ex Delile",
    vernacularName: "Bisana, Mekanisa, Tanbuk",
    growthForm: "Tree",
    habitat: "Woodland, riverine, and disturbed sites",
    location: "Widespread in Ethiopia",
    geographicalDistribution: "Ethiopia and tropical Africa",
    plantParts: ["Bark", "Latex", "Leaves"],
    traditionalUse: "Reported traditional use for malaria, diarrhea, wounds, hepatitis, tuberculosis, gonorrhea, pneumonia, and ascariasis.",
    action: "Traditional anti-inflammatory, antibacterial, antimalarial, and antitrypanosomal claims.",
    modeOfAction: "Diterpenoids, phenolics, flavonoids, and other constituents are reported in phytochemical studies; mechanism is not clinically validated.",
    diseasesTreated: ["Malaria", "Diarrhea", "Wound", "Hepatitis", "Tuberculosis", "Gonorrhea", "Pneumonia", "Ascariasis"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "moringa-stenopetala",
    scientificName: "Moringa stenopetala (Baker f.) Cufod.",
    vernacularName: "Shiferaw, Haleko, Cabbage tree",
    growthForm: "Tree",
    habitat: "Arid and semi-arid lowlands to mid-altitudes",
    location: "Konso, Gamo, and Wolayita",
    geographicalDistribution: "Southern Ethiopia and northern Kenya",
    plantParts: ["Leaves", "Seeds"],
    traditionalUse: "Reported use for hypertension, diabetes, malaria, asthma, wounds, diarrhea, kidney and liver complaints, and nutrition.",
    action: "Reported antioxidant and antimicrobial activity; traditional use is not proof of treatment efficacy.",
    modeOfAction: "Flavonoids, phenolic acids, glucosinolates, and isothiocyanates are reported constituents; human clinical evidence is limited.",
    diseasesTreated: ["Hypertension", "Diabetes", "Malaria", "Asthma", "Wound", "Diarrhea", "Kidney disease", "Liver disease"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "cordia-africana-attachment",
    scientificName: "Cordia africana Lam.",
    vernacularName: "Wanza, Awhi",
    growthForm: "Tree",
    habitat: "Woodland and savanna",
    location: "Widespread in Ethiopia",
    geographicalDistribution: "Ethiopia and tropical Africa",
    plantParts: ["Roots", "Bark", "Leaves"],
    traditionalUse: "Reported use for wounds, febrile illness, toothache, intestinal parasites, hepatitis, jaundice, and eye infections.",
    action: "Traditional antidiarrheal and antimalarial claims.",
    modeOfAction: "Phenolic compounds, flavonoids, terpenoids, alkaloids, tannins, and saponins are reported; mechanism is not established.",
    diseasesTreated: ["Wound", "Fever", "Toothache", "Intestinal parasite", "Hepatitis", "Jaundice", "Eye infection", "Diarrhea", "Malaria"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "olea-europaea-cuspidata",
    scientificName: "Olea europaea subsp. cuspidata",
    vernacularName: "Woira, African olive",
    growthForm: "Tree",
    habitat: "Highland and mid-altitude woodland",
    location: "Ethiopian highlands and mid-altitudes",
    geographicalDistribution: "Ethiopia and eastern Africa",
    plantParts: ["Leaves", "Bark", "Fruit"],
    traditionalUse: "Reported use for malaria, asthma, dandruff, toothache, trachoma, abdominal pain, hemorrhoids, and wounds.",
    action: "Traditional antimicrobial and anti-inflammatory claims.",
    modeOfAction: "Phenols, glycosides, tannins, and phytosterols are reported constituents; clinical mechanism is not established.",
    diseasesTreated: ["Malaria", "Asthma", "Dandruff", "Toothache", "Trachoma", "Abdominal pain", "Hemorrhoids", "Wound"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "rumex-abyssinicus",
    scientificName: "Rumex abyssinicus Jacq.",
    vernacularName: "Mekimeko",
    growthForm: "Herb",
    habitat: "Highlands and mid-altitudes",
    location: "Widespread in Ethiopia",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Roots", "Leaves"],
    traditionalUse: "Reported use for malaria, ascariasis, liver complaints, toothache, gonorrhea, dandruff, jaundice, asthma, and tuberculosis.",
    action: "Traditional antibacterial, antifungal, and diuretic claims.",
    modeOfAction: "Anthraquinones, flavonoids, tannins, and phenolic acids are reported; mechanism is not clinically established.",
    diseasesTreated: ["Malaria", "Ascariasis", "Liver disease", "Toothache", "Gonorrhea", "Dandruff", "Jaundice", "Asthma", "Tuberculosis"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "brucea-antidysenterica-attachment",
    scientificName: "Brucea antidysenterica J.F.Mill.",
    vernacularName: "Abalo",
    growthForm: "Shrub",
    habitat: "Montane forest and forest margins",
    location: "Ethiopian montane forests",
    geographicalDistribution: "Ethiopia and eastern Africa",
    plantParts: ["Leaves", "Bark"],
    traditionalUse: "Reported use for dysentery, snakebite, toothache, jaundice, gastritis, and malaria.",
    action: "Traditional antimalarial claim; evidence is not sufficient for treatment.",
    modeOfAction: "Quassinoids, alkaloids, and phenolics are reported constituents; mechanism and safe dose are not established.",
    diseasesTreated: ["Dysentery", "Snakebite", "Toothache", "Jaundice", "Gastritis", "Malaria"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "phytolacca-dodecandra",
    scientificName: "Phytolacca dodecandra L'Hér.",
    vernacularName: "Endod",
    growthForm: "Shrub",
    habitat: "Riverbanks and disturbed sites",
    location: "Widespread in Ethiopia",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Berries", "Leaves", "Roots"],
    traditionalUse: "Reported use in traditional practices and as a molluscicide; some sources mention rabies and skin conditions.",
    action: "Molluscicidal activity is associated with triterpenoid saponins; medicinal claims require strict review.",
    modeOfAction: "Saponins have surface-active and molluscicidal effects; human therapeutic use is not established.",
    diseasesTreated: ["Skin disease"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "ruta-chalepensis",
    scientificName: "Ruta chalepensis L.",
    vernacularName: "Tenadam, rue",
    growthForm: "Herb",
    habitat: "Cultivated and wild highland sites",
    location: "Ethiopian highlands and mid-altitudes",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Leaves", "Aerial parts"],
    traditionalUse: "Reported use for abdominal pain, fever, respiratory complaints, malaria, and infections.",
    action: "Traditional antimicrobial and antimalarial claims.",
    modeOfAction: "Essential oils, furanocoumarins, alkaloids, tannins, and saponins are reported; mechanism is not clinically established.",
    diseasesTreated: ["Abdominal pain", "Fever", "Respiratory illness", "Malaria", "Infection"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "allium-sativum-attachment",
    scientificName: "Allium sativum L.",
    vernacularName: "Nech shinkurt, garlic",
    amharicName: "ነጭ ሽንኩርት",
    growthForm: "Herb",
    habitat: "Home gardens and irrigated land",
    location: "Cultivated nationwide",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Bulb"],
    traditionalUse: "Reported use for malaria, abdominal pain, colds, and hypertension.",
    action: "Traditional antimicrobial claim.",
    modeOfAction: "Organosulfur compounds, especially allicin and diallyl sulfides, are reported active constituents.",
    diseasesTreated: ["Malaria", "Abdominal pain", "Cold", "Hypertension"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "vernonia-amygdalina",
    scientificName: "Vernonia amygdalina Delile",
    vernacularName: "Bitter leaf",
    growthForm: "Shrub",
    habitat: "Woodland and home gardens",
    location: "Widespread in Ethiopia",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Leaves"],
    traditionalUse: "Reported use for malaria, diabetes, gastrointestinal complaints, and infections.",
    action: "Traditional antimicrobial and antioxidant claims.",
    modeOfAction: "Sesquiterpene lactones, flavonoids, steroids, and vernoniosides are reported constituents.",
    diseasesTreated: ["Malaria", "Diabetes", "Gastrointestinal illness", "Infection"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "justicia-schimperiana-attachment",
    scientificName: "Justicia schimperiana (Hochst. ex Nees) T.Anderson",
    vernacularName: "Sensel",
    growthForm: "Shrub",
    habitat: "Highland and mid-altitude vegetation",
    location: "Ethiopian highlands and mid-altitudes",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Leaves", "Roots"],
    traditionalUse: "Reported use for gonorrhea, liver complaints, malaria, and wound healing.",
    action: "Traditional wound-healing and antimalarial claims.",
    modeOfAction: "Alkaloids and phenolics are reported; detailed pharmacological mechanism remains uncertain.",
    diseasesTreated: ["Gonorrhea", "Liver disease", "Malaria", "Wound"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "carissa-spinarum-attachment",
    scientificName: "Carissa spinarum L.",
    vernacularName: "Agam",
    growthForm: "Shrub",
    habitat: "Dry bushland and woodland",
    location: "Widespread across Ethiopian bushlands",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Roots", "Leaves"],
    traditionalUse: "Reported use for wounds, malaria, abdominal pain, and snakebite.",
    action: "Traditional wound-healing and antimalarial claims.",
    modeOfAction: "Alkaloids, phenolics, flavonoids, and cardiac glycosides are reported; cardiac safety requires review.",
    diseasesTreated: ["Wound", "Malaria", "Abdominal pain", "Snakebite"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "embelia-schimperi",
    scientificName: "Embelia schimperi Vatke",
    vernacularName: "Enkoko",
    growthForm: "Shrub",
    habitat: "Montane forest",
    location: "Ethiopian montane forests",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Fruit"],
    traditionalUse: "Traditional anthelmintic use for tapeworm and gastrointestinal parasites.",
    action: "Anthelmintic activity is traditionally reported.",
    modeOfAction: "Embelin and related benzoquinones are reported constituents; safe dosing requires professional review.",
    diseasesTreated: ["Tapeworm", "Intestinal parasite"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "calpurnia-aurea-attachment",
    scientificName: "Calpurnia aurea (Aiton) Benth.",
    vernacularName: "Digita",
    growthForm: "Shrub",
    habitat: "Woodland and forest",
    location: "Widespread in Ethiopia",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Leaves", "Roots", "Seeds"],
    traditionalUse: "Reported use for eye diseases, snakebite, vomiting, and stomach complaints.",
    action: "Traditional antimicrobial claim.",
    modeOfAction: "Quinolizidine alkaloids, flavonoids, and saponins are reported constituents.",
    diseasesTreated: ["Eye disease", "Snakebite", "Vomiting", "Stomach illness"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "aloe-species-attachment",
    scientificName: "Aloe spp. (including A. monticola and A. macrocarpa)",
    vernacularName: "Eret, aloe",
    amharicName: "እሬት",
    growthForm: "Succulent herb",
    habitat: "Rocky slopes and mountains",
    location: "Mountainous areas of Ethiopia",
    geographicalDistribution: "Ethiopia; several species are locally endemic",
    plantParts: ["Leaf gel", "Leaf latex"],
    traditionalUse: "Reported use for wounds, burns, anthrax, skin conditions, and constipation.",
    action: "Topical soothing and laxative claims are traditional references only.",
    modeOfAction: "Anthraquinones, polysaccharides, phenolics, aloin, aloe-emodin, and acemannan-like compounds are reported.",
    diseasesTreated: ["Wound", "Burn", "Anthrax", "Skin disease", "Constipation"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "withania-somnifera",
    scientificName: "Withania somnifera (L.) Dunal",
    vernacularName: "Girawa, ashwagandha-like",
    growthForm: "Shrub",
    habitat: "Cultivated and wild sites",
    location: "Various regions of Ethiopia",
    geographicalDistribution: "Ethiopia and other regions",
    plantParts: ["Roots", "Leaves"],
    traditionalUse: "Reported use for pneumonia, stress, inflammation, and infections.",
    action: "Traditional anti-inflammatory and antimicrobial claims.",
    modeOfAction: "Withanolides, withaferin A, alkaloids, and saponins are reported constituents.",
    diseasesTreated: ["Pneumonia", "Stress", "Inflammation", "Infection"],
    source: ATTACHMENT_SOURCE,
  },
  {
    id: "lepidium-sativum",
    scientificName: "Lepidium sativum L.",
    vernacularName: "Feto, garden cress",
    growthForm: "Herb",
    habitat: "Cultivated land and home gardens",
    location: "Cultivated nationwide",
    geographicalDistribution: "Ethiopia",
    plantParts: ["Seeds", "Leaves"],
    traditionalUse: "Reported use for asthma, cough, hypertension, wounds, and as a diuretic.",
    action: "Traditional expectorant and diuretic claims.",
    modeOfAction: "Glucosinolates, isothiocyanates, flavonoids, and phenolics are reported constituents.",
    diseasesTreated: ["Asthma", "Cough", "Hypertension", "Wound"],
    source: ATTACHMENT_SOURCE,
  },
];

const ATTACHMENT_BIOCHEMISTRY: Record<
  string,
  Pick<MedicinalPlant, "biochemicalComposition" | "activeIngredients" | "safetyNotes">
> = {
  "hagenia-abyssinica": {
    biochemicalComposition: ["Phenols", "Flavonoids", "Tannins", "Terpenoids", "Essential oils", "Phloroglucinol derivatives"],
    activeIngredients: ["Alpha-kosin", "Kosotoxin", "Protokosin", "Protocatechuic acid", "Quercetin", "Caffeic acid"],
    safetyNotes: "The attachment reports nausea, abdominal pain, diarrhea, visual toxicity, cardiovascular effects, abortion risk, and potentially fatal overdose. Do not self-administer.",
  },
  "croton-macrostachyus-attachment": {
    biochemicalComposition: ["Alkaloids", "Flavonoids", "Tannins", "Saponins", "Terpenoids", "Phenolic compounds", "Cardiac glycosides", "Essential oils"],
    activeIngredients: ["Benzyl benzoate", "Linalool", "Clerodane diterpenoids", "Lupeol", "Betulin", "Crotepoxide"],
    safetyNotes: "The attachment reports moderate toxicity in animal studies, possible cytotoxicity, and skin irritation from latex.",
  },
  "moringa-stenopetala": {
    biochemicalComposition: ["Proteins", "Vitamins A and C", "Minerals", "Flavonoids", "Phenolic acids", "Glucosinolates", "Saponins", "Tannins", "Phytosterols"],
    activeIngredients: ["Quercetin", "Kaempferol", "Rutin", "Chlorogenic acid", "Caffeic acid", "Isothiocyanates", "Oleic acid"],
    safetyNotes: "The attachment describes dietary use as generally tolerated but notes possible hypotension and goitrogenic factors in raw leaves; clinical data are limited.",
  },
  "cordia-africana-attachment": {
    biochemicalComposition: ["Flavonoids", "Terpenoids", "Alkaloids", "Phenols", "Tannins", "Saponins"],
    activeIngredients: ["Phenolic compounds", "Flavonoids"],
    safetyNotes: "The attachment reports relatively low acute toxicity in some studies, but evidence remains limited.",
  },
  "olea-europaea-cuspidata": {
    biochemicalComposition: ["Alkaloids", "Glycosides", "Tannins", "Phytosterols", "Phenols"],
    activeIngredients: ["Oleuropein-like compounds", "Phenols"],
    safetyNotes: "The attachment reports low acute toxicity in some studies; this does not establish a safe medicinal dose.",
  },
  "rumex-abyssinicus": {
    biochemicalComposition: ["Anthraquinones", "Flavonoids", "Tannins", "Phenolic acids"],
    activeIngredients: ["Anthraquinones", "Flavonoids"],
    safetyNotes: "High doses may cause gastrointestinal irritation or laxative effects according to the attachment.",
  },
  "brucea-antidysenterica-attachment": {
    biochemicalComposition: ["Quassinoids", "Alkaloids", "Phenolics"],
    activeIngredients: ["Bruceantin-like quassinoids", "Alkaloids"],
    safetyNotes: "Potential toxicity is reported; do not use without qualified professional review.",
  },
  "phytolacca-dodecandra": {
    biochemicalComposition: ["Saponins", "Triterpenoids"],
    activeIngredients: ["Molluscicidal saponins"],
    safetyNotes: "The attachment reports vomiting and high-dose toxicity and restricts use in children and pregnancy.",
  },
  "ruta-chalepensis": {
    biochemicalComposition: ["Alkaloids", "Tannins", "Saponins", "Essential oils", "Furanocoumarins"],
    activeIngredients: ["Rutin", "Furanocoumarins", "Alkaloids"],
    safetyNotes: "The attachment reports photosensitivity, gastrointestinal upset, high-dose toxicity, and pregnancy risk.",
  },
  "allium-sativum-attachment": {
    biochemicalComposition: ["Organosulfur compounds", "Flavonoids"],
    activeIngredients: ["Allicin", "Diallyl sulfides"],
    safetyNotes: "The attachment reports heartburn and increased bleeding risk at high doses.",
  },
  "vernonia-amygdalina": {
    biochemicalComposition: ["Sesquiterpene lactones", "Flavonoids", "Steroids"],
    activeIngredients: ["Vernoniosides", "Flavonoids"],
    safetyNotes: "The attachment reports possible gastrointestinal irritation; dose and clinical safety are not established.",
  },
  "justicia-schimperiana-attachment": {
    biochemicalComposition: ["Alkaloids", "Phenolics"],
    activeIngredients: ["Alkaloids", "Phenolics"],
    safetyNotes: "Detailed toxicity data are limited according to the attachment.",
  },
  "carissa-spinarum-attachment": {
    biochemicalComposition: ["Alkaloids", "Cardiac glycosides", "Phenolics", "Flavonoids"],
    activeIngredients: ["Cardiac glycosides", "Alkaloids"],
    safetyNotes: "Potential cardiac effects in overdose are reported; use requires professional review.",
  },
  "embelia-schimperi": {
    biochemicalComposition: ["Benzoquinones", "Phenolics"],
    activeIngredients: ["Embelin"],
    safetyNotes: "The attachment reports possible gastrointestinal upset and dose-related effects.",
  },
  "calpurnia-aurea-attachment": {
    biochemicalComposition: ["Alkaloids", "Flavonoids", "Saponins"],
    activeIngredients: ["Quinolizidine alkaloids"],
    safetyNotes: "Potential alkaloid toxicity is reported; acute safety data are limited.",
  },
  "aloe-species-attachment": {
    biochemicalComposition: ["Anthraquinones", "Polysaccharides", "Phenolics"],
    activeIngredients: ["Aloin", "Aloe-emodin", "Acemannan-like compounds"],
    safetyNotes: "The attachment reports laxation, cramping, electrolyte imbalance with long-term use, and latex irritation.",
  },
  "withania-somnifera": {
    biochemicalComposition: ["Withanolides", "Alkaloids", "Saponins"],
    activeIngredients: ["Withaferin A", "Withanolides"],
    safetyNotes: "The attachment reports possible gastrointestinal upset or sedation at high doses.",
  },
  "lepidium-sativum": {
    biochemicalComposition: ["Glucosinolates", "Flavonoids", "Phenolics"],
    activeIngredients: ["Glucosinolates", "Isothiocyanates"],
    safetyNotes: "The attachment reports general dietary tolerance but possible gastrointestinal irritation at high doses.",
  },
};

export const ETHIOPIAN_MEDICINAL_PLANTS_CUSTOM = ATTACHMENT_PLANTS.map((plant) => ({
  ...plant,
  ...ATTACHMENT_BIOCHEMISTRY[plant.id],
}));
