/**
 * Animal Product Nutritional Profiles — Ethiopian & Universal
 * 50 entries: 10 reference profiles and 40 low-confidence category proxies.
 * Proxy nutrient values are not product-specific laboratory measurements.
 * Covers: beef, lamb, goat, poultry, fish, eggs, dairy, organ meats.
 * Animal products are the primary source of: complete protein,
 * vitamin B12, heme iron, long-chain fatty acids (EPA/DHA/AA),
 * cholesterol, preformed vitamin A, and all 21 amino acids.
 * Sources: USDA FoodData Central, FAO/INFOODS AFDB, EFCT 2025.
 */

import type { DeepIngredientProfile } from "./deepNutrientProfiles";

const CORE_ANIMAL_PRODUCT_PROFILES: DeepIngredientProfile[] = [
  // ── 1. Beef Tibs (Lean Beef, raw) ───────────────────────────
  {
    uid: "anm-beef-lean",
    nameEn: "Lean Beef (Tibs cut)",
    nameAmharic: "ጥሬ ሥጋ / ትብስ ስጋ",
    scientificName: "Bos taurus",
    category: "Red Meat",
    partUsed: "Longissimus muscle (lean, raw)",
    processingState: "raw",
    basis: "per 100 g raw lean beef",
    proximate: {
      energyKcal: 150, moisture_g: 72.0, protein_g: 21.2,
      fat_g: 6.5, carbohydrate_g: 0.0, dietaryFiber_g: 0.0, ash_g: 1.1,
    },
    minerals: {
      calcium_mg: 18, phosphorus_mg: 198, magnesium_mg: 22,
      potassium_mg: 318, sodium_mg: 62, sulfur_mg: 248,
      iron_mg: 2.6, zinc_mg: 4.8, copper_mg: 0.09,
      manganese_mg: 0.014, selenium_mcg: 14.2, molybdenum_mcg: 8,
      boron_mcg: 8, iodine_mcg: 6, chromium_mcg: 3,
    },
    vitamins: {
      vitaminA_retinolEquiv_mcg: 0, vitaminB1_thiamine_mg: 0.07,
      vitaminB2_riboflavin_mg: 0.18, vitaminB3_niacin_mg: 5.4,
      vitaminB5_pantothenicAcid_mg: 0.59, vitaminB6_pyridoxine_mg: 0.38,
      vitaminB9_folate_mcg: 8, vitaminB12_cobalamin_mcg: 2.5,
      vitaminD_mcg: 0.1, vitaminE_tocopherol_mg: 0.16, vitaminK_mcg: 1.5,
    },
    aminoAcids: {
      essential: {
        histidine: 6.8, isoleucine: 4.8, leucine: 8.4,
        lysine: 8.9, methionine: 2.5, phenylalanine: 4.1,
        threonine: 4.4, tryptophan: 1.1, valine: 5.2,
      },
      semiEssential: {
        arginine: 6.8, cysteine: 1.2, glycine: 6.4,
        proline: 4.8, tyrosine: 3.4,
      },
      nonEssential: {
        alanine: 6.4, asparagine: 2.0, aspartate: 9.4,
        glutamate: 15.8, glutamine: 8.6, serine: 3.8,
        hydroxyproline: 2.2,
      },
      totalAminoAcidsMgPer100g: 18900,
      limitingAmino: "None — complete protein, exceeds all EAA requirements",
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 2.75, totalMonounsaturatedG: 2.84, totalPolyunsaturatedG: 0.28,
      totalTransFatG: 0.18, cholesterol_mg: 62,
      myristic_C14_0: 0.16, palmitic_C16_0: 2.08, stearic_C18_0: 0.51,
      oleic_C18_1: 2.82, vaccenic_C18_1t: 0.12,
      linoleic_C18_2n6: 0.24, alphaLinolenic_C18_3n3: 0.04,
      arachidonic_C20_4n6: 0.06, eicosaPentaenoic_C20_5n3: 0.01,
      docosaHexaenoic_C22_6n3: 0.02,
      omega3ToOmega6Ratio: "1:6",
    },
    glycemicIndex: 0,
    functionalProperties: [
      "Complete protein: all 9 EAA in abundant quantities (PDCAAS 1.0)",
      "Heme iron (2.6 mg) with 15–35% absorption vs 2–8% non-heme",
      "Outstanding zinc (4.8 mg) for immune and reproductive function",
      "Vitamin B12 (2.5 mcg) — exclusive to animal foods",
      "Carnosine: anti-glycation and muscle fatigue buffer",
    ],
    bioavailabilityNotes: "Heme iron from beef is absorbed at 15–35%, 5–10× higher than non-heme iron. Beef consumption simultaneously enhances non-heme iron absorption from co-ingested plant foods ('meat factor'). Zinc from beef is highly bioavailable (40%) vs plant sources (~20%).",
    sourceReferences: ["USDA FoodData Central #174032", "Dahl et al. (2012) Adv Nutr"],
    dataConfidence: "high",
  },

  // ── 2. Lamb / Goat Meat (Beg Tibs) ──────────────────────────
  {
    uid: "anm-lamb",
    nameEn: "Lamb / Goat Meat",
    nameAmharic: "የበግ ሥጋ / ቤጎ",
    scientificName: "Ovis aries / Capra hircus",
    category: "Red Meat",
    partUsed: "Leg muscle (lean, raw)",
    processingState: "raw",
    basis: "per 100 g raw lean lamb/goat",
    proximate: {
      energyKcal: 145, moisture_g: 73.2, protein_g: 20.1,
      fat_g: 6.8, carbohydrate_g: 0.0, dietaryFiber_g: 0.0, ash_g: 1.2,
    },
    minerals: {
      calcium_mg: 16, phosphorus_mg: 182, magnesium_mg: 21,
      potassium_mg: 312, sodium_mg: 72, sulfur_mg: 232,
      iron_mg: 2.1, zinc_mg: 3.8, copper_mg: 0.12,
      manganese_mg: 0.022, selenium_mcg: 8.8, boron_mcg: 6,
      iodine_mcg: 8, chromium_mcg: 2,
    },
    vitamins: {
      vitaminB1_thiamine_mg: 0.12, vitaminB2_riboflavin_mg: 0.24,
      vitaminB3_niacin_mg: 5.7, vitaminB5_pantothenicAcid_mg: 0.62,
      vitaminB6_pyridoxine_mg: 0.14, vitaminB9_folate_mcg: 4,
      vitaminB12_cobalamin_mcg: 2.2, vitaminD_mcg: 0.1,
      vitaminE_tocopherol_mg: 0.12,
    },
    aminoAcids: {
      essential: {
        histidine: 6.4, isoleucine: 4.7, leucine: 8.0,
        lysine: 8.4, methionine: 2.3, phenylalanine: 3.9,
        threonine: 4.2, tryptophan: 1.0, valine: 4.9,
      },
      semiEssential: {
        arginine: 6.4, cysteine: 1.1, glycine: 5.9, proline: 4.4, tyrosine: 3.1,
      },
      nonEssential: {
        alanine: 6.1, asparagine: 1.9, aspartate: 8.9,
        glutamate: 15.1, glutamine: 8.0, serine: 3.5, hydroxyproline: 2.0,
      },
      totalAminoAcidsMgPer100g: 17890,
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 3.22, totalMonounsaturatedG: 3.12, totalPolyunsaturatedG: 0.52,
      totalTransFatG: 0.22, cholesterol_mg: 68,
      myristic_C14_0: 0.38, palmitic_C16_0: 2.12, stearic_C18_0: 0.72,
      oleic_C18_1: 3.10, vaccenic_C18_1t: 0.15,
      linoleic_C18_2n6: 0.44, alphaLinolenic_C18_3n3: 0.08,
      arachidonic_C20_4n6: 0.12, eicosaPentaenoic_C20_5n3: 0.02,
      docosaHexaenoic_C22_6n3: 0.04,
      omega3ToOmega6Ratio: "1:5.5",
    },
    glycemicIndex: 0,
    functionalProperties: [
      "Complete protein with carnosine and anserine (imidazole dipeptides)",
      "Conjugated linoleic acid (CLA) in ruminant fat: anti-cancer and anti-adipogenic",
      "Natural trans fat (vaccenic acid): cardioprotective, not industrial trans fat",
      "Rich L-carnitine for fatty acid mitochondrial transport",
    ],
    bioavailabilityNotes: "Goat meat has slightly lower fat than lamb. Both ruminant animals produce CLA (conjugated linoleic acid) in their rumen fat — biologically distinct from industrial trans fats and associated with reduced adiposity in intervention studies.",
    sourceReferences: ["USDA FoodData Central #174028", "FAO East Africa FCT"],
    dataConfidence: "high",
  },

  // ── 3. Chicken Breast (Doro) ─────────────────────────────────
  {
    uid: "anm-chicken-breast",
    nameEn: "Chicken Breast (skinless, raw)",
    nameAmharic: "የዶሮ ሥጋ",
    scientificName: "Gallus gallus domesticus",
    category: "Poultry",
    partUsed: "Breast muscle, skinless",
    processingState: "raw",
    basis: "per 100 g raw skinless chicken breast",
    proximate: {
      energyKcal: 120, moisture_g: 74.9, protein_g: 22.5,
      fat_g: 2.62, carbohydrate_g: 0.0, dietaryFiber_g: 0.0, ash_g: 1.0,
    },
    minerals: {
      calcium_mg: 11, phosphorus_mg: 220, magnesium_mg: 27,
      potassium_mg: 370, sodium_mg: 65, sulfur_mg: 268,
      iron_mg: 0.89, zinc_mg: 0.8, copper_mg: 0.042,
      manganese_mg: 0.018, selenium_mcg: 27.6, boron_mcg: 4, iodine_mcg: 7,
    },
    vitamins: {
      vitaminB1_thiamine_mg: 0.07, vitaminB2_riboflavin_mg: 0.12,
      vitaminB3_niacin_mg: 11.8, vitaminB5_pantothenicAcid_mg: 1.09,
      vitaminB6_pyridoxine_mg: 0.87, vitaminB9_folate_mcg: 4,
      vitaminB12_cobalamin_mcg: 0.3, vitaminD_mcg: 0.1,
      vitaminE_tocopherol_mg: 0.27,
    },
    aminoAcids: {
      essential: {
        histidine: 5.5, isoleucine: 5.1, leucine: 7.9,
        lysine: 8.4, methionine: 2.8, phenylalanine: 4.2,
        threonine: 4.4, tryptophan: 1.2, valine: 5.0,
      },
      semiEssential: {
        arginine: 6.9, cysteine: 1.3, glycine: 4.5, proline: 3.9, tyrosine: 3.5,
      },
      nonEssential: {
        alanine: 5.6, asparagine: 2.1, aspartate: 9.8,
        glutamate: 16.2, glutamine: 9.0, serine: 3.6, hydroxyproline: 0.8,
      },
      totalAminoAcidsMgPer100g: 20100,
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 0.72, totalMonounsaturatedG: 0.88, totalPolyunsaturatedG: 0.57,
      cholesterol_mg: 64,
      palmitic_C16_0: 0.65, stearic_C18_0: 0.07,
      oleic_C18_1: 0.87, linoleic_C18_2n6: 0.52,
      alphaLinolenic_C18_3n3: 0.04, arachidonic_C20_4n6: 0.08,
      eicosaPentaenoic_C20_5n3: 0.01, docosaHexaenoic_C22_6n3: 0.03,
      omega3ToOmega6Ratio: "1:13",
    },
    glycemicIndex: 0,
    functionalProperties: [
      "Highest niacin (B3) of all common meats (11.8 mg) — NAD+ metabolism",
      "Outstanding selenium (27.6 mcg) — GPx antioxidant enzyme cofactor",
      "Complete protein at only 120 kcal — highest protein-to-energy ratio",
      "Rich B6 for amino acid catabolism and neurotransmitter synthesis",
    ],
    bioavailabilityNotes: "Chicken breast provides the highest leucine-to-energy ratio of common foods, making it optimal for muscle protein synthesis per calorie. Selenium bioavailability from poultry (as selenomethionine) is ~90%.",
    sourceReferences: ["USDA FoodData Central #171477"],
    dataConfidence: "high",
  },

  // ── 4. Egg (Whole) ───────────────────────────────────────────
  {
    uid: "anm-egg-whole",
    nameEn: "Whole Egg (raw)",
    nameAmharic: "እንቁላል",
    scientificName: "Gallus gallus domesticus",
    category: "Egg",
    partUsed: "Whole egg (yolk + white)",
    processingState: "raw",
    basis: "per 100 g raw whole egg (≈2 medium eggs)",
    proximate: {
      energyKcal: 143, moisture_g: 76.2, protein_g: 12.56,
      fat_g: 9.51, carbohydrate_g: 0.72, dietaryFiber_g: 0.0, ash_g: 1.06,
    },
    minerals: {
      calcium_mg: 56, phosphorus_mg: 198, magnesium_mg: 12,
      potassium_mg: 138, sodium_mg: 142, sulfur_mg: 182,
      iron_mg: 1.75, zinc_mg: 1.29, copper_mg: 0.072,
      manganese_mg: 0.028, selenium_mcg: 30.7, boron_mcg: 22,
      iodine_mcg: 25, chromium_mcg: 2,
    },
    vitamins: {
      vitaminA_retinolEquiv_mcg: 160, betaCarotene_mcg: 0,
      vitaminB1_thiamine_mg: 0.069, vitaminB2_riboflavin_mg: 0.478,
      vitaminB3_niacin_mg: 0.064, vitaminB5_pantothenicAcid_mg: 1.533,
      vitaminB6_pyridoxine_mg: 0.17, vitaminB9_folate_mcg: 47,
      vitaminB12_cobalamin_mcg: 0.89, vitaminD_mcg: 1.1,
      vitaminE_tocopherol_mg: 1.05, vitaminK_mcg: 0.3,
    },
    aminoAcids: {
      essential: {
        histidine: 2.4, isoleucine: 5.4, leucine: 8.8,
        lysine: 7.3, methionine: 3.2, phenylalanine: 5.8,
        threonine: 4.9, tryptophan: 1.7, valine: 6.6,
      },
      semiEssential: {
        arginine: 6.4, cysteine: 2.4, glycine: 3.5, proline: 4.2, tyrosine: 4.2,
      },
      nonEssential: {
        alanine: 6.0, asparagine: 2.0, aspartate: 11.1,
        glutamate: 12.6, glutamine: 6.5, serine: 9.3, hydroxyproline: 0.0,
      },
      totalAminoAcidsMgPer100g: 11230,
      limitingAmino: "None — PDCAAS reference protein (score = 100)",
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 3.10, totalMonounsaturatedG: 3.66, totalPolyunsaturatedG: 1.91,
      cholesterol_mg: 373,
      myristic_C14_0: 0.04, palmitic_C16_0: 2.55, stearic_C18_0: 0.51,
      oleic_C18_1: 3.64, linoleic_C18_2n6: 1.39,
      alphaLinolenic_C18_3n3: 0.04, arachidonic_C20_4n6: 0.22,
      eicosaPentaenoic_C20_5n3: 0.0, docosaHexaenoic_C22_6n3: 0.04,
      omega3ToOmega6Ratio: "1:35",
      note: "DHA enriched eggs from omega-3 fed hens contain 150–300 mg DHA vs standard 35 mg.",
    },
    glycemicIndex: 0,
    functionalProperties: [
      "PDCAAS = 100 — the gold standard reference protein for amino acid scoring",
      "Highest dietary choline source (251 mg/100g) — liver function, neurodevelopment",
      "Outstanding riboflavin (B2) for oxidative metabolism",
      "Lutein (252 mcg) + zeaxanthin (217 mcg) in yolk for macular protection",
      "Preformed vitamin A (160 mcg RAE) in yolk for immune and epithelial integrity",
    ],
    bioavailabilityNotes: "Cooked egg protein is 91% digestible vs 51% raw (Evenepoel et al., 1998). Egg cholesterol (373 mg) has minimal impact on blood cholesterol in most individuals — dietary cholesterol effect is overridden by saturated fat intake. Egg consumption increased HDL in 70% of studies.",
    sourceReferences: ["USDA FoodData Central #173424", "Evenepoel et al. (1998) Gastroenterology"],
    dataConfidence: "high",
  },

  // ── 5. Cow's Milk (Whole) ────────────────────────────────────
  {
    uid: "anm-milk-whole",
    nameEn: "Whole Cow's Milk",
    nameAmharic: "ወተት",
    scientificName: "Bos taurus",
    category: "Dairy",
    partUsed: "Whole milk (3.25% fat)",
    processingState: "raw/pasteurized",
    basis: "per 100 g (≈100 mL) whole milk",
    proximate: {
      energyKcal: 61, moisture_g: 87.4, protein_g: 3.22,
      fat_g: 3.34, carbohydrate_g: 4.80, dietaryFiber_g: 0.0, ash_g: 0.74, sugars_g: 4.80,
    },
    minerals: {
      calcium_mg: 113, phosphorus_mg: 84, magnesium_mg: 10,
      potassium_mg: 132, sodium_mg: 43, sulfur_mg: 32, chloride_mg: 97,
      iron_mg: 0.03, zinc_mg: 0.37, copper_mg: 0.01,
      manganese_mg: 0.003, selenium_mcg: 3.7, iodine_mcg: 56,
      boron_mcg: 20, chromium_mcg: 0.3,
    },
    vitamins: {
      vitaminA_retinolEquiv_mcg: 46, betaCarotene_mcg: 21,
      vitaminB1_thiamine_mg: 0.046, vitaminB2_riboflavin_mg: 0.169,
      vitaminB3_niacin_mg: 0.089, vitaminB5_pantothenicAcid_mg: 0.314,
      vitaminB6_pyridoxine_mg: 0.042, vitaminB9_folate_mcg: 5,
      vitaminB12_cobalamin_mcg: 0.45, vitaminD_mcg: 1.3,
      vitaminE_tocopherol_mg: 0.07, vitaminK_mcg: 0.3,
    },
    aminoAcids: {
      essential: {
        histidine: 2.7, isoleucine: 6.2, leucine: 10.0,
        lysine: 7.9, methionine: 2.5, phenylalanine: 4.9,
        threonine: 4.6, tryptophan: 1.4, valine: 6.8,
      },
      semiEssential: {
        arginine: 3.5, cysteine: 0.8, glycine: 1.9, proline: 10.0, tyrosine: 5.4,
      },
      nonEssential: {
        alanine: 3.5, asparagine: 0.8, aspartate: 7.4,
        glutamate: 20.9, glutamine: 0.0, serine: 5.5,
      },
      totalAminoAcidsMgPer100g: 2920,
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 2.08, totalMonounsaturatedG: 0.81, totalPolyunsaturatedG: 0.12,
      totalTransFatG: 0.08, cholesterol_mg: 10,
      butyric_C4_0: 0.11, caproic_C6_0: 0.07, caprylic_C8_0: 0.05,
      capric_C10_0: 0.10, lauric_C12_0: 0.13, myristic_C14_0: 0.37,
      palmitic_C16_0: 0.96, stearic_C18_0: 0.28,
      oleic_C18_1: 0.79, vaccenic_C18_1t: 0.05,
      linoleic_C18_2n6: 0.11, alphaLinolenic_C18_3n3: 0.01,
      arachidonic_C20_4n6: 0.008, docosaHexaenoic_C22_6n3: 0.006,
      omega3ToOmega6Ratio: "1:11",
      note: "Short-chain fatty acids (butyric C4:0) are beneficial postbiotics for colonocyte health, distinct from SCFAs produced by gut fermentation.",
    },
    glycemicIndex: 31,
    functionalProperties: [
      "Richest dietary calcium source (113 mg) with highest bioavailability (32%)",
      "Outstanding iodine source (56 mcg) — critical for thyroid function",
      "Lactoferrin: iron-binding antimicrobial glycoprotein in whey",
      "BCAA profile (leucine + isoleucine + valine) ideal for muscle protein synthesis",
      "Short-chain fatty acids (butyric acid) for colonic epithelial health",
    ],
    bioavailabilityNotes: "Milk calcium is the most bioavailable dietary calcium (fractional absorption 32%), with casein phosphopeptides acting as mineral carriers. Lactose enhances calcium absorption. Fermentation to yogurt (ergo) further increases calcium and eliminates lactose intolerance.",
    sourceReferences: ["USDA FoodData Central #171265", "Dahl et al. (2012) Adv Nutr"],
    dataConfidence: "high",
  },

  // ── 6. Ayib (Ethiopian Cottage Cheese) ───────────────────────
  {
    uid: "anm-ayib",
    nameEn: "Ayib (Ethiopian Cottage Cheese)",
    nameAmharic: "አይብ",
    scientificName: "Bos taurus (fermented/drained whey cheese)",
    category: "Dairy",
    partUsed: "Soft fresh cheese curds",
    processingState: "fermented/coagulated",
    basis: "per 100 g ayib",
    proximate: {
      energyKcal: 98, moisture_g: 79.8, protein_g: 11.1,
      fat_g: 4.5, carbohydrate_g: 3.4, dietaryFiber_g: 0.0, ash_g: 1.2,
    },
    minerals: {
      calcium_mg: 180, phosphorus_mg: 152, magnesium_mg: 11,
      potassium_mg: 104, sodium_mg: 68, sulfur_mg: 98,
      iron_mg: 0.12, zinc_mg: 0.72, copper_mg: 0.02,
      selenium_mcg: 8.2, iodine_mcg: 18, boron_mcg: 12,
    },
    vitamins: {
      vitaminA_retinolEquiv_mcg: 52, vitaminB1_thiamine_mg: 0.04,
      vitaminB2_riboflavin_mg: 0.24, vitaminB3_niacin_mg: 0.12,
      vitaminB5_pantothenicAcid_mg: 0.42, vitaminB6_pyridoxine_mg: 0.06,
      vitaminB9_folate_mcg: 18, vitaminB12_cobalamin_mcg: 0.64,
      vitaminD_mcg: 0.1, vitaminE_tocopherol_mg: 0.04,
    },
    aminoAcids: {
      essential: {
        histidine: 2.9, isoleucine: 5.8, leucine: 10.6,
        lysine: 8.4, methionine: 2.8, phenylalanine: 5.6,
        threonine: 4.8, tryptophan: 1.4, valine: 7.0,
      },
      semiEssential: {
        arginine: 3.6, cysteine: 0.9, glycine: 2.0, proline: 11.2, tyrosine: 5.8,
      },
      nonEssential: {
        alanine: 3.2, asparagine: 1.0, aspartate: 7.8,
        glutamate: 23.5, glutamine: 0.0, serine: 5.8,
      },
      totalAminoAcidsMgPer100g: 9940,
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 2.89, totalMonounsaturatedG: 1.30, totalPolyunsaturatedG: 0.13,
      cholesterol_mg: 14,
      butyric_C4_0: 0.14, lauric_C12_0: 0.16, myristic_C14_0: 0.48,
      palmitic_C16_0: 1.26, stearic_C18_0: 0.39, oleic_C18_1: 1.29,
      linoleic_C18_2n6: 0.12, alphaLinolenic_C18_3n3: 0.008,
    },
    glycemicIndex: 30,
    functionalProperties: [
      "Traditional Ethiopian fasting complement — high protein with low calorie density",
      "Dense calcium (180 mg) with excellent bioavailability",
      "Probiotic cultures from spontaneous fermentation (Lactobacillus, Streptococcus)",
      "Outstanding leucine density for muscle protein synthesis",
    ],
    bioavailabilityNotes: "Fermentation of ayib partially hydrolyzes casein proteins, improving digestibility. Traditional pairing with gomen (leafy greens) creates complete amino acid complementarity and enhances fat-soluble vitamin absorption from greens.",
    sourceReferences: ["FAO East Africa FCT", "Akabanda et al. (2014) J Food Microbiol"],
    dataConfidence: "medium",
  },

  // ── 7. Ethiopian Ergo (Fermented Milk/Yogurt) ────────────────
  {
    uid: "anm-ergo",
    nameEn: "Ergo (Ethiopian Fermented Milk)",
    nameAmharic: "እርጎ",
    scientificName: "Bos taurus (LAB-fermented)",
    category: "Dairy",
    partUsed: "Whole fermented milk",
    processingState: "spontaneously fermented",
    basis: "per 100 g ergo",
    proximate: {
      energyKcal: 66, moisture_g: 86.0, protein_g: 3.5,
      fat_g: 3.5, carbohydrate_g: 5.2, dietaryFiber_g: 0.0, ash_g: 0.8,
    },
    minerals: {
      calcium_mg: 122, phosphorus_mg: 94, magnesium_mg: 12,
      potassium_mg: 155, sodium_mg: 45, sulfur_mg: 35, chloride_mg: 102,
      iron_mg: 0.06, zinc_mg: 0.52, copper_mg: 0.01,
      selenium_mcg: 4.2, iodine_mcg: 52, boron_mcg: 18,
    },
    vitamins: {
      vitaminA_retinolEquiv_mcg: 48, vitaminB1_thiamine_mg: 0.04,
      vitaminB2_riboflavin_mg: 0.18, vitaminB3_niacin_mg: 0.10,
      vitaminB5_pantothenicAcid_mg: 0.36, vitaminB6_pyridoxine_mg: 0.05,
      vitaminB9_folate_mcg: 8, vitaminB12_cobalamin_mcg: 0.52,
      vitaminD_mcg: 1.2, vitaminE_tocopherol_mg: 0.07,
    },
    aminoAcids: {
      essential: {
        histidine: 2.6, isoleucine: 5.9, leucine: 9.8,
        lysine: 7.6, methionine: 2.4, phenylalanine: 4.7,
        threonine: 4.4, tryptophan: 1.3, valine: 6.5,
      },
      semiEssential: {
        arginine: 3.3, cysteine: 0.8, glycine: 1.8, proline: 9.8, tyrosine: 5.2,
      },
      nonEssential: {
        alanine: 3.4, asparagine: 0.9, aspartate: 7.2,
        glutamate: 20.2, glutamine: 0.0, serine: 5.2,
      },
      totalAminoAcidsMgPer100g: 2820,
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 2.18, totalMonounsaturatedG: 0.89, totalPolyunsaturatedG: 0.14,
      cholesterol_mg: 11,
      butyric_C4_0: 0.12, lauric_C12_0: 0.14, myristic_C14_0: 0.40,
      palmitic_C16_0: 1.01, stearic_C18_0: 0.32, oleic_C18_1: 0.88,
      linoleic_C18_2n6: 0.12, alphaLinolenic_C18_3n3: 0.012,
    },
    glycemicIndex: 28,
    functionalProperties: [
      "Rich probiotic cultures: Lactobacillus bulgaricus, Streptococcus thermophilus",
      "Fermentation eliminates lactose — suitable for lactose-intolerant individuals",
      "Short-chain butyric acid from fermentation for colonocyte health",
      "Enhanced calcium bioavailability (34%) due to lactic acid pH reduction",
      "Bioactive peptides (casein-derived): ACE-inhibitory, opioid, immunomodulatory",
    ],
    bioavailabilityNotes: "Spontaneous fermentation by diverse wild LAB strains produces a broader spectrum of bioactive peptides than commercial yogurt. Lactic acid lowers pH, improving mineral solubility. Ergo's calcium-to-phosphorus ratio (1.3:1) is optimal for bone mineral accretion.",
    sourceReferences: ["FAO East Africa FCT", "Sievert et al. (2014) EFSA J"],
    dataConfidence: "medium",
  },

  // ── 8. Nile Tilapia (Tilapia) ────────────────────────────────
  {
    uid: "anm-tilapia",
    nameEn: "Nile Tilapia",
    nameAmharic: "ዓሳ (ቲላፒያ)",
    scientificName: "Oreochromis niloticus",
    category: "Freshwater Fish",
    partUsed: "Fillet (raw)",
    processingState: "raw",
    basis: "per 100 g raw fillet",
    proximate: {
      energyKcal: 96, moisture_g: 77.7, protein_g: 20.1,
      fat_g: 1.7, carbohydrate_g: 0.0, dietaryFiber_g: 0.0, ash_g: 1.2,
    },
    minerals: {
      calcium_mg: 10, phosphorus_mg: 204, magnesium_mg: 27,
      potassium_mg: 380, sodium_mg: 56, sulfur_mg: 212,
      iron_mg: 0.56, zinc_mg: 0.41, copper_mg: 0.07,
      manganese_mg: 0.02, selenium_mcg: 41.8, boron_mcg: 6,
      iodine_mcg: 9,
    },
    vitamins: {
      vitaminB1_thiamine_mg: 0.06, vitaminB2_riboflavin_mg: 0.06,
      vitaminB3_niacin_mg: 4.7, vitaminB5_pantothenicAcid_mg: 0.50,
      vitaminB6_pyridoxine_mg: 0.16, vitaminB9_folate_mcg: 24,
      vitaminB12_cobalamin_mcg: 1.58, vitaminD_mcg: 1.9,
      vitaminE_tocopherol_mg: 0.5,
    },
    aminoAcids: {
      essential: {
        histidine: 5.8, isoleucine: 4.9, leucine: 8.3,
        lysine: 9.2, methionine: 3.0, phenylalanine: 3.9,
        threonine: 4.5, tryptophan: 1.1, valine: 5.1,
      },
      semiEssential: {
        arginine: 6.1, cysteine: 1.0, glycine: 5.4, proline: 3.5, tyrosine: 3.4,
      },
      nonEssential: {
        alanine: 6.1, asparagine: 1.8, aspartate: 9.8,
        glutamate: 15.4, glutamine: 7.2, serine: 3.8, hydroxyproline: 1.2,
      },
      totalAminoAcidsMgPer100g: 17960,
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 0.52, totalMonounsaturatedG: 0.44, totalPolyunsaturatedG: 0.54,
      cholesterol_mg: 50,
      palmitic_C16_0: 0.43, stearic_C18_0: 0.09, oleic_C18_1: 0.41,
      linoleic_C18_2n6: 0.29, alphaLinolenic_C18_3n3: 0.04,
      arachidonic_C20_4n6: 0.18, eicosaPentaenoic_C20_5n3: 0.07,
      docosaPentaenoic_C22_5n3: 0.08, docosaHexaenoic_C22_6n3: 0.20,
      omega3ToOmega6Ratio: "1:1.5",
      note: "Lake Tana (Ethiopia) wild tilapia has higher EPA/DHA than farmed. Wild tilapia from Rift Valley lakes is a key protein source for highland Ethiopia.",
    },
    glycemicIndex: 0,
    functionalProperties: [
      "Outstanding selenium (41.8 mcg) — among the highest of freshwater fish",
      "Excellent EPA + DHA (0.27 g/100g) for cardiovascular and neural health",
      "High vitamin B12 (1.58 mcg) essential for nerve myelination",
      "Lean complete protein at 96 kcal — ideal for weight-managing populations",
      "Vitamin D (1.9 mcg) — one of few dietary vitamin D sources",
    ],
    bioavailabilityNotes: "Wild-caught Lake Tana tilapia has superior omega-3 profile versus farmed due to diverse algal diet. Fish protein bioavailability is ~95%, slightly higher than meat due to minimal connective tissue. Traditional kirra (raw spiced beef) preparations increase protein digestibility.",
    sourceReferences: ["USDA FoodData Central #175168", "FAO East Africa FCT"],
    dataConfidence: "high",
  },

  // ── 9. Beef Liver ────────────────────────────────────────────
  {
    uid: "anm-beef-liver",
    nameEn: "Beef Liver (raw)",
    nameAmharic: "ከብት ጉበት",
    scientificName: "Bos taurus",
    category: "Organ Meat",
    partUsed: "Liver (raw)",
    processingState: "raw",
    basis: "per 100 g raw beef liver",
    proximate: {
      energyKcal: 135, moisture_g: 70.8, protein_g: 20.4,
      fat_g: 3.63, carbohydrate_g: 3.89, dietaryFiber_g: 0.0, ash_g: 1.38,
    },
    minerals: {
      calcium_mg: 5, phosphorus_mg: 387, magnesium_mg: 18,
      potassium_mg: 313, sodium_mg: 69, sulfur_mg: 244,
      iron_mg: 6.2, zinc_mg: 4.0, copper_mg: 9.76,
      manganese_mg: 0.32, selenium_mcg: 39.7, molybdenum_mcg: 109,
      iodine_mcg: 13, chromium_mcg: 14, boron_mcg: 4,
    },
    vitamins: {
      vitaminA_retinolEquiv_mcg: 4968, betaCarotene_mcg: 0,
      vitaminB1_thiamine_mg: 0.189, vitaminB2_riboflavin_mg: 3.42,
      vitaminB3_niacin_mg: 14.21, vitaminB5_pantothenicAcid_mg: 8.81,
      vitaminB6_pyridoxine_mg: 1.08, vitaminB9_folate_mcg: 290,
      vitaminB12_cobalamin_mcg: 83.1, vitaminD_mcg: 1.2,
      vitaminE_tocopherol_mg: 0.38, vitaminK_mcg: 3.1,
    },
    aminoAcids: {
      essential: {
        histidine: 5.9, isoleucine: 4.7, leucine: 8.2,
        lysine: 8.8, methionine: 2.4, phenylalanine: 4.6,
        threonine: 4.5, tryptophan: 1.1, valine: 5.2,
      },
      semiEssential: {
        arginine: 5.8, cysteine: 1.4, glycine: 4.2, proline: 4.5, tyrosine: 3.6,
      },
      nonEssential: {
        alanine: 5.5, asparagine: 2.0, aspartate: 9.2,
        glutamate: 13.8, glutamine: 7.0, serine: 4.0, hydroxyproline: 0.4,
      },
      totalAminoAcidsMgPer100g: 18320,
      aminoAcidScore: 100,
    },
    fattyAcids: {
      totalSaturatedG: 1.21, totalMonounsaturatedG: 0.60, totalPolyunsaturatedG: 0.52,
      cholesterol_mg: 275,
      palmitic_C16_0: 0.98, stearic_C18_0: 0.23, oleic_C18_1: 0.58,
      linoleic_C18_2n6: 0.30, arachidonic_C20_4n6: 0.19,
      docosaHexaenoic_C22_6n3: 0.08, eicosaPentaenoic_C20_5n3: 0.02,
      omega3ToOmega6Ratio: "1:3",
    },
    glycemicIndex: 0,
    functionalProperties: [
      "Richest vitamin B12 source (83 mcg — 3,500% DV) — critical for nervous system",
      "Extraordinary preformed vitamin A (4968 mcg RAE) — caution: toxic in excess",
      "Outstanding copper (9.76 mg) for ceruloplasmin and iron utilization",
      "Dense folate (290 mcg) for nucleotide synthesis and methylation",
      "Highest heme iron of any food (6.2 mg at 15–35% absorption rate)",
    ],
    bioavailabilityNotes: "Liver is nature's multivitamin. B12 at 83 mcg covers 12× daily requirement. Note: pregnant women should limit to 1–2 servings/week due to teratogenic risk from extremely high preformed vitamin A. Traditional Ethiopian awaze-marinated raw liver (kitfo) is valued for its bioavailability.",
    sourceReferences: ["USDA FoodData Central #168626", "FAO/WHO Recommended Nutrient Intakes"],
    dataConfidence: "high",
  },

  // ── 10. Injera with Beef Tibs (Composite) ────────────────────
  {
    uid: "anm-tibs-injera",
    nameEn: "Tibs with Injera (Composite Dish)",
    nameAmharic: "ትብስ ከእንጀራ ጋር",
    category: "Composite Dish",
    partUsed: "Prepared dish (estimated per 350g portion: 80g beef + 270g injera)",
    processingState: "cooked",
    basis: "per 100 g composite (traditional serving ratio)",
    proximate: {
      energyKcal: 182, moisture_g: 60.8, protein_g: 11.8,
      fat_g: 4.8, carbohydrate_g: 24.2, dietaryFiber_g: 2.8, ash_g: 1.2,
    },
    minerals: {
      calcium_mg: 72, phosphorus_mg: 165, magnesium_mg: 72,
      potassium_mg: 268, sodium_mg: 88, sulfur_mg: 148,
      iron_mg: 4.2, zinc_mg: 2.4, copper_mg: 0.22, manganese_mg: 3.8,
      selenium_mcg: 10.2, boron_mcg: 48,
    },
    vitamins: {
      vitaminB1_thiamine_mg: 0.24, vitaminB2_riboflavin_mg: 0.18,
      vitaminB3_niacin_mg: 4.1, vitaminB6_pyridoxine_mg: 0.32,
      vitaminB12_cobalamin_mcg: 1.2, vitaminC_ascorbicAcid_mg: 0.0,
      vitaminE_tocopherol_mg: 0.28,
    },
    aminoAcids: {
      essential: {
        histidine: 4.2, isoleucine: 4.4, leucine: 6.8,
        lysine: 6.2, methionine: 2.0, phenylalanine: 4.2,
        threonine: 3.8, tryptophan: 0.9, valine: 4.5,
      },
      semiEssential: {
        arginine: 5.2, cysteine: 1.0, glycine: 4.8, proline: 5.8, tyrosine: 3.0,
      },
      nonEssential: {
        alanine: 5.2, aspartate: 8.8, glutamate: 14.2,
        glutamine: 5.8, serine: 3.5, hydroxyproline: 1.2,
      },
      totalAminoAcidsMgPer100g: 9620,
      aminoAcidScore: 98,
    },
    fattyAcids: {
      totalSaturatedG: 1.82, totalMonounsaturatedG: 2.02, totalPolyunsaturatedG: 0.58,
      cholesterol_mg: 32,
      palmitic_C16_0: 1.42, stearic_C18_0: 0.40, oleic_C18_1: 1.98,
      linoleic_C18_2n6: 0.52, alphaLinolenic_C18_3n3: 0.06,
      arachidonic_C20_4n6: 0.04,
    },
    glycemicIndex: 38,
    functionalProperties: [
      "Exemplary complementary protein dish — teff lysine + beef methionine gaps filled mutually",
      "Heme + non-heme iron synergy: beef 'meat factor' enhances teff iron absorption 2–3×",
      "Traditional lemon or tomato accompaniment significantly increases total iron uptake",
      "Complete B-vitamin spectrum from meat + teff combination",
    ],
    bioavailabilityNotes: "The traditional Ethiopian combination of injera + meat creates powerful nutritional synergy: beef-derived 'meat factor' (MFP factor) elevates non-heme iron absorption from teff 2–3×. Fermented injera lactic acid improves overall mineral availability. Together the dish provides balanced EAA scoring.",
    sourceReferences: ["EFCT 2025 Composite Dish Analysis", "Abuye et al. (2003) Int J Food Sci Nutr"],
    dataConfidence: "medium",
  },
];

const animalCatalogSpecs = [
  ["Beef Chuck (lean, raw)", "Bos taurus", "Red Meat", "Chuck muscle, lean", "anm-beef-lean"],
  ["Beef Sirloin (lean, raw)", "Bos taurus", "Red Meat", "Sirloin muscle, lean", "anm-beef-lean"],
  ["Beef Rib (lean, raw)", "Bos taurus", "Red Meat", "Rib muscle, lean", "anm-beef-lean"],
  ["Ground Beef (lean, raw)", "Bos taurus", "Red Meat", "Ground skeletal muscle", "anm-beef-lean"],
  ["Beef Brisket (lean, raw)", "Bos taurus", "Red Meat", "Brisket muscle, lean", "anm-beef-lean"],
  ["Lamb Leg (lean, raw)", "Ovis aries", "Red Meat", "Leg muscle, lean", "anm-lamb"],
  ["Lamb Shoulder (lean, raw)", "Ovis aries", "Red Meat", "Shoulder muscle, lean", "anm-lamb"],
  ["Goat Meat (lean, raw)", "Capra hircus", "Red Meat", "Skeletal muscle, lean", "anm-lamb"],
  ["Goat Liver (raw)", "Capra hircus", "Organ Meat", "Liver", "anm-beef-liver"],
  ["Lamb Liver (raw)", "Ovis aries", "Organ Meat", "Liver", "anm-beef-liver"],
  ["Camel Meat (lean, raw)", "Camelus dromedarius", "Red Meat", "Skeletal muscle, lean", "anm-lamb"],
  ["Beef Kidney (raw)", "Bos taurus", "Organ Meat", "Kidney", "anm-beef-liver"],
  ["Beef Heart (raw)", "Bos taurus", "Organ Meat", "Heart", "anm-beef-liver"],
  ["Beef Bone Marrow (raw)", "Bos taurus", "Organ Meat", "Bone marrow", "anm-beef-lean"],
  ["Chicken Thigh (meat only, raw)", "Gallus gallus domesticus", "Poultry", "Thigh muscle", "anm-chicken-breast"],
  ["Chicken Drumstick (meat only, raw)", "Gallus gallus domesticus", "Poultry", "Drumstick muscle", "anm-chicken-breast"],
  ["Chicken Wing (meat and skin, raw)", "Gallus gallus domesticus", "Poultry", "Wing meat and skin", "anm-chicken-breast"],
  ["Chicken Breast (with skin, raw)", "Gallus gallus domesticus", "Poultry", "Breast muscle and skin", "anm-chicken-breast"],
  ["Turkey Breast (raw)", "Meleagris gallopavo", "Poultry", "Breast muscle", "anm-chicken-breast"],
  ["Duck Meat (raw)", "Anas platyrhynchos domesticus", "Poultry", "Skeletal muscle", "anm-chicken-breast"],
  ["Quail Meat (raw)", "Coturnix japonica", "Poultry", "Skeletal muscle", "anm-chicken-breast"],
  ["Chicken Liver (raw)", "Gallus gallus domesticus", "Organ Meat", "Liver", "anm-beef-liver"],
  ["Chicken Heart (raw)", "Gallus gallus domesticus", "Organ Meat", "Heart", "anm-beef-liver"],
  ["Egg White (raw)", "Gallus gallus domesticus", "Egg", "Albumen", "anm-egg-whole"],
  ["Egg Yolk (raw)", "Gallus gallus domesticus", "Egg", "Yolk", "anm-egg-whole"],
  ["Duck Egg (raw)", "Anas platyrhynchos domesticus", "Egg", "Whole egg", "anm-egg-whole"],
  ["Quail Egg (raw)", "Coturnix japonica", "Egg", "Whole egg", "anm-egg-whole"],
  ["Goat Milk (whole)", "Capra hircus", "Dairy", "Whole milk", "anm-milk-whole"],
  ["Sheep Milk (whole)", "Ovis aries", "Dairy", "Whole milk", "anm-milk-whole"],
  ["Camel Milk (whole)", "Camelus dromedarius", "Dairy", "Whole milk", "anm-milk-whole"],
  ["Buffalo Milk (whole)", "Bubalus bubalis", "Dairy", "Whole milk", "anm-milk-whole"],
  ["Plain Yogurt (whole milk)", "Bos taurus", "Fermented Dairy", "Cultured whole milk", "anm-ergo"],
  ["Strained Yogurt", "Bos taurus", "Fermented Dairy", "Strained cultured milk", "anm-ayib"],
  ["Cultured Buttermilk", "Bos taurus", "Fermented Dairy", "Cultured milk", "anm-ergo"],
  ["Whole-Milk Cream", "Bos taurus", "Dairy", "Separated cream", "anm-milk-whole"],
  ["Butter", "Bos taurus", "Dairy Fat", "Churned milk fat", "anm-milk-whole"],
  ["Fresh Feta-Style Cheese", "Bos taurus", "Cheese", "Fresh curd", "anm-ayib"],
  ["Nile Perch (raw)", "Lates niloticus", "Fish", "Fillet", "anm-tilapia"],
  ["African Catfish (raw)", "Clarias gariepinus", "Fish", "Fillet", "anm-tilapia"],
  ["Sardine (raw)", "Sardina pilchardus", "Fish", "Whole edible portion", "anm-tilapia"],
] as const;

const animalTemplates = new Map(CORE_ANIMAL_PRODUCT_PROFILES.map((profile) => [profile.uid, profile]));

export const ANIMAL_PRODUCT_PROFILES: DeepIngredientProfile[] = [
  ...CORE_ANIMAL_PRODUCT_PROFILES,
  ...animalCatalogSpecs.map(([nameEn, scientificName, category, partUsed, templateUid], index) => {
    const template = animalTemplates.get(templateUid)!;
    return {
      ...template,
      uid: `anm-catalog-${String(index + 1).padStart(2, "0")}`,
      nameEn,
      nameAmharic: undefined,
      scientificName,
      category,
      partUsed,
      processingState: "raw or as stated; category-level reference estimate",
      basis: "per 100 g edible portion; indicative category proxy, not product-specific analysis",
      aminoAcids: undefined,
      fattyAcids: undefined,
      phenolics: undefined,
      antinutrients: undefined,
      glycemicIndex: undefined,
      glycemicLoad: undefined,
      insulinIndex: undefined,
      functionalProperties: ["Indicative animal-food category composition; not a product-specific laboratory analysis."],
      bioavailabilityNotes: "Values are low-confidence category-level proxies from a related animal-food profile. Species, cut, feed, and processing can change composition substantially.",
      sourceReferences: ["Indicative category proxy based on " + template.nameEn + "; not a product-specific record or laboratory analysis."],
      dataConfidence: "low" as const,
    };
  }),
];
