import { EFCTFoodItem } from "./types";

export const EFCT_MASTER_FOODS: EFCTFoodItem[] = [
  // ==========================================
  // 1. GRAINS & CEREALS
  // ==========================================
  {
    id: "efct-0101",
    name: "Fermented Brown Teff Injera",
    nameAmharic: "የቡናማ ጤፍ እንጀራ (የቦካ)",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0101",
    traditionalPreparation: "4-day spontaneous lactic acid and yeast fermentation with Ersho starter. Microbial phytase breaks down phytate complexes by up to 75%, liberating bound divalent cations.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 42, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 220,
      tanninsMgPer100g: 85,
      oxalatesMgPer100g: 30,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "72–96h Ersho lactic backslopped fermentation and aeration (Aflegna).",
      fermentationReductionPct: 75,
      bioavailabilityUpliftDescription: "Non-heme iron dialyzability elevated by 1.45x–1.60x; zinc bioavailability elevated by 1.35x.",
    },
    macros: { caloriesKcal: 165, proteinG: 4.8, carbohydratesG: 34.2, fatsG: 0.8, dietaryFiberG: 4.2 },
    nutrients: [
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 11.5, bioavailabilityFactor: 1.45, note: "Phytate degraded by Ersho fermentation" },
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 130.0, bioavailabilityFactor: 1.2, note: "Volcanic soil uptake in grain bran" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 3.6, bioavailabilityFactor: 1.35, note: "Microbially liberated" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 140.0, bioavailabilityFactor: 1.15, note: "High cellular mineral density" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 4.2, bioavailabilityFactor: 1.0, note: "Prebiotic resistant starch" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 4.8, bioavailabilityFactor: 1.0, note: "Contains all 8 essential amino acids" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Iron-deficiency anemia", "Pre-diabetes & metabolic syndrome", "Celiac disease (naturally gluten-free)"],
      bioactiveCompounds: ["Prebiotic arabinoxylans", "Proanthocyanidins", "Resistant retrograded starch"],
      digestiveTolerance: "Excellent gastrointestinal soothing due to lactic fermentation acidity (pH 3.8–4.2).",
    },
  },
  {
    id: "efct-0102",
    name: "White Teff Injera (Nech Teff)",
    nameAmharic: "የነጭ ጤፍ እንጀራ",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0102",
    traditionalPreparation: "Fermented white teff flour (Eragrostis tef var. alba). Highly prized for soft spongy texture and subtle sourness.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 48, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 180,
      tanninsMgPer100g: 35,
      oxalatesMgPer100g: 22,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "72h Ersho fermentation with scum skimming.",
      fermentationReductionPct: 70,
      bioavailabilityUpliftDescription: "Smooth mineral release with lower native polyphenol content than dark grains.",
    },
    macros: { caloriesKcal: 170, proteinG: 4.5, carbohydratesG: 36.0, fatsG: 0.7, dietaryFiberG: 3.2 },
    nutrients: [
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 6.8, bioavailabilityFactor: 1.35, note: "Fermented injera non-heme iron" },
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 90.0, bioavailabilityFactor: 1.15, note: "Endosperm calcium" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.8, bioavailabilityFactor: 1.25, note: "Bioavailable zinc" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 4.5, bioavailabilityFactor: 1.0, note: "Gluten-free cereal protein" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 3.2, bioavailabilityFactor: 1.0, note: "Fermented grain fiber" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["General digestive wellness", "Gluten intolerance", "Cardiovascular support"],
      bioactiveCompounds: ["Soluble ferulic acid", "Resistant starch"],
      digestiveTolerance: "Very gentle on sensitive digestive tracts.",
    },
  },
  {
    id: "efct-0103",
    name: "Red Teff Injera (Qey Teff)",
    nameAmharic: "የቀይ ጤፍ እንጀራ",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0103",
    traditionalPreparation: "Fermented dark whole-grain red teff. Contains the highest iron and phenolic antioxidant concentration among all teff cultivars.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 39, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 290,
      tanninsMgPer100g: 140,
      oxalatesMgPer100g: 38,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Extended 96h Ersho fermentation with temperature controlled resting.",
      fermentationReductionPct: 78,
      bioavailabilityUpliftDescription: "Fermentation neutralizes tannins while preserving concentrated bran-bound iron.",
    },
    macros: { caloriesKcal: 160, proteinG: 5.1, carbohydratesG: 33.5, fatsG: 0.9, dietaryFiberG: 4.8 },
    nutrients: [
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 15.2, bioavailabilityFactor: 1.5, note: "Peak iron density among all cultivated grains" },
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 160.0, bioavailabilityFactor: 1.25, note: "High bran calcium" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 4.1, bioavailabilityFactor: 1.4, note: "Enzymatic activation" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 165.0, bioavailabilityFactor: 1.2, note: "Dense mineral matrix" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 4.8, bioavailabilityFactor: 1.0, note: "Whole grain roughage" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 5.1, bioavailabilityFactor: 1.0, note: "Rich in methionine" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Highland altitude hemoglobin synthesis", "Severe nutritional anemia", "Athletic stamina"],
      bioactiveCompounds: ["High polymeric proanthocyanidins", "Bran flavonoids"],
      digestiveTolerance: "Substantial satiety; requires thorough chewing and hydration.",
    },
  },
  {
    id: "efct-0104",
    name: "Roasted Barley Besso Drink",
    nameAmharic: "የገብስ በሶ",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0104",
    traditionalPreparation: "Highland barley (Hordeum vulgare) cleaned, slow-roasted over clay griddles, ground to fine flour, and shaken with water and a touch of honey or salt.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 35, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 120,
      tanninsMgPer100g: 45,
      oxalatesMgPer100g: 18,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Thermal roasting (Qolo technique) thermally denatures heat-labile antinutrients.",
      fermentationReductionPct: 60,
      bioavailabilityUpliftDescription: "Roasting gelatinizes beta-glucan starch and enhances soluble mineral release.",
    },
    macros: { caloriesKcal: 352, proteinG: 11.5, carbohydratesG: 68.0, fatsG: 2.1, dietaryFiberG: 14.5 },
    nutrients: [
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 14.5, bioavailabilityFactor: 1.0, note: "Rich in beta-glucan soluble fiber" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 120.0, bioavailabilityFactor: 1.1, note: "High cellular magnesium" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.5, bioavailabilityFactor: 1.2, note: "Roasted barley iron" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 450.0, bioavailabilityFactor: 1.0, note: "Electrolyte replenishment" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 11.5, bioavailabilityFactor: 1.0, note: "High satiety protein" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Cholesterol reduction (LDL lowering via beta-glucan)", "Gastric ulcer soothing", "Endurance hydration"],
      bioactiveCompounds: ["Barley beta-glucans", "Tocotrienols"],
      digestiveTolerance: "Forms a soothing demulcent gel in the stomach, shielding gastric mucosa from excess acid.",
    },
  },
  {
    id: "efct-0105",
    name: "Kinche (Cracked Wheat Porridge)",
    nameAmharic: "ቂንጬ",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0105",
    traditionalPreparation: "Coarsely cracked whole wheat boiled in water until tender, seasoned with spiced clarified butter (niter kibbeh) or oil during fasting.",
    fastingSuitability: "dual",
    glycemicIndex: { value: 52, rating: "medium" },
    antinutrients: {
      phyticAcidMgPer100g: 310,
      tanninsMgPer100g: 50,
      oxalatesMgPer100g: 25,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Prolonged boiling and pre-cracking.",
      fermentationReductionPct: 40,
      bioavailabilityUpliftDescription: "Cracking grain enhances moisture penetration and starch availability.",
    },
    macros: { caloriesKcal: 185, proteinG: 6.2, carbohydratesG: 35.0, fatsG: 2.8, dietaryFiberG: 5.5 },
    nutrients: [
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 5.5, bioavailabilityFactor: 1.0, note: "Insoluble wheat bran fiber" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 6.2, bioavailabilityFactor: 1.0, note: "Plant protein" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 78.0, bioavailabilityFactor: 1.0, note: "Whole grain magnesium" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 2.8, bioavailabilityFactor: 1.0, note: "Non-heme cereal iron" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Bowel regularity & peristalsis", "Sustained morning energy"],
      bioactiveCompounds: ["Wheat bran alkylresorcinols"],
      digestiveTolerance: "Wholesome breakfast staple; moderate portion if gluten sensitive.",
    },
  },
  {
    id: "efct-0106",
    name: "Genfo (Barley-Emmer Porridge with Berbere Well)",
    nameAmharic: "የገብስና አጃ ገንፎ",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0106",
    traditionalPreparation: "Thick roasted barley and emmer wheat porridge whipped vigorously in boiling water, served with a central well of melted niter kibbeh and berbere.",
    fastingSuitability: "dual",
    glycemicIndex: { value: 45, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 150,
      tanninsMgPer100g: 60,
      oxalatesMgPer100g: 20,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Intense dry roasting prior to milling and vigorous boiling.",
      fermentationReductionPct: 65,
      bioavailabilityUpliftDescription: "Thermal processing degrades phytates and gelatinizes complex starches.",
    },
    macros: { caloriesKcal: 240, proteinG: 7.5, carbohydratesG: 42.0, fatsG: 5.2, dietaryFiberG: 7.0 },
    nutrients: [
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 7.0, bioavailabilityFactor: 1.0, note: "Mixed soluble and insoluble fiber" },
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 65.0, bioavailabilityFactor: 1.1, note: "Cereal calcium" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.2, bioavailabilityFactor: 1.15, note: "Emmer & barley iron" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 95.0, bioavailabilityFactor: 1.1, note: "Muscular recovery mineral" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Postpartum maternal recovery", "Bone fracture convalescence", "Thermal body warming"],
      bioactiveCompounds: ["Emmer avenanthramides", "Barley beta-glucans"],
      digestiveTolerance: "Heavy grounding comfort food; provides long-lasting sustained caloric satiety.",
    },
  },
  {
    id: "efct-0107",
    name: "Sorghum Bread (Mashila Qitta)",
    nameAmharic: "የማሽላ ቂጣ",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0107",
    traditionalPreparation: "Drought-resilient lowland sorghum (Sorghum bicolor) flour lightly fermented and baked on earthenware mitad into dense flatbread.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 50, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 340,
      tanninsMgPer100g: 180,
      oxalatesMgPer100g: 28,
      trypsinInhibitorLevel: "moderate",
      traditionalDegradationMethod: "Overnight light fermentation and baking.",
      fermentationReductionPct: 55,
      bioavailabilityUpliftDescription: "Thermal contact neutralizes cyanogenic precursors in cultivated grain varieties.",
    },
    macros: { caloriesKcal: 190, proteinG: 5.5, carbohydratesG: 39.0, fatsG: 1.5, dietaryFiberG: 4.0 },
    nutrients: [
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 5.0, bioavailabilityFactor: 1.15, note: "Sorghum iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.2, bioavailabilityFactor: 1.1, note: "Cereal zinc" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 85.0, bioavailabilityFactor: 1.0, note: "Electrolyte mineral" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Lowland arid adaptation", "High antioxidant polyphenol protection"],
      bioactiveCompounds: ["3-Deoxyanthocyanidins", "Flavones"],
      digestiveTolerance: "Good tolerance; traditionally paired with buttermilk or vegetable stews.",
    },
  },
  {
    id: "efct-0108",
    name: "Finger Millet Bread (Dagussa Injera)",
    nameAmharic: "የዳጉሳ እንጀራ",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0108",
    traditionalPreparation: "Calcium-dense highland finger millet (Eleusine coracana) fermented with Ersho into distinctive dark reddish-brown injera.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 44, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 250,
      tanninsMgPer100g: 110,
      oxalatesMgPer100g: 32,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "72h Ersho fermentation.",
      fermentationReductionPct: 70,
      bioavailabilityUpliftDescription: "Microbial phytase markedly unlocks extraordinarily high native calcium.",
    },
    macros: { caloriesKcal: 168, proteinG: 4.2, carbohydratesG: 35.0, fatsG: 0.9, dietaryFiberG: 4.5 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 340.0, bioavailabilityFactor: 1.35, note: "Highest natural calcium density among all cereals (3x milk equivalent)" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 6.5, bioavailabilityFactor: 1.3, note: "Bioavailable millet iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.5, bioavailabilityFactor: 1.2, note: "Trace mineral" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 4.5, bioavailabilityFactor: 1.0, note: "Slow digesting fiber" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Pediatric bone mineralization", "Osteoporosis prevention in elderly", "Maternal lactation calcium support"],
      bioactiveCompounds: ["Eleusinian polyphenols", "Tryptophan"],
      digestiveTolerance: "Remarkable digestive calm; favored in Gojjam and Gondar for bone strength.",
    },
  },
  {
    id: "efct-0109",
    name: "Ethiopian Roasted Kolo Mix",
    nameAmharic: "የቆሎ ቅልቅል",
    category: "Grains & Cereals",
    sourceRef: "EFCT2025-0109",
    traditionalPreparation: "Hand-roasted blend of whole barley grains, chickpeas (shimbra), peanuts (lewz), and safflower seed kernels. Ubiquitous daily snack.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 38, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 190,
      tanninsMgPer100g: 75,
      oxalatesMgPer100g: 20,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "High heat sand/clay roasting completely destroys trypsin inhibitors.",
      fermentationReductionPct: 60,
      bioavailabilityUpliftDescription: "Dry thermal roasting neutralizes enzyme blockers and stabilizes healthy fats.",
    },
    macros: { caloriesKcal: 410, proteinG: 16.5, carbohydratesG: 62.0, fatsG: 11.0, dietaryFiberG: 12.0 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 16.5, bioavailabilityFactor: 1.0, note: "Complementary pulse and cereal amino acids" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 12.0, bioavailabilityFactor: 1.0, note: "Whole roasted grain roughage" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 6.2, bioavailabilityFactor: 1.1, note: "Roasted seed and pulse iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 3.4, bioavailabilityFactor: 1.1, note: "Plant zinc" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 155.0, bioavailabilityFactor: 1.0, note: "High energy mineral" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Sustained mental concentration during travel/study", "Appetite stabilization"],
      bioactiveCompounds: ["Legume lignans", "Roasted seed phytosterols"],
      digestiveTolerance: "Requires slow and thorough mastication; provides hours of stable blood sugar.",
    },
  },

  // ==========================================
  // 2. LEGUMES & PULSES
  // ==========================================
  {
    id: "efct-0201",
    name: "Shiro Wot (Spiced Chickpea & Field Pea Stew)",
    nameAmharic: "ሽሮ ወጥ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0201",
    traditionalPreparation: "Roasted, de-hulled, and seasoned chickpea (Cicer arietinum) and field pea flour slowly simmered with minced red onions, garlic, and berbere.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 34, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 210,
      tanninsMgPer100g: 65,
      oxalatesMgPer100g: 28,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Pre-soaking, thorough sun-drying, dry roasting, and prolonged simmering.",
      fermentationReductionPct: 70,
      bioavailabilityUpliftDescription: "Roasting pulses deactivates hemagglutinins and enhances protein digestibility.",
    },
    macros: { caloriesKcal: 180, proteinG: 12.4, carbohydratesG: 22.0, fatsG: 4.8, dietaryFiberG: 6.2 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 12.4, bioavailabilityFactor: 1.0, note: "Everyday staple protein source across Ethiopia" },
      { name: "Folate", symbol: "B9", unit: "mcg", amountPer100g: 180.0, bioavailabilityFactor: 1.0, note: "Critical maternal and cellular folate" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.8, bioavailabilityFactor: 1.1, note: "Pulse non-heme iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.2, bioavailabilityFactor: 1.1, note: "Bioavailable pulse zinc" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 480.0, bioavailabilityFactor: 1.0, note: "Cardiovascular electrolyte" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 6.2, bioavailabilityFactor: 1.0, note: "Soluble legume fiber" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Prenatal folate fortification", "Fasting season protein security", "Cholesterol control"],
      bioactiveCompounds: ["Chickpea isoflavones", "Allium sulfur compounds from garlic/onion"],
      digestiveTolerance: "Traditional roasting significantly reduces flatulence-inducing oligosaccharides (stachyose/raffinose).",
    },
  },
  {
    id: "efct-0202",
    name: "Misir Wot (Spicy Red Lentil Stew)",
    nameAmharic: "የምስር ወጥ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0202",
    traditionalPreparation: "Split de-hulled red lentils (Lens culinaris) simmered in rich berbere paste, red onions, ginger, and garlic into a thick stew.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 31, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 160,
      tanninsMgPer100g: 40,
      oxalatesMgPer100g: 18,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "De-hulling removes outer seed coats containing the majority of tannins.",
      fermentationReductionPct: 75,
      bioavailabilityUpliftDescription: "De-hulled split lentils exhibit rapid cooking and minimal mineral chelation.",
    },
    macros: { caloriesKcal: 195, proteinG: 14.5, carbohydratesG: 26.0, fatsG: 3.5, dietaryFiberG: 7.9 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 14.5, bioavailabilityFactor: 1.0, note: "High lysine pulse protein" },
      { name: "Folate", symbol: "B9", unit: "mcg", amountPer100g: 210.0, bioavailabilityFactor: 1.0, note: "Over 50% daily baseline requirement per portion" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 5.5, bioavailabilityFactor: 1.15, note: "De-hulled lentil iron" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 7.9, bioavailabilityFactor: 1.0, note: "Prebiotic colon substrate" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Prenatal neural tube protection", "High-altitude blood regeneration", "Type 2 diabetes glycemic control"],
      bioactiveCompounds: ["Lentil lectin fragments", "Capsaicin from berbere"],
      digestiveTolerance: "Rapidly digestible; lighter on the stomach than un-hulled whole pulses.",
    },
  },
  {
    id: "efct-0203",
    name: "Kik Alicha (Mild Yellow Split Pea Stew)",
    nameAmharic: "የክክ አልጫ ወጥ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0203",
    traditionalPreparation: "De-hulled yellow split peas slowly simmered with fresh turmeric (Ird), garlic, ginger, and red onions without chili peppers.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 33, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 170,
      tanninsMgPer100g: 30,
      oxalatesMgPer100g: 15,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Soaking and prolonged simmering with anti-inflammatory turmeric.",
      fermentationReductionPct: 72,
      bioavailabilityUpliftDescription: "Mild non-acidic preparation optimal for inflamed gastric linings.",
    },
    macros: { caloriesKcal: 175, proteinG: 13.0, carbohydratesG: 25.0, fatsG: 2.8, dietaryFiberG: 6.8 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 13.0, bioavailabilityFactor: 1.0, note: "Gentle pulse protein" },
      { name: "Folate", symbol: "B9", unit: "mcg", amountPer100g: 160.0, bioavailabilityFactor: 1.0, note: "Natural dietary folate" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.2, bioavailabilityFactor: 1.1, note: "Plant iron" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 420.0, bioavailabilityFactor: 1.0, note: "Cardiovascular balance" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Gastritis and heartburn (chegura)", "Pediatric weaning nutrition", "Convalescent recovery"],
      bioactiveCompounds: ["Curcuminoids from turmeric (Ird)", "Gingerols from ginger"],
      digestiveTolerance: "Exceptionally well tolerated by individuals sensitive to spicy berbere dishes.",
    },
  },
  {
    id: "efct-0204",
    name: "Bakela Wot (Highland Fava Bean Stew)",
    nameAmharic: "የባቄላ ወጥ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0204",
    traditionalPreparation: "Highland fava beans (Vicia faba) soaked, skinned, and cooked into thick hearty stew with onions, ginger, and cardamom.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 36, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 280,
      tanninsMgPer100g: 95,
      oxalatesMgPer100g: 35,
      trypsinInhibitorLevel: "moderate",
      traditionalDegradationMethod: "Overnight soaking and complete manual removal of tough seed coats.",
      fermentationReductionPct: 68,
      bioavailabilityUpliftDescription: "Peeling fava coats eliminates 80% of vicine and convicine glycosides.",
    },
    macros: { caloriesKcal: 185, proteinG: 15.0, carbohydratesG: 24.0, fatsG: 2.2, dietaryFiberG: 8.5 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 15.0, bioavailabilityFactor: 1.0, note: "High biological value plant protein" },
      { name: "Folate", symbol: "B9", unit: "mcg", amountPer100g: 225.0, bioavailabilityFactor: 1.0, note: "Abundant natural folate" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 5.8, bioavailabilityFactor: 1.1, note: "Fava bean iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.6, bioavailabilityFactor: 1.1, note: "Plant zinc" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Dopaminergic neuro-support (natural L-DOPA precursor)", "Highland muscular endurance"],
      bioactiveCompounds: ["Levodopa (L-DOPA)", "Flavonol glycosides"],
      digestiveTolerance: "Contraindicated in individuals with G6PD deficiency (favism risk).",
    },
  },
  {
    id: "efct-0205",
    name: "Shimbra Asa (Spiced Chickpea Dumplings in Wot)",
    nameAmharic: "የሽንብራ ዓሣ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0205",
    traditionalPreparation: "Seasoned chickpea dough shaped into stylized fish fillets, baked or pan-seared, then simmered in spicy berbere sauce. Celebrated fasting delicacy.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 37, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 195,
      tanninsMgPer100g: 55,
      oxalatesMgPer100g: 22,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Double cooking: baking/frying followed by stew simmering.",
      fermentationReductionPct: 75,
      bioavailabilityUpliftDescription: "Thermal cycle maximizes protein digestibility and reduces flatulence.",
    },
    macros: { caloriesKcal: 215, proteinG: 13.5, carbohydratesG: 28.0, fatsG: 5.8, dietaryFiberG: 7.2 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 13.5, bioavailabilityFactor: 1.0, note: "Chickpea protein" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.5, bioavailabilityFactor: 1.1, note: "Plant iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.4, bioavailabilityFactor: 1.1, note: "Pulse zinc" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Culinary fasting satisfaction", "Sustained athletic protein"],
      bioactiveCompounds: ["Chickpea saponins", "Capsaicin"],
      digestiveTolerance: "Very satisfying chewy texture without heavy animal fat.",
    },
  },
  {
    id: "efct-0206",
    name: "Azifa (Chilled Green Lentil Salad with Mustard)",
    nameAmharic: "አዚፋ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0206",
    traditionalPreparation: "Whole brown/green lentils boiled tender, lightly mashed with Ethiopian brown mustard (Senafich), fresh lime juice, diced red onions, and green chilies.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 29, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 140,
      tanninsMgPer100g: 70,
      oxalatesMgPer100g: 20,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Boiling followed by acid maceration with fresh lime juice (ascorbic acid).",
      fermentationReductionPct: 70,
      bioavailabilityUpliftDescription: "Ascorbic acid from fresh lime juice elevates non-heme iron absorption by 2.0x–3.0x!",
    },
    macros: { caloriesKcal: 155, proteinG: 11.2, carbohydratesG: 22.5, fatsG: 1.8, dietaryFiberG: 8.2 },
    nutrients: [
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 6.2, bioavailabilityFactor: 2.2, note: "Citric & ascorbic acid from lime juice doubles iron absorption" },
      { name: "Vitamin C", symbol: "VitC", unit: "mg", amountPer100g: 24.0, bioavailabilityFactor: 1.0, note: "Fresh lime and raw pepper vitamin C" },
      { name: "Folate", symbol: "B9", unit: "mcg", amountPer100g: 175.0, bioavailabilityFactor: 1.0, note: "Whole lentil folate" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 8.2, bioavailabilityFactor: 1.0, note: "High prebiotic roughage" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Rapid nutritional iron replenishment", "Metabolic digestive stimulation via mustard isothiocyanates", "Liver bile flow"],
      bioactiveCompounds: ["Sinigrin from brown mustard (Senafich)", "L-ascorbic acid"],
      digestiveTolerance: "Crisp and invigorating; stimulates digestive secretions.",
    },
  },
  {
    id: "efct-0207",
    name: "Nifro (Boiled Mixed Grains & Pulses)",
    nameAmharic: "ንፍሮ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0207",
    traditionalPreparation: "Whole chickpeas, wheat kernels, and fava beans soaked overnight, boiled together with a pinch of salt until plump and tender. Traditional harvest and commemoration dish.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 40, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 220,
      tanninsMgPer100g: 60,
      oxalatesMgPer100g: 25,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Extended 18-hour cold soaking followed by 2-hour slow boiling.",
      fermentationReductionPct: 65,
      bioavailabilityUpliftDescription: "Soaking initiates enzymatic grain germination, reducing phytates.",
    },
    macros: { caloriesKcal: 230, proteinG: 12.0, carbohydratesG: 38.0, fatsG: 3.2, dietaryFiberG: 10.5 },
    nutrients: [
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 10.5, bioavailabilityFactor: 1.0, note: "Superb whole grain and pulse fiber" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 12.0, bioavailabilityFactor: 1.0, note: "Complete complementary amino acids" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.8, bioavailabilityFactor: 1.1, note: "Whole seed iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.8, bioavailabilityFactor: 1.1, note: "Germinated zinc" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Chronic constipation & sluggish colon", "Long-lasting physical labor fuel"],
      bioactiveCompounds: ["Resistant starch type 3", "Soluble arabinogalactans"],
      digestiveTolerance: "High roughage; requires adequate water intake.",
    },
  },
  {
    id: "efct-0208",
    name: "Fasolia (Green Beans, Carrots & Onions)",
    nameAmharic: "የፋሶሊያ ወጥ",
    category: "Vegetables & Greens",
    sourceRef: "EFCT2025-0208",
    traditionalPreparation: "Fresh tender green beans (Phaseolus vulgaris) sliced and sautéed with sweet carrots, red onions, garlic, and turmeric.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 32, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 45,
      tanninsMgPer100g: 20,
      oxalatesMgPer100g: 12,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Fresh vegetable sautéing.",
      fermentationReductionPct: 40,
      bioavailabilityUpliftDescription: "Low antinutrients natively.",
    },
    macros: { caloriesKcal: 85, proteinG: 2.8, carbohydratesG: 12.0, fatsG: 3.2, dietaryFiberG: 3.8 },
    nutrients: [
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 420.0, bioavailabilityFactor: 1.2, note: "Beta-carotene from carrots absorbed with cooking oil" },
      { name: "Vitamin C", symbol: "VitC", unit: "mg", amountPer100g: 18.0, bioavailabilityFactor: 0.9, note: "Vegetable vitamin C" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 3.8, bioavailabilityFactor: 1.0, note: "Pectin and cellulose" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 290.0, bioavailabilityFactor: 1.0, note: "Low-sodium electrolyte" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Eye health & night vision", "Mild digestive detox", "Caloric balance during fasting"],
      bioactiveCompounds: ["Carotenoids (alpha and beta-carotene)", "Lutein"],
      digestiveTolerance: "Light, sweet, and soothing for all ages.",
    },
  },
  {
    id: "efct-0209",
    name: "Siljo (Fermented Fava Bean & Safflower Paste)",
    nameAmharic: "ስልጆ",
    category: "Legumes & Pulses",
    sourceRef: "EFCT2025-0209",
    traditionalPreparation: "Milled fava bean flour cooked with water extracted from safflower (suf) seeds, fermented for 3–5 days with mustard seed, garlic, and rue. Highly valued during Lent (Abiy Tsom).",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 30, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 90,
      tanninsMgPer100g: 40,
      oxalatesMgPer100g: 15,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Multistage fermentation with lactic acid bacteria and mustard essential oils.",
      fermentationReductionPct: 85,
      bioavailabilityUpliftDescription: "Probiotic fermentation eliminates antinutrients and produces functional organic acids.",
    },
    macros: { caloriesKcal: 160, proteinG: 11.0, carbohydratesG: 18.0, fatsG: 5.5, dietaryFiberG: 6.0 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 11.0, bioavailabilityFactor: 1.0, note: "Fermented fava & seed protein" },
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 110.0, bioavailabilityFactor: 1.25, note: "Safflower mineral calcium" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.8, bioavailabilityFactor: 1.35, note: "Fermentation liberated iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 2.5, bioavailabilityFactor: 1.3, note: "Probiotic accessible zinc" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Gut microbiome diversity during strict fasting", "Immune modulation via allyl isothiocyanate"],
      bioactiveCompounds: ["Probiotic Lactobacillus brevis & L. plantarum", "Safflower carthamin"],
      digestiveTolerance: "Pungent and tangy; acts as a powerful digestive stimulant.",
    },
  },

  // ==========================================
  // 3. ROOTS & TUBERS
  // ==========================================
  {
    id: "efct-0301",
    name: "Kocho (Underground Pit-Fermented Enset Bread)",
    nameAmharic: "ቆጮ",
    category: "Roots & Tubers",
    sourceRef: "EFCT2025-0301",
    traditionalPreparation: "Scraped pseudo-stem and pulverized corm of Ensete ventricosum fermented in underground earthen pits for 3 to 12 months, kneaded and baked over hot clay griddles.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 46, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 40,
      tanninsMgPer100g: 30,
      oxalatesMgPer100g: 18,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Multi-month anaerobic earthen pit fermentation destroys volatile bitter glycosides.",
      fermentationReductionPct: 90,
      bioavailabilityUpliftDescription: "Pit fermentation produces abundant butyrate, acetate, and propionate short-chain fatty acids.",
    },
    macros: { caloriesKcal: 195, proteinG: 1.8, carbohydratesG: 45.0, fatsG: 0.5, dietaryFiberG: 5.8 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 160.0, bioavailabilityFactor: 1.2, note: "Mineral-rich soil-derived calcium" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 5.8, bioavailabilityFactor: 1.0, note: "Prebiotic resistant enset fiber" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 380.0, bioavailabilityFactor: 1.0, note: "Cellular potassium" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 1.2, bioavailabilityFactor: 1.1, note: "Trace mineral" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Irritable bowel syndrome (IBS) and mucosal inflammation", "Caloric resilience against drought", "Gastric lining repair"],
      bioactiveCompounds: ["Enset beta-sitosterol", "Butyric acid fermentation products"],
      digestiveTolerance: "Soothing and demulcent; traditionally given to comfort abdominal irritation.",
    },
  },
  {
    id: "efct-0302",
    name: "Bulla Porridge",
    nameAmharic: "የቡላ ገንፎ",
    category: "Roots & Tubers",
    sourceRef: "EFCT2025-0302",
    traditionalPreparation: "Refined liquid squeezed from fresh enset pulp, decanted, sun-dried into pure white starch, and cooked into silky porridge with milk or niter kibbeh.",
    fastingSuitability: "dual",
    glycemicIndex: { value: 54, rating: "medium" },
    antinutrients: {
      phyticAcidMgPer100g: 20,
      tanninsMgPer100g: 15,
      oxalatesMgPer100g: 10,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Decanting and water washing washes away soluble antinutrients.",
      fermentationReductionPct: 92,
      bioavailabilityUpliftDescription: "Near-pure digestible starch with exceptionally low antinutritional interference.",
    },
    macros: { caloriesKcal: 210, proteinG: 1.2, carbohydratesG: 49.0, fatsG: 0.3, dietaryFiberG: 3.2 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 185.0, bioavailabilityFactor: 1.15, note: "Traditional postpartum recovery food" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 3.2, bioavailabilityFactor: 1.0, note: "Gentle enset starch" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 2.1, bioavailabilityFactor: 1.0, note: "Trace iron" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Postpartum maternal recovery", "Acute gastritis relief", "Pediatric convalescence"],
      bioactiveCompounds: ["Easily assimilable amylopectin"],
      digestiveTolerance: "The gentlest traditional food in Ethiopian medicine; zero mechanical or chemical irritation.",
    },
  },
  {
    id: "efct-0303",
    name: "Taro / Godere (Boiled Highland Colocasia)",
    nameAmharic: "ጎደሬ",
    category: "Roots & Tubers",
    sourceRef: "EFCT2025-0303",
    traditionalPreparation: "Highland taro corms (Colocasia esculenta) thoroughly boiled with salt and mild spices until needle-like calcium oxalate raphides are completely dissolved.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 48, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 65,
      tanninsMgPer100g: 25,
      oxalatesMgPer100g: 140, // High when raw!
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Prolonged boiling in abundant water with water discarded neutralizes soluble oxalates.",
      fermentationReductionPct: 85,
      bioavailabilityUpliftDescription: "Boiling destroys calcium oxalate needle crystals, making root safe and nourishing.",
    },
    macros: { caloriesKcal: 142, proteinG: 2.1, carbohydratesG: 34.0, fatsG: 0.2, dietaryFiberG: 5.1 },
    nutrients: [
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 590.0, bioavailabilityFactor: 1.0, note: "Exceptionally high potassium" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 33.0, bioavailabilityFactor: 1.0, note: "Tuber magnesium" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 5.1, bioavailabilityFactor: 1.0, note: "Resistant tuber starch" },
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 43.0, bioavailabilityFactor: 1.0, note: "Bioavailable post-boiling" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Hypertension management (high potassium-to-sodium ratio)", "Colon health"],
      bioactiveCompounds: ["Water-soluble mucilage polysaccharides"],
      digestiveTolerance: "Must be thoroughly boiled; never consume raw.",
    },
  },
  {
    id: "efct-0304",
    name: "Sweet Potato (Sukar Dinich)",
    nameAmharic: "የስኳር ድንች",
    category: "Roots & Tubers",
    sourceRef: "EFCT2025-0304",
    traditionalPreparation: "Orange and yellow fleshed sweet potato tubers (Ipomoea batatas) boiled or roasted over embers.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 50, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 35,
      tanninsMgPer100g: 15,
      oxalatesMgPer100g: 28,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Boiling and roasting.",
      fermentationReductionPct: 50,
      bioavailabilityUpliftDescription: "Thermal cooking unlocks beta-carotene into easily micellized form.",
    },
    macros: { caloriesKcal: 110, proteinG: 1.8, carbohydratesG: 25.5, fatsG: 0.2, dietaryFiberG: 3.5 },
    nutrients: [
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 780.0, bioavailabilityFactor: 1.25, note: "Rich pro-vitamin A beta-carotene" },
      { name: "Vitamin C", symbol: "VitC", unit: "mg", amountPer100g: 19.5, bioavailabilityFactor: 0.85, note: "Tuber vitamin C" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 337.0, bioavailabilityFactor: 1.0, note: "Cardiac electrolyte" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 3.5, bioavailabilityFactor: 1.0, note: "Soluble dietary fiber" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Pediatric vitamin A deficiency prevention", "Immune mucosal barrier integrity"],
      bioactiveCompounds: ["Trans-beta-carotene", "Chlorogenic acids"],
      digestiveTolerance: "Easily digestible and naturally sweet.",
    },
  },
  {
    id: "efct-0305",
    name: "Oromo Dinicha (Plectranthus edulis)",
    nameAmharic: "የኦሮሞ ድንች",
    category: "Roots & Tubers",
    sourceRef: "EFCT2025-0305",
    traditionalPreparation: "Indigenous Ethiopian tuber cultivated in the highlands of Oromia and Southern Ethiopia, boiled with salt.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 45, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 45,
      tanninsMgPer100g: 30,
      oxalatesMgPer100g: 22,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Boiling in salted water.",
      fermentationReductionPct: 60,
      bioavailabilityUpliftDescription: "Gentle boiling leaches trace bitter glycosides.",
    },
    macros: { caloriesKcal: 125, proteinG: 2.4, carbohydratesG: 28.0, fatsG: 0.3, dietaryFiberG: 4.2 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 72.0, bioavailabilityFactor: 1.1, note: "High tuber calcium" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 3.8, bioavailabilityFactor: 1.1, note: "Indigenous tuber iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 1.8, bioavailabilityFactor: 1.1, note: "Trace mineral" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Indigenous agrobiodiversity conservation", "Slow-release carbohydrate energy"],
      bioactiveCompounds: ["Terpenoid glycosides", "Tuber inulin"],
      digestiveTolerance: "Mild pleasant earthy flavor; highly filling.",
    },
  },

  // ==========================================
  // 4. VEGETABLES & GREENS
  // ==========================================
  {
    id: "efct-0401",
    name: "Habesha Gomen (Ethiopian Highland Collard)",
    nameAmharic: "ጎመን",
    category: "Vegetables & Greens",
    sourceRef: "EFCT2025-0401",
    traditionalPreparation: "Highland Ethiopian kale (Brassica carinata) braised with garlic, ginger, sliced green chili, and vegetable oil or niter kibbeh.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 20, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 15,
      tanninsMgPer100g: 25,
      oxalatesMgPer100g: 45, // Much lower than spinach!
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Light braising and steam cooking.",
      fermentationReductionPct: 50,
      bioavailabilityUpliftDescription: "Exceptionally low oxalic acid allows high calcium absorption (>40% absorption vs <5% in common spinach).",
    },
    macros: { caloriesKcal: 65, proteinG: 3.2, carbohydratesG: 8.5, fatsG: 2.1, dietaryFiberG: 4.0 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 210.0, bioavailabilityFactor: 1.35, note: "Exceptionally bioavailable calcium due to low oxalate profile" },
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 380.0, bioavailabilityFactor: 1.2, note: "Beta-carotene provitamin A" },
      { name: "Vitamin C", symbol: "VitC", unit: "mg", amountPer100g: 45.0, bioavailabilityFactor: 0.85, note: "Partially heat-sensitive" },
      { name: "Folate", symbol: "B9", unit: "mcg", amountPer100g: 120.0, bioavailabilityFactor: 1.0, note: "Leafy green folate" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 4.0, bioavailabilityFactor: 1.0, note: "Digestive roughage" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Bone density fortification during dairy-free fasting", "Retinal macular health via lutein", "Cellular detoxification"],
      bioactiveCompounds: ["Glucosinolates (allyl isothiocyanate precursors)", "Lutein & zeaxanthin"],
      digestiveTolerance: "Cooking deactivates mild goitrogens; very gentle on digestion.",
    },
  },
  {
    id: "efct-0402",
    name: "Moringa (Shiferaw) Leaf Powder",
    nameAmharic: "የሽፈራው ቅጠል ዱቄት",
    category: "Vegetables & Greens",
    sourceRef: "EFCT2025-0402",
    traditionalPreparation: "Shade-dried leaves of indigenous Moringa stenopetala from Konso and Arba Minch, pulverized into fine vibrant green powder.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 18, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 80,
      tanninsMgPer100g: 45,
      oxalatesMgPer100g: 50,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Shade drying preserves micronutrients while reducing moisture-dependent antinutrients.",
      fermentationReductionPct: 60,
      bioavailabilityUpliftDescription: "Super-dense micronutrient matrix delivering concentrated minerals.",
    },
    macros: { caloriesKcal: 205, proteinG: 27.0, carbohydratesG: 38.0, fatsG: 2.5, dietaryFiberG: 19.0 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 1850.0, bioavailabilityFactor: 1.15, note: "Unmatched plant calcium density" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 28.0, bioavailabilityFactor: 1.2, note: "Concentrated plant iron" },
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 1600.0, bioavailabilityFactor: 1.0, note: "Over 170% daily baseline provitamin A" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 27.0, bioavailabilityFactor: 1.0, note: "High protein leaf flour" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 360.0, bioavailabilityFactor: 1.1, note: "Cellular magnesium" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Severe multi-micronutrient deficiency", "Lactation enhancement", "Blood glucose modulation"],
      bioactiveCompounds: ["Moringine isothiocyanates", "Quercetin & chlorogenic acid"],
      digestiveTolerance: "Introduce gradually (1/2 tsp daily) to prevent mild laxative effect.",
    },
  },
  {
    id: "efct-0403",
    name: "Duba Wot (Pumpkin / Squash Stew)",
    nameAmharic: "የዱባ ወጥ",
    category: "Vegetables & Greens",
    sourceRef: "EFCT2025-0403",
    traditionalPreparation: "Ripe yellow pumpkin (Cucurbita pepo) cubed and simmered in mild berbere or turmeric sauce with garlic and red onions.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 45, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 20,
      tanninsMgPer100g: 10,
      oxalatesMgPer100g: 15,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Stew simmering.",
      fermentationReductionPct: 50,
      bioavailabilityUpliftDescription: "Low antinutrients; high carotenoid micellization with cooking oils.",
    },
    macros: { caloriesKcal: 90, proteinG: 2.1, carbohydratesG: 18.0, fatsG: 1.8, dietaryFiberG: 3.2 },
    nutrients: [
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 650.0, bioavailabilityFactor: 1.2, note: "High provitamin A carotenoids" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 340.0, bioavailabilityFactor: 1.0, note: "Hypotensive electrolyte" },
      { name: "Vitamin C", symbol: "VitC", unit: "mg", amountPer100g: 15.0, bioavailabilityFactor: 0.8, note: "Vegetable vitamin C" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Visual pigment regeneration", "Prostate and urinary health", "Gentle fasting nourishment"],
      bioactiveCompounds: ["Beta-cryptoxanthin", "Cucurbitacins"],
      digestiveTolerance: "Very gentle and easy on the intestines.",
    },
  },
  {
    id: "efct-0404",
    name: "Timatim Fitfit (Fresh Tomato & Injera Salad)",
    nameAmharic: "የቲማቲም ፍትፍት",
    category: "Vegetables & Greens",
    sourceRef: "EFCT2025-0404",
    traditionalPreparation: "Fresh vine-ripened tomatoes diced with onions, minced green chili (kariya), lemon juice, and torn pieces of cold fermented teff injera.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 38, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 70,
      tanninsMgPer100g: 25,
      oxalatesMgPer100g: 15,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Fresh raw preparation with cold fermented teff.",
      fermentationReductionPct: 75,
      bioavailabilityUpliftDescription: "Vitamin C from fresh tomatoes and lemon dramatically multiplies teff iron uptake.",
    },
    macros: { caloriesKcal: 140, proteinG: 3.8, carbohydratesG: 28.0, fatsG: 1.5, dietaryFiberG: 3.5 },
    nutrients: [
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 7.2, bioavailabilityFactor: 1.85, note: "Fresh tomato vitamin C elevates teff iron absorption by 85%" },
      { name: "Vitamin C", symbol: "VitC", unit: "mg", amountPer100g: 32.0, bioavailabilityFactor: 1.0, note: "Raw tomato and lemon ascorbic acid" },
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 210.0, bioavailabilityFactor: 1.0, note: "Lycopene and beta-carotene" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Optimal meal pairing for treating iron deficiency", "Vascular endothelial protection via lycopene"],
      bioactiveCompounds: ["Lycopene", "Flavonoid rutin"],
      digestiveTolerance: "Refreshing and hydrating; excellent cooling dish in warm weather.",
    },
  },

  // ==========================================
  // 5. SEEDS, NUTS & OILS
  // ==========================================
  {
    id: "efct-0501",
    name: "Roasted Telba (Flaxseed) Drink",
    nameAmharic: "የተልባ ውሀ / ጭማቂ",
    category: "Seeds, Nuts & Oils",
    sourceRef: "EFCT2025-0501",
    traditionalPreparation: "Flaxseed (Linum usitatissimum) lightly toasted to pop, finely ground, and whisked into warm water with honey. Creates a thick soothing mucilage.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 25, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 180,
      tanninsMgPer100g: 50,
      oxalatesMgPer100g: 20,
      trypsinInhibitorLevel: "low",
      traditionalDegradationMethod: "Light dry roasting thermally inactivates trace cyanogenic glycosides (linamarin).",
      fermentationReductionPct: 65,
      bioavailabilityUpliftDescription: "Roasting frees alpha-linolenic omega-3 fatty acids from cellular matrix.",
    },
    macros: { caloriesKcal: 260, proteinG: 9.5, carbohydratesG: 15.0, fatsG: 18.5, dietaryFiberG: 13.5 },
    nutrients: [
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 13.5, bioavailabilityFactor: 1.0, note: "Superb water-soluble arabinoxylan mucilage" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 195.0, bioavailabilityFactor: 1.0, note: "High anti-stress magnesium" },
      { name: "Potassium", symbol: "K", unit: "mg", amountPer100g: 410.0, bioavailabilityFactor: 1.0, note: "Cardiovascular electrolyte" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 2.8, bioavailabilityFactor: 1.0, note: "Plant iron" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Omega-3 fatty acid intake during fasting", "Esophageal and gastric ulcer mucosal coating", "Constipation relief"],
      bioactiveCompounds: ["Alpha-linolenic acid (ALA Omega-3)", "Secoisolariciresinol diglucoside (SDG lignan)"],
      digestiveTolerance: "Supreme mucosal demulcent; coats inflamed stomach and promotes gentle bowel movement.",
    },
  },
  {
    id: "efct-0502",
    name: "Suf Fitfit (Wild Safflower Seed Milk with Injera)",
    nameAmharic: "የሱፍ ፍትፍት",
    category: "Seeds, Nuts & Oils",
    sourceRef: "EFCT2025-0502",
    traditionalPreparation: "Safflower seeds (Carthamus tinctorius) crushed in water, filtered through fine mesh to extract rich white seed milk, seasoned with chili, and mixed with torn injera.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 34, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 110,
      tanninsMgPer100g: 35,
      oxalatesMgPer100g: 15,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Crushing and cloth filtration discards hull-bound antinutrients.",
      fermentationReductionPct: 75,
      bioavailabilityUpliftDescription: "Emulsified seed milk delivers bioavailable linoleic and oleic fatty acids.",
    },
    macros: { caloriesKcal: 230, proteinG: 7.2, carbohydratesG: 32.0, fatsG: 9.0, dietaryFiberG: 4.8 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 115.0, bioavailabilityFactor: 1.2, note: "Seed milk bioavailable calcium" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 5.2, bioavailabilityFactor: 1.25, note: "Teff & safflower iron" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 125.0, bioavailabilityFactor: 1.1, note: "Cellular magnesium" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Essential linoleic fatty acid source during vegan fasting", "Cardiovascular lipid modulation"],
      bioactiveCompounds: ["Carthamin", "Polyunsaturated fatty acids"],
      digestiveTolerance: "Light, silky, and cooling to an irritated stomach.",
    },
  },
  {
    id: "efct-0503",
    name: "Nug (Niger Seed) Paste",
    nameAmharic: "የኑግ መረቅ",
    category: "Seeds, Nuts & Oils",
    sourceRef: "EFCT2025-0503",
    traditionalPreparation: "Indigenous Ethiopian Niger seed (Guizotia abyssinica) roasted, pounded into oily aromatic paste, used as cooking fat and seasoning during fasting seasons.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 22, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 140,
      tanninsMgPer100g: 40,
      oxalatesMgPer100g: 18,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Thermal roasting and paste pressing.",
      fermentationReductionPct: 60,
      bioavailabilityUpliftDescription: "Essential oil release facilitates fat-soluble vitamin absorption.",
    },
    macros: { caloriesKcal: 515, proteinG: 19.5, carbohydratesG: 16.0, fatsG: 43.0, dietaryFiberG: 8.5 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 19.5, bioavailabilityFactor: 1.0, note: "High protein seed paste" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 7.8, bioavailabilityFactor: 1.1, note: "Seed iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 4.2, bioavailabilityFactor: 1.1, note: "High seed zinc" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 280.0, bioavailabilityFactor: 1.0, note: "Dense mineral content" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["High calorie fasting energy", "Cellular membrane fluidity via linoleic acid"],
      bioactiveCompounds: ["Linoleic acid (Omega-6)", "Sesamol-related lignans"],
      digestiveTolerance: "Nutritious and dense; consume in culinary moderation.",
    },
  },

  // ==========================================
  // 6. MEAT, POULTRY & DAIRY
  // ==========================================
  {
    id: "efct-0601",
    name: "Doro Wot with Hardboiled Egg",
    nameAmharic: "ዶሮ ወጥ ከእንቁላል ጋር",
    category: "Meat, Poultry & Dairy",
    sourceRef: "EFCT2025-0601",
    traditionalPreparation: "Celebrated Ethiopian festive chicken stew simmered for hours in slow-caramelized red onions, niter kibbeh, ginger, garlic, and heavy berbere sauce.",
    fastingSuitability: "non_fasting",
    glycemicIndex: { value: 22, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 0,
      tanninsMgPer100g: 0,
      oxalatesMgPer100g: 0,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Animal-source food free from plant antinutrients.",
      fermentationReductionPct: 100,
      bioavailabilityUpliftDescription: "Contains meat factor which stimulates simultaneous non-heme iron absorption.",
    },
    macros: { caloriesKcal: 235, proteinG: 22.5, carbohydratesG: 6.5, fatsG: 14.0, dietaryFiberG: 1.8 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 22.5, bioavailabilityFactor: 1.0, note: "Complete animal protein" },
      { name: "Vitamin B12", symbol: "B12", unit: "mcg", amountPer100g: 1.8, bioavailabilityFactor: 1.0, note: "Essential animal-source cobalamin (75% RDA per portion)" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 3.8, bioavailabilityFactor: 1.8, note: "Heme iron with 25-30% direct intestinal absorption" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 3.2, bioavailabilityFactor: 1.5, note: "Highly bioavailable animal zinc" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Post-fasting remineralization & B12 repletion", "Muscle mass synthesis", "Anemia recovery"],
      bioactiveCompounds: ["Carnitine", "Carnosine", "Egg lutein"],
      digestiveTolerance: "Rich and spiced; consume with plenty of teff injera.",
    },
  },
  {
    id: "efct-0602",
    name: "Siga Key Wot (Beef Stew)",
    nameAmharic: "የሥጋ ቀይ ወጥ",
    category: "Meat, Poultry & Dairy",
    sourceRef: "EFCT2025-0602",
    traditionalPreparation: "Tender beef cubes slow-simmered in berbere, caramelized red onions, garlic, and spiced clarified butter.",
    fastingSuitability: "non_fasting",
    glycemicIndex: { value: 18, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 0,
      tanninsMgPer100g: 0,
      oxalatesMgPer100g: 0,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Animal-source food.",
      fermentationReductionPct: 100,
      bioavailabilityUpliftDescription: "High heme iron density.",
    },
    macros: { caloriesKcal: 245, proteinG: 24.0, carbohydratesG: 5.0, fatsG: 15.0, dietaryFiberG: 1.2 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 24.0, bioavailabilityFactor: 1.0, note: "Complete mammalian protein" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.2, bioavailabilityFactor: 1.85, note: "Heme iron" },
      { name: "Vitamin B12", symbol: "B12", unit: "mcg", amountPer100g: 2.1, bioavailabilityFactor: 1.0, note: "Near 100% daily B12 requirement" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 4.8, bioavailabilityFactor: 1.5, note: "Peak bioavailable zinc" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Rapid hepatic B12 store replenishment", "Zinc-dependent immune recovery"],
      bioactiveCompounds: ["Creatine", "Heme iron peptide complexes"],
      digestiveTolerance: "Substantial satiety; best paired with greens (Gomen).",
    },
  },
  {
    id: "efct-0603",
    name: "Minced Beef Kitfo (with Mitmita & Niter Kibbeh)",
    nameAmharic: "ክትፎ",
    category: "Meat, Poultry & Dairy",
    sourceRef: "EFCT2025-0603",
    traditionalPreparation: "Finely minced extra-lean top round beef warmed with spiced clarified butter (niter kibbeh) and fiery mitmita chili powder. Served raw, leb-leb (warmed), or betam-tibsel (cooked).",
    fastingSuitability: "non_fasting",
    glycemicIndex: { value: 10, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 0,
      tanninsMgPer100g: 0,
      oxalatesMgPer100g: 0,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Animal protein with antioxidant spice blend.",
      fermentationReductionPct: 100,
      bioavailabilityUpliftDescription: "Pure bioavailable heme iron and zinc.",
    },
    macros: { caloriesKcal: 270, proteinG: 26.0, carbohydratesG: 1.5, fatsG: 18.0, dietaryFiberG: 0.5 },
    nutrients: [
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 4.6, bioavailabilityFactor: 1.9, note: "Superior heme iron absorption" },
      { name: "Vitamin B12", symbol: "B12", unit: "mcg", amountPer100g: 2.4, bioavailabilityFactor: 1.0, note: "100% full daily RDA in 100g" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 5.2, bioavailabilityFactor: 1.6, note: "Unmatched bioavailable zinc" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 26.0, bioavailabilityFactor: 1.0, note: "Pure muscle protein" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Post-anemic recovery", "Heavy athletic power replenishment"],
      bioactiveCompounds: ["Carnitine", "CLA (Conjugated linoleic acid from grass-fed cattle)"],
      digestiveTolerance: "Raw/rare meat carries zoonotic tapeworm (Taenia saginata) risk; ensure meat is veterinary inspected or thoroughly cooked (betam-tibsel) during pregnancy.",
    },
  },
  {
    id: "efct-0604",
    name: "Ayib (Fresh Ethiopian Cottage Cheese)",
    nameAmharic: "አይብ",
    category: "Meat, Poultry & Dairy",
    sourceRef: "EFCT2025-0604",
    traditionalPreparation: "Soft lactic curd cheese made by gently heating naturally fermented whole buttermilk, straining through muslin. Traditionally served alongside spicy wots and kitfo.",
    fastingSuitability: "non_fasting",
    glycemicIndex: { value: 25, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 0,
      tanninsMgPer100g: 0,
      oxalatesMgPer100g: 0,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Lactic fermentation curdling.",
      fermentationReductionPct: 100,
      bioavailabilityUpliftDescription: "Lactic acid solubilizes calcium into ionic, easily absorbed form.",
    },
    macros: { caloriesKcal: 145, proteinG: 13.5, carbohydratesG: 3.5, fatsG: 8.5, dietaryFiberG: 0.0 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 240.0, bioavailabilityFactor: 1.35, note: "Highly bioavailable ionic dairy calcium" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 13.5, bioavailabilityFactor: 1.0, note: "Casein and whey protein" },
      { name: "Vitamin B12", symbol: "B12", unit: "mcg", amountPer100g: 0.9, bioavailabilityFactor: 1.0, note: "Dairy B12" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Tempering acute gastrointestinal capsicum irritation", "Bone mineralization", "Sleep-supportive tryptophan"],
      bioactiveCompounds: ["Casein phosphopeptides", "L-tryptophan"],
      digestiveTolerance: "Lactic fermentation reduces lactose, making it easier to tolerate than fresh sweet milk.",
    },
  },
  {
    id: "efct-0605",
    name: "Ergo (Traditional Fermented Sour Milk)",
    nameAmharic: "እርጎ",
    category: "Meat, Poultry & Dairy",
    sourceRef: "EFCT2025-0605",
    traditionalPreparation: "Fresh raw whole cow milk fermented spontaneously at ambient highland temperatures in smoked clay pots (Geleb). Forms rich thick curds.",
    fastingSuitability: "non_fasting",
    glycemicIndex: { value: 30, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 0,
      tanninsMgPer100g: 0,
      oxalatesMgPer100g: 0,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Probiotic spontaneous fermentation.",
      fermentationReductionPct: 100,
      bioavailabilityUpliftDescription: "Probiotic live cultures generate peptides and synthesize B vitamins.",
    },
    macros: { caloriesKcal: 135, proteinG: 6.8, carbohydratesG: 8.0, fatsG: 8.2, dietaryFiberG: 0.0 },
    nutrients: [
      { name: "Calcium", symbol: "Ca", unit: "mg", amountPer100g: 220.0, bioavailabilityFactor: 1.35, note: "Lactic-bound bioavailable calcium" },
      { name: "Vitamin B12", symbol: "B12", unit: "mcg", amountPer100g: 0.7, bioavailabilityFactor: 1.0, note: "Fermented dairy cobalamin" },
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 6.8, bioavailabilityFactor: 1.0, note: "Lactobacillus pre-digested proteins" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Gut microbiome restoration", "Recovery from antibiotic dysbiosis", "Calcium replenishment"],
      bioactiveCompounds: ["Lactobacillus acidophilus & Lactococcus lactis live strains", "Smoked pot phenolic traces"],
      digestiveTolerance: "Significantly lower lactose than sweet milk; well tolerated by lactose maldigesters.",
    },
  },
  {
    id: "efct-0606",
    name: "Lake Tana Tilapia / Asa Wot (Fish Stew)",
    nameAmharic: "የዓሣ ወጥ",
    category: "Meat, Poultry & Dairy",
    sourceRef: "EFCT2025-0606",
    traditionalPreparation: "Freshwater Tilapia from Lake Tana or Lake Hawassa simmered with berbere, garlic, korerima, and tomato paste.",
    fastingSuitability: "dual", // Permitted during certain lesser fasts in local regional traditions
    glycemicIndex: { value: 15, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 0,
      tanninsMgPer100g: 0,
      oxalatesMgPer100g: 0,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Cooked fresh fish.",
      fermentationReductionPct: 100,
      bioavailabilityUpliftDescription: "High bioavailability white fish protein.",
    },
    macros: { caloriesKcal: 175, proteinG: 20.0, carbohydratesG: 4.0, fatsG: 8.5, dietaryFiberG: 1.0 },
    nutrients: [
      { name: "Protein", symbol: "Pro", unit: "g", amountPer100g: 20.0, bioavailabilityFactor: 1.0, note: "High quality lean fish protein" },
      { name: "Vitamin B12", symbol: "B12", unit: "mcg", amountPer100g: 2.2, bioavailabilityFactor: 1.0, note: "Abundant fish B12" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 2.1, bioavailabilityFactor: 1.7, note: "Heme iron" },
      { name: "Zinc", symbol: "Zn", unit: "mg", amountPer100g: 1.9, bioavailabilityFactor: 1.4, note: "Freshwater fish zinc" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Cognitive brain health", "Cardiovascular support", "Gentle non-red-meat protein"],
      bioactiveCompounds: ["EPA & DHA omega-3 precursors", "Selenium"],
      digestiveTolerance: "Light, easily digestible, and anti-inflammatory.",
    },
  },

  // ==========================================
  // 7. SPICES & NUTRIENT AMPLIFIERS
  // ==========================================
  {
    id: "efct-0701",
    name: "Traditional Ethiopian Berbere Paste",
    nameAmharic: "በርበሬ",
    category: "Spices & Nutrient Amplifiers",
    sourceRef: "EFCT2025-0701",
    traditionalPreparation: "Sun-dried red peppers de-seeded, blended with korerima (cardamom), fenugreek (abish), cloves, ginger, garlic, rue (tena adam), and holy basil, slow roasted and ground into vibrant crimson powder.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 25, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 50,
      tanninsMgPer100g: 65,
      oxalatesMgPer100g: 35,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Sun-drying, deseeded chili pods, dry roasting and slow aging.",
      fermentationReductionPct: 60,
      bioavailabilityUpliftDescription: "Capsaicin and piperine stimulate mesenteric blood flow, multiplying nutrient absorption.",
    },
    macros: { caloriesKcal: 290, proteinG: 12.5, carbohydratesG: 48.0, fatsG: 9.5, dietaryFiberG: 22.0 },
    nutrients: [
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 1450.0, bioavailabilityFactor: 1.0, note: "High carotenoid concentration from sun-dried peppers" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 12.0, bioavailabilityFactor: 1.1, note: "Spice mineral iron" },
      { name: "Vitamin C", symbol: "VitC", unit: "mg", amountPer100g: 35.0, bioavailabilityFactor: 0.8, note: "Residual sun-dried vitamin C" },
      { name: "Dietary Fiber", symbol: "Fib", unit: "g", amountPer100g: 22.0, bioavailabilityFactor: 1.0, note: "Dietary spice fiber" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Peripheral circulation stimulation", "Thermogenic metabolism elevation", "Antimicrobial food preservation"],
      bioactiveCompounds: ["Capsaicin", "4-terpineol from korerima", "Trigonelline from fenugreek"],
      digestiveTolerance: "Strong thermogenic spice; moderate in active gastric ulcers or severe reflux.",
    },
  },
  {
    id: "efct-0702",
    name: "Mitmita Spice Blend",
    nameAmharic: "ሚጥሚጣ",
    category: "Spices & Nutrient Amplifiers",
    sourceRef: "EFCT2025-0702",
    traditionalPreparation: "Pungent bird's eye chili peppers (Capsicum frutescens) ground with Ethiopian cardamom (korerima), whole cloves (qurunfud), and sea salt.",
    fastingSuitability: "fasting_friendly",
    glycemicIndex: { value: 20, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 40,
      tanninsMgPer100g: 45,
      oxalatesMgPer100g: 20,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Dry roasting and fine milling.",
      fermentationReductionPct: 60,
      bioavailabilityUpliftDescription: "Clove eugenol acts as natural carminative and gastro-protective agent.",
    },
    macros: { caloriesKcal: 310, proteinG: 11.0, carbohydratesG: 52.0, fatsG: 10.0, dietaryFiberG: 24.0 },
    nutrients: [
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 1800.0, bioavailabilityFactor: 1.0, note: "Dense provitamin A" },
      { name: "Iron", symbol: "Fe", unit: "mg", amountPer100g: 9.5, bioavailabilityFactor: 1.0, note: "Spice iron" },
      { name: "Magnesium", symbol: "Mg", unit: "mg", amountPer100g: 140.0, bioavailabilityFactor: 1.0, note: "Spice mineral trace" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Acute peripheral vasodilation", "Antimicrobial food defense when consuming raw kitfo"],
      bioactiveCompounds: ["Capsaicinoids", "Eugenol from cloves"],
      digestiveTolerance: "Very high heat; use sparingly as pinch condiment.",
    },
  },
  {
    id: "efct-0703",
    name: "Niter Kibbeh (Ethiopian Clarified Spiced Butter)",
    nameAmharic: "ንጥር ቅቤ",
    category: "Spices & Nutrient Amplifiers",
    sourceRef: "EFCT2025-0703",
    traditionalPreparation: "Cultured highland cow butter simmered on low heat until milk solids precipitate, clarified and infused with korerima, koseret (Lippia abyssinica), tikur azmud (nigella), ginger, and garlic.",
    fastingSuitability: "non_fasting",
    glycemicIndex: { value: 0, rating: "low" },
    antinutrients: {
      phyticAcidMgPer100g: 0,
      tanninsMgPer100g: 0,
      oxalatesMgPer100g: 0,
      trypsinInhibitorLevel: "negligible",
      traditionalDegradationMethod: "Clarification completely removes water and milk solids.",
      fermentationReductionPct: 100,
      bioavailabilityUpliftDescription: "Essential fat carrier that multiplies absorption of fat-soluble vitamins (A, D, E, K) from greens.",
    },
    macros: { caloriesKcal: 884, proteinG: 0.3, carbohydratesG: 0.0, fatsG: 99.5, dietaryFiberG: 0.0 },
    nutrients: [
      { name: "Vitamin A", symbol: "VitA", unit: "mcg", amountPer100g: 850.0, bioavailabilityFactor: 1.0, note: "True preformed retinol from grass-fed highland cattle" },
      { name: "Vitamin D", symbol: "VitD", unit: "IU", amountPer100g: 65.0, bioavailabilityFactor: 1.0, note: "Natural dairy vitamin D" },
    ],
    clinicalhealthNotes: {
      primaryIndications: ["Carotenoid and fat-soluble vitamin absorption catalyst", "Conjugated linoleic acid (CLA) delivery"],
      bioactiveCompounds: ["Butyric acid", "Koseret terpenes", "Thymoquinone traces from tikur azmud"],
      digestiveTolerance: "Milk solids removed; well tolerated by lactose sensitive individuals.",
    },
  },
];

export function findEFCTFoodById(id: string): EFCTFoodItem | undefined {
  return EFCT_MASTER_FOODS.find((f) => f.id === id);
}

export function searchEFCTFoods(query: string, category?: string, fastingOnly?: boolean): EFCTFoodItem[] {
  let list = [...EFCT_MASTER_FOODS];

  if (category && category !== "All") {
    list = list.filter((f) => f.category.toLowerCase() === category.toLowerCase());
  }

  if (fastingOnly) {
    list = list.filter((f) => f.fastingSuitability === "fasting_friendly");
  }

  if (query && query.trim().length > 0) {
    const q = query.trim().toLowerCase();
    list = list.filter(
      (f) =>
        f.name.toLowerCase().includes(q) ||
        f.nameAmharic.includes(query.trim()) ||
        f.category.toLowerCase().includes(q) ||
        f.traditionalPreparation.toLowerCase().includes(q) ||
        f.clinicalhealthNotes.primaryIndications.some((ind) => ind.toLowerCase().includes(q))
    );
  }

  return list;
}
