export interface RecipeIngredientCue {
  name: string;
  catalogFoodId?: string;
  rawCerealId?: string;
}

export const RECIPE_INGREDIENT_CUES: Record<string, RecipeIngredientCue[]> = {
  "efct-0101": [{ name: "Brown teff flour", rawCerealId: "raw-teff" }, { name: "Water" }, { name: "Ersho starter" }],
  "efct-0102": [{ name: "White teff flour", rawCerealId: "raw-teff" }, { name: "Water" }, { name: "Ersho starter" }],
  "efct-0103": [{ name: "Red teff flour", rawCerealId: "raw-teff" }, { name: "Water" }, { name: "Ersho starter" }],
  "efct-0104": [{ name: "Barley flour", rawCerealId: "raw-barley" }, { name: "Water" }, { name: "Honey or salt (optional)" }],
  "efct-0105": [{ name: "Cracked whole wheat", rawCerealId: "raw-wheat" }, { name: "Water" }, { name: "Niter kibbeh or oil (optional)", catalogFoodId: "efct-0703" }],
  "efct-0106": [{ name: "Roasted barley", rawCerealId: "raw-barley" }, { name: "Emmer wheat" }, { name: "Water" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Berbere", catalogFoodId: "efct-0701" }],
  "efct-0107": [{ name: "Sorghum flour", rawCerealId: "raw-sorghum" }, { name: "Water" }, { name: "Fermentation starter" }],
  "efct-0108": [{ name: "Finger millet flour", rawCerealId: "raw-finger-millet" }, { name: "Water" }, { name: "Ersho starter" }],
  "efct-0109": [{ name: "Roasted barley", rawCerealId: "raw-barley" }, { name: "Chickpeas" }, { name: "Peanuts" }, { name: "Safflower seed" }],
  "efct-0201": [{ name: "Chickpea flour" }, { name: "Field pea flour" }, { name: "Red onion" }, { name: "Garlic" }, { name: "Berbere", catalogFoodId: "efct-0701" }],
  "efct-0202": [{ name: "Red lentils" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Red onion" }, { name: "Ginger" }, { name: "Garlic" }],
  "efct-0203": [{ name: "Yellow split peas" }, { name: "Turmeric" }, { name: "Garlic" }, { name: "Ginger" }, { name: "Red onion" }],
  "efct-0204": [{ name: "Fava beans" }, { name: "Onion" }, { name: "Ginger" }, { name: "Cardamom" }],
  "efct-0205": [{ name: "Chickpea dough" }, { name: "Berbere sauce", catalogFoodId: "efct-0701" }],
  "efct-0206": [{ name: "Green lentils" }, { name: "Ethiopian brown mustard" }, { name: "Lime juice" }, { name: "Red onion" }, { name: "Green chili" }],
  "efct-0207": [{ name: "Chickpeas" }, { name: "Wheat kernels", rawCerealId: "raw-wheat" }, { name: "Fava beans" }, { name: "Salt" }],
  "efct-0208": [{ name: "Green beans" }, { name: "Carrots" }, { name: "Red onion" }, { name: "Garlic" }, { name: "Turmeric" }],
  "efct-0209": [{ name: "Fava bean flour" }, { name: "Safflower seed" }, { name: "Mustard seed" }, { name: "Garlic" }, { name: "Rue" }],
  "efct-0301": [{ name: "Fermented enset (false banana) pulp" }],
  "efct-0302": [{ name: "Enset starch (bulla)" }, { name: "Water" }],
  "efct-0303": [{ name: "Taro (godere)" }, { name: "Water" }],
  "efct-0304": [{ name: "Sweet potato" }, { name: "Water" }],
  "efct-0305": [{ name: "Oromo potato" }, { name: "Water" }],
  "efct-0401": [{ name: "Ethiopian collard greens" }, { name: "Onion" }, { name: "Garlic" }, { name: "Cooking oil or niter kibbeh", catalogFoodId: "efct-0703" }],
  "efct-0402": [{ name: "Moringa stenopetala leaves" }],
  "efct-0403": [{ name: "Pumpkin or squash" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Turmeric" }, { name: "Garlic" }, { name: "Red onion" }],
  "efct-0404": [{ name: "Tomato" }, { name: "Red onion" }, { name: "Green chili" }, { name: "Lemon juice" }, { name: "Fermented teff injera" }],
  "efct-0501": [{ name: "Flaxseed" }, { name: "Water" }, { name: "Honey (optional)" }],
  "efct-0502": [{ name: "Safflower seed" }, { name: "Water" }, { name: "Chili" }, { name: "Injera" }],
  "efct-0503": [{ name: "Niger seed" }],
  "efct-0601": [{ name: "Chicken" }, { name: "Hardboiled egg" }, { name: "Red onion" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Ginger" }, { name: "Garlic" }],
  "efct-0602": [{ name: "Beef" }, { name: "Red onion" }, { name: "Garlic" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }],
  "efct-0603": [{ name: "Beef" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Mitmita", catalogFoodId: "efct-0702" }],
  "efct-0604": [{ name: "Fermented whole buttermilk" }],
  "efct-0605": [{ name: "Whole cow's milk" }, { name: "Traditional starter culture" }],
  "efct-0606": [{ name: "Tilapia" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Garlic" }, { name: "Korerima" }, { name: "Tomato paste" }],
  "efct-0701": [{ name: "Sun-dried red peppers" }, { name: "Korerima" }, { name: "Fenugreek" }, { name: "Cloves" }, { name: "Ginger" }, { name: "Garlic" }, { name: "Rue" }, { name: "Holy basil" }],
  "efct-0702": [{ name: "Hot peppers" }, { name: "Spices" }],
  "efct-0703": [{ name: "Clarified butter" }, { name: "Koseret" }, { name: "Black cumin" }],
  "efct-0110": [{ name: "Wheat & teff flour", rawCerealId: "raw-wheat" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Honey (optional)" }],
  "efct-0111": [{ name: "Roasted barley flour", rawCerealId: "raw-barley" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Korerima", catalogFoodId: "efct-0705" }, { name: "Salt" }],
  "efct-0112": [{ name: "Brown teff", rawCerealId: "raw-teff" }, { name: "Barley flour", rawCerealId: "raw-barley" }, { name: "Sorghum", rawCerealId: "raw-sorghum" }, { name: "Ersho starter" }],
  "efct-0113": [{ name: "Emmer wheat flour", rawCerealId: "raw-wheat" }, { name: "Water" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Berbere", catalogFoodId: "efct-0701" }],
  "efct-0114": [{ name: "Roasted wheat", rawCerealId: "raw-wheat" }, { name: "Peanuts" }, { name: "Salt" }],
  "efct-0115": [{ name: "Roasted barley flour", rawCerealId: "raw-barley" }, { name: "Ground flaxseed" }, { name: "Water" }, { name: "Cardamom" }],
  "efct-0116": [{ name: "Wheat flour", rawCerealId: "raw-wheat" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Black cumin", catalogFoodId: "efct-0709" }, { name: "Garlic" }],
  "efct-0117": [{ name: "Whole wheat flour", rawCerealId: "raw-wheat" }, { name: "Koba (enset leaf)" }, { name: "Fenugreek", catalogFoodId: "efct-0714" }, { name: "Black seed", catalogFoodId: "efct-0709" }],
  "efct-0118": [{ name: "Wheat flour", rawCerealId: "raw-wheat" }, { name: "Korerima", catalogFoodId: "efct-0705" }, { name: "Fenugreek", catalogFoodId: "efct-0714" }, { name: "Black cumin", catalogFoodId: "efct-0709" }],
  "efct-0119": [{ name: "Wheat or teff flour", rawCerealId: "raw-teff" }, { name: "Water" }, { name: "Salt" }],
  "efct-0120": [{ name: "Roasted barley malt", rawCerealId: "raw-barley" }, { name: "Gesho" }, { name: "Water" }],
  "efct-0121": [{ name: "Barley malt (bikil)", rawCerealId: "raw-barley" }, { name: "Sorghum (enkuro)", rawCerealId: "raw-sorghum" }, { name: "Gesho leaves & stems" }, { name: "Water" }],
  "efct-0122": [{ name: "Maize flour", rawCerealId: "raw-maize" }, { name: "Malted sorghum", rawCerealId: "raw-sorghum" }, { name: "Finger millet", rawCerealId: "raw-finger-millet" }, { name: "Water" }],
  "efct-0123": [{ name: "Roasted barley", rawCerealId: "raw-barley" }, { name: "Garlic" }, { name: "Ginger" }, { name: "Rue", catalogFoodId: "efct-0707" }],
  "efct-0127": [{ name: "Teff injera", catalogFoodId: "efct-0101" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Awaze paste", catalogFoodId: "efct-0704" }],
  "efct-0131": [{ name: "Highland barley flour", rawCerealId: "raw-barley" }, { name: "Water" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Berbere", catalogFoodId: "efct-0701" }],
  "efct-0132": [{ name: "Red teff flour", rawCerealId: "raw-teff" }, { name: "Water" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Mitmita", catalogFoodId: "efct-0702" }],
  "efct-0210": [{ name: "Chickpea flour" }, { name: "Cured beef jerky (quanta)" }, { name: "Red onion" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }],
  "efct-0211": [{ name: "Chickpea flour" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Garlic" }, { name: "Shallots" }, { name: "Spiced oil" }],
  "efct-0212": [{ name: "De-hulled fava beans" }, { name: "Fenugreek", catalogFoodId: "efct-0714" }, { name: "Mustard paste", catalogFoodId: "efct-0711" }, { name: "Garlic" }],
  "efct-0213": [{ name: "Yellow split peas" }, { name: "Pumpkin" }, { name: "Turmeric", catalogFoodId: "efct-0712" }, { name: "Garlic" }],
  "efct-0214": [{ name: "Whole brown lentils" }, { name: "Turmeric", catalogFoodId: "efct-0712" }, { name: "Ginger" }, { name: "Garlic" }, { name: "Red onion" }],
  "efct-0215": [{ name: "Whole brown lentils" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Red onion" }, { name: "Garlic" }, { name: "Korerima", catalogFoodId: "efct-0705" }],
  "efct-0216": [{ name: "Red haricot beans" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Shallots" }, { name: "Garlic" }],
  "efct-0220": [{ name: "White lupin seeds" }, { name: "Water" }, { name: "Salt" }],
  "efct-0221": [{ name: "Fava beans" }, { name: "Tomato" }, { name: "Green chili" }, { name: "Olive oil" }, { name: "Cumin" }],
  "efct-0306": [{ name: "Anchote tuber" }, { name: "Garlic" }, { name: "Salt" }, { name: "Spiced butter or oil" }],
  "efct-0307": [{ name: "Potato" }, { name: "Carrot" }, { name: "Turmeric", catalogFoodId: "efct-0712" }, { name: "Garlic" }],
  "efct-0308": [{ name: "Potato" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Red onion" }, { name: "Garlic" }],
  "efct-0309": [{ name: "Fermented enset (kocho)" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Koba leaf wrapper" }],
  "efct-0310": [{ name: "Refined enset starch (bulla)" }, { name: "Water or milk" }, { name: "Cardamom", catalogFoodId: "efct-0705" }, { name: "Honey" }],
  "efct-0405": [{ name: "Ethiopian collards (gomen)" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Mitmita", catalogFoodId: "efct-0702" }, { name: "Shallots" }],
  "efct-0406": [{ name: "Cabbage" }, { name: "Carrots" }, { name: "Potato" }, { name: "Turmeric", catalogFoodId: "efct-0712" }],
  "efct-0407": [{ name: "Beetroot" }, { name: "Potato" }, { name: "Red onion" }, { name: "Green chili" }],
  "efct-0408": [{ name: "Lettuce" }, { name: "Tomato" }, { name: "Green chili" }, { name: "Lime juice" }],
  "efct-0409": [{ name: "Green chili peppers" }, { name: "Tomato" }, { name: "Shallot" }, { name: "Lemon juice" }],
  "efct-0410": [{ name: "Okra" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Red onion" }, { name: "Garlic" }, { name: "Tomato" }],
  "efct-0504": [{ name: "White sesame seeds" }, { name: "Water" }, { name: "Chili" }, { name: "Fermented teff injera", catalogFoodId: "efct-0101" }],
  "efct-0505": [{ name: "Roasted white sesame seeds" }, { name: "Korerima", catalogFoodId: "efct-0705" }, { name: "Salt" }],
  "efct-0506": [{ name: "Roasted flaxseed" }],
  "efct-0507": [{ name: "Safflower seeds" }, { name: "Red onion" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Potato" }],
  "efct-0508": [{ name: "Peanuts" }, { name: "Garlic" }, { name: "Bird's eye chili" }, { name: "Salt" }],
  "efct-0509": [{ name: "Ground flaxseed" }, { name: "Barley flour", rawCerealId: "raw-barley" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Berbere", catalogFoodId: "efct-0701" }],
  "efct-0607": [{ name: "Beef sirloin" }, { name: "Red onion" }, { name: "Garlic" }, { name: "Rosemary" }, { name: "Jalapeño" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }],
  "efct-0608": [{ name: "Highland lamb" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Rosemary" }, { name: "Shallots" }, { name: "Garlic" }],
  "efct-0609": [{ name: "Lean beef tenderloin" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Awaze paste", catalogFoodId: "efct-0704" }, { name: "Korerima", catalogFoodId: "efct-0705" }],
  "efct-0610": [{ name: "Country chicken" }, { name: "Hard-boiled egg" }, { name: "Turmeric", catalogFoodId: "efct-0712" }, { name: "Red onion" }, { name: "Ginger" }, { name: "Garlic" }],
  "efct-0611": [{ name: "Highland lamb" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Red onion" }, { name: "Garlic" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }],
  "efct-0612": [{ name: "Highland lamb" }, { name: "Turmeric", catalogFoodId: "efct-0712" }, { name: "Shallots" }, { name: "Garlic" }, { name: "Ginger" }],
  "efct-0613": [{ name: "Lamb shanks & marrow bones" }, { name: "Ginger" }, { name: "Garlic" }, { name: "Turmeric", catalogFoodId: "efct-0712" }, { name: "Jalapeño" }],
  "efct-0614": [{ name: "Lean beef" }, { name: "Awaze", catalogFoodId: "efct-0704" }, { name: "Mitmita", catalogFoodId: "efct-0702" }, { name: "Green chili" }],
  "efct-0615": [{ name: "Cured beef jerky (quanta)" }, { name: "Teff injera", catalogFoodId: "efct-0101" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Red onion" }],
  "efct-0618": [{ name: "Minced beef" }, { name: "Fenugreek", catalogFoodId: "efct-0714" }, { name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Hard-boiled egg" }],
  "efct-0620": [{ name: "Beef tripe" }, { name: "Beef liver" }, { name: "Lean beef" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Mitmita", catalogFoodId: "efct-0702" }, { name: "Onion" }],
  "efct-0622": [{ name: "Whole cow's milk" }, { name: "Lactic culture" }],
  "efct-0623": [{ name: "Fermented whey" }],
  "efct-0624": [{ name: "Tilapia" }, { name: "Garlic" }, { name: "Lemon" }, { name: "Teff flour", rawCerealId: "raw-teff" }, { name: "Oil" }],
  "efct-0632": [{ name: "Farm eggs" }, { name: "Red onion" }, { name: "Tomato" }, { name: "Green chili" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }],
  "efct-0636": [{ name: "Ayib cottage curd", catalogFoodId: "efct-0605" }, { name: "Steamed collards", catalogFoodId: "efct-0401" }, { name: "Niter kibbeh", catalogFoodId: "efct-0703" }, { name: "Mitmita", catalogFoodId: "efct-0702" }],
  "efct-0704": [{ name: "Berbere", catalogFoodId: "efct-0701" }, { name: "Tej (honey wine)", catalogFoodId: "efct-0716" }, { name: "Garlic" }, { name: "Ginger" }],
  "efct-0705": [{ name: "Aframomum corrorima pods" }],
  "efct-0706": [{ name: "Lippia adoensis leaves" }],
  "efct-0707": [{ name: "Ruta chalepensis leaves & seed pods" }],
  "efct-0708": [{ name: "Ocimum basilicum var. thyrsiflorum dried flower spikes" }],
  "efct-0709": [{ name: "Nigella sativa seeds" }],
  "efct-0710": [{ name: "Trachyspermum ammi seeds" }],
  "efct-0711": [{ name: "Brassica nigra seeds" }, { name: "Water" }, { name: "Vinegar" }],
  "efct-0712": [{ name: "Curcuma longa rhizome" }],
  "efct-0713": [{ name: "Zingiber officinale dried rhizome" }],
  "efct-0714": [{ name: "Trigonella foenum-graecum seeds" }],
  "efct-0715": [{ name: "Cinnamomum verum bark" }],
  "efct-0716": [{ name: "Raw wild forest honey" }, { name: "Water" }, { name: "Gesho debarked stems" }],
};
