/**
 * Generates src/styles/palette.css from Tailwind's default colours.
 *
 * The UI is authored dark-first (text-white, bg-slate-950, text-emerald-400 …). Each Tailwind colour
 * variable points at a --p-* variable that holds the original shade in dark mode and the mirrored
 * shade (950↔50, 900↔100 …) in light mode, so the same classes read well in both themes.
 *
 * Legacy aliases: emerald and teal are the brand (Luminous Blue) and map to the sky ramp.
 *
 *   node scripts/generate-palette.mjs
 */
import fs from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);
const themeCss = fs.readFileSync(path.join(path.dirname(require.resolve("tailwindcss/package.json")), "theme.css"), "utf8");

const SHADES = ["50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950"];
const mirror = (shade) => SHADES[SHADES.length - 1 - SHADES.indexOf(shade)];
const FAMILIES = [
  "slate", "gray", "zinc", "neutral", "stone", "red", "orange", "amber", "yellow", "lime", "green",
  "emerald", "teal", "cyan", "sky", "blue", "indigo", "violet", "purple", "fuchsia", "pink", "rose",
];
const ALIASES = { emerald: "sky", teal: "sky" };

const defaults = {};
for (const match of themeCss.matchAll(/--color-([a-z]+)-(\d{2,3}):\s*([^;]+);/g)) {
  defaults[`${match[1]}-${match[2]}`] = match[3].trim();
}

const value = (family, shade) => {
  const resolved = defaults[`${ALIASES[family] ?? family}-${shade}`];
  if (!resolved) throw new Error(`Missing Tailwind colour ${family}-${shade}`);
  return resolved;
};

const dark = [];
const light = [];
const theme = [];
for (const family of FAMILIES) {
  for (const shade of SHADES) {
    const name = `--p-${family}-${shade}`;
    dark.push(`  ${name}: ${value(family, shade)};`);
    light.push(`  ${name}: ${value(family, mirror(shade))};`);
    theme.push(`  --color-${family}-${shade}: var(${name});`);
  }
}

const out = `/* Generated by scripts/generate-palette.mjs — do not edit by hand. */

/* Light theme: mirrored shades so dark-first classes keep their contrast. */
:root {
${light.join("\n")}
  --p-white: ${value("slate", "950")};
  --p-black: #ffffff;
}

/* Dark theme: Tailwind's original shades. */
html.dark {
${dark.join("\n")}
  --p-white: #ffffff;
  --p-black: #000000;
}

@theme inline {
${theme.join("\n")}
  --color-white: var(--p-white);
  --color-black: var(--p-black);
}
`;

fs.writeFileSync("src/styles/palette.css", out);
console.log(`Wrote src/styles/palette.css (${FAMILIES.length} families)`);
