import { EthiopianNameRecord } from "../types";

export const ETHIOPIAN_NAMES_DATABASE: EthiopianNameRecord[] = [
  // ==================== AMHARIC NAMES ====================
  {
    name: "Tigist",
    geezFidel: "ትዕግሥት",
    language: "Amharic",
    meaning: "Patience, endurance, and quiet fortitude",
    gender: "female",
    originEtymology: "Derived from the Ge'ez root 'አግሠጸ / ትዕግሥት' (Ta'agasa - to endure with steadfast grace).",
    culturalContext: "Historically bestowed upon daughters as a prayer for enduring grace and resilient composure through life's trials.",
    numerologicalValues: { destiny: 5, soulUrge: 8, personality: 6 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Deep interior resilience, reluctance to complain or express acute physical vulnerability.",
      emotionalExpressionStyle: "Internalizes emotional distress; absorbs relational tension silently before seeking relief.",
      psychosomaticTendency: "Gastrointestinal somatization (acid buildup / stomach tension) and upper shoulder holding from chronic patience.",
      balancingVirtue: "Active emotional venting, boundary assertion, and warm comforting meals rather than solitary endurance.",
    },
  },
  {
    name: "Mulugeta",
    geezFidel: "ሙሉጌታ",
    language: "Amharic",
    meaning: "Full of grace, dignity, and divine abundance",
    gender: "male",
    originEtymology: "Compound of 'Mulu' (ሙሉ - full/complete) and 'Geta' (ጌታ - Lord / master / benefactor).",
    culturalContext: "Bestowed in gratitude for family survival and divine blessing, representing holistic completeness.",
    numerologicalValues: { destiny: 7, soulUrge: 9, personality: 7 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Quiet spiritual dignity, noble self-reliance, expectation of wholeness in body and spirit.",
      emotionalExpressionStyle: "Introspective and contemplative; prefers philosophical reflection to impulsive confrontation.",
      psychosomaticTendency: "Prone to introspective overthinking, nocturnal sleep phase delays, and cognitive fatigue.",
      balancingVirtue: "Structured circadian sleep habits, grounding outdoor physical exertion, and regular social recreation.",
    },
  },
  {
    name: "Abebe",
    geezFidel: "አበበ",
    language: "Amharic",
    meaning: "He has blossomed, flourished, and flowered",
    gender: "male",
    originEtymology: "From the verb 'አበበ' (Abebe - to blossom/flower, from the root አበባ).",
    culturalContext: "Celebrates the blossoming of a family lineage, the arrival of spring rains, and vibrant renewal.",
    numerologicalValues: { destiny: 1, soulUrge: 6, personality: 4 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Youthful vitality, natural optimism, expectation of growth and rapid physical recovery.",
      emotionalExpressionStyle: "Expansive and expressive; readily projects warmth and energy to companions.",
      psychosomaticTendency: "Elevated metabolic pace; tendency toward acute inflammatory surges when growth is blocked.",
      balancingVirtue: "Cooling foods (fresh highland vegetables, Ayib) and disciplined physical training.",
    },
  },
  {
    name: "Bekele",
    geezFidel: "በቀለ",
    language: "Amharic",
    meaning: "He sprouted, grew, and germinated successfully",
    gender: "male",
    originEtymology: "From the Semitic Ethiopian root 'በቀለ' (Baqala - to sprout forth from the earth).",
    culturalContext: "A name celebrating agricultural abundance, hardy highland crops, and survival against frost.",
    numerologicalValues: { destiny: 8, soulUrge: 6, personality: 2 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Grounded earthy endurance, physical stamina rooted in the soil, practical work ethic.",
      emotionalExpressionStyle: "Measured and steady; does not display erratic emotional highs or lows.",
      psychosomaticTendency: "Skeletal stiffness in knees and lower back; tendency to push through physical pain.",
      balancingVirtue: "Joint lubrication through healthy fats (sesame, flaxseed) and hot mineral spring soaks.",
    },
  },
  {
    name: "Almaz",
    geezFidel: "አልማዝ",
    language: "Amharic",
    meaning: "Diamond — unbreakable, luminous, and precious",
    gender: "female",
    originEtymology: "Rooted in classical Ge'ez/Arabic loanword for diamond (ألماس / አልማዝ).",
    culturalContext: "Given to cherish a rare and invaluable daughter, symbolizing purity and radiant strength.",
    numerologicalValues: { destiny: 4, soulUrge: 2, personality: 2 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Unbreakable inner core, pristine aesthetic standards, high somatic sensitivity.",
      emotionalExpressionStyle: "Graceful and contained; maintains strong poise even during acute stress.",
      psychosomaticTendency: "High dermal and sensory sensitivity; physical tension around the neck and jawline.",
      balancingVirtue: "Gentle lymphatic drainage, soothing floral and herbal teas, and emotional softness.",
    },
  },
  {
    name: "Selam",
    geezFidel: "ሰላም",
    language: "Amharic",
    meaning: "Peace, wholeness, safety, and tranquil serenity",
    gender: "female",
    originEtymology: "Classical Semitic root 'ሰ-ለ-መ' (SLM - peace, soundness, reconciliation).",
    culturalContext: "Bestowed during times of communal peace or as a prayer for domestic tranquility.",
    numerologicalValues: { destiny: 6, soulUrge: 6, personality: 9 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "The peacemaker and mediator; vital sign balance directly tied to harmonious relationships.",
      emotionalExpressionStyle: "Calming and de-escalating; deeply distressed by loud arguments or chaotic environments.",
      psychosomaticTendency: "Heart palpitations and epigastric fluttering during relational turmoil.",
      balancingVirtue: "Peaceful quiet environments, deep diaphragmatic breathing, and herbal cardiovascular tonics.",
    },
  },
  {
    name: "Dawit",
    geezFidel: "ዳዊት",
    language: "Amharic",
    meaning: "Beloved; victorious shepherd and musician king",
    gender: "male",
    originEtymology: "From the biblical name David (Ge'ez: ዳዊት - Beloved).",
    culturalContext: "Associated with the Psalms of David (መዝሙረ ዳዊት) used for holistic prayer and healing.",
    numerologicalValues: { destiny: 3, soulUrge: 1, personality: 2 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Resilient courage, musical harmony, capacity to conquer overwhelming obstacles.",
      emotionalExpressionStyle: "Charismatic and poetic; channels emotional stress into song, prayer, or creative labor.",
      psychosomaticTendency: "Vocal fatigue, throat tightness, and upper thoracic tension under heavy responsibility.",
      balancingVirtue: "Vocal warmups, herbal gargles with honey and ginger, and restful mountain walks.",
    },
  },
  {
    name: "Tariku",
    geezFidel: "ታሪኩ",
    language: "Amharic",
    meaning: "His history, story, and memorable lineage",
    gender: "male",
    originEtymology: "Derived from 'ታሪክ' (Tarik - history/chronicle) with 3rd-person suffix '-u'.",
    culturalContext: "Commemorates an unforgettable event or ancestral continuity across generations.",
    numerologicalValues: { destiny: 9, soulUrge: 4, personality: 5 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Custodianship of the past; high sense of ancestral accountability.",
      emotionalExpressionStyle: "Narrative-driven; processes bodily sensations through storytelling and reflection.",
      psychosomaticTendency: "Nervous system exhaustion from carrying intergenerational family duties.",
      balancingVirtue: "Focusing on present bodily sensations, mindful meditation, and daily light physical exercise.",
    },
  },
  {
    name: "Aster",
    geezFidel: "አስቴር",
    language: "Amharic",
    meaning: "Star — shining beauty and protective grace",
    gender: "female",
    originEtymology: "From ancient Persian/Biblical roots adopted into Ge'ez (ኮከብ / አስቴር).",
    culturalContext: "Celebrated for bravery, radiant beauty, and stepping forward to save one's community.",
    numerologicalValues: { destiny: 2, soulUrge: 6, personality: 5 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Luminous guidance, social devotion, acute intuitive perception.",
      emotionalExpressionStyle: "Empathetic and socially responsive; sensitive to ambient group moods.",
      psychosomaticTendency: "Circulatory sensitivity, cold hands and feet during nervous anticipation.",
      balancingVirtue: "Warming spices (Korerima, Ginger), warm foot soaks, and regular cardio movement.",
    },
  },
  {
    name: "Yohannes",
    geezFidel: "ዮሐንስ",
    language: "Amharic",
    meaning: "God has shown grace and mercy",
    gender: "male",
    originEtymology: "From Ge'ez 'ዮሐንስ' (Yoḥannəs - Hebrew Yohanan - Yahweh is gracious).",
    culturalContext: "Echoes the ascetic discipline of John the Baptist and the prophetic wisdom of the Evangelist.",
    numerologicalValues: { destiny: 7, soulUrge: 8, personality: 8 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Ascetic purity, philosophical discipline, high tolerance for physical simplicity.",
      emotionalExpressionStyle: "Solemn and principled; values authenticity over superficial social ease.",
      psychosomaticTendency: "Digestive dryness during strict religious fasting; melancholy in isolated environments.",
      balancingVirtue: "Nutritious broths during fasting periods, healthy sesame oils, and warm sunlit community walks.",
    },
  },
  {
    name: "Haile",
    geezFidel: "ኃይሌ",
    language: "Amharic",
    meaning: "My strength, power, and vital force",
    gender: "male",
    originEtymology: "From the Ge'ez noun 'ኃይል' (Hayl - strength/power/might) with possessive suffix.",
    culturalContext: "Evokes divine and physical fortitude; commonly given to invoke protective power for a son.",
    numerologicalValues: { destiny: 1, soulUrge: 6, personality: 4 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Unyielding strength, commanding vigor, innate expectation of physical endurance.",
      emotionalExpressionStyle: "Assertive, protective, and direct; uncomfortable showing hesitation or frailty.",
      psychosomaticTendency: "High vascular tone, elevated blood pressure under stress, muscular shoulder clenching.",
      balancingVirtue: "Cardiovascular breathwork, bitter herbal teas, and regular aerobic pacing.",
    },
  },
  {
    name: "Genet",
    geezFidel: "ገነት",
    language: "Amharic",
    meaning: "Paradise, heavenly garden, and fruitful abundance",
    gender: "female",
    originEtymology: "From Ge'ez 'ገነት' (Ganat - Eden / heavenly garden).",
    culturalContext: "Celebrates pure joy, fertility, verdant natural landscapes, and sweet maternal warmth.",
    numerologicalValues: { destiny: 3, soulUrge: 1, personality: 2 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Verdant life, joyful nurturing, connection to living green flora and culinary arts.",
      emotionalExpressionStyle: "Generous and welcoming; delights in feeding companions and cultivating sanctuary.",
      psychosomaticTendency: "Tendency to overindulge in rich festive dishes; fluid sluggishness when sedentary.",
      balancingVirtue: "Daily active garden walks, fresh bitter greens (Habesha Gomen), and mindful digestive pacing.",
    },
  },
  {
    name: "Taye",
    geezFidel: "ታየ",
    language: "Amharic",
    meaning: "He was seen, manifested, and acknowledged",
    gender: "male",
    originEtymology: "From the verb 'ታየ' (Taye - to appear, be seen, become visible).",
    culturalContext: "Often given when a long-awaited son finally arrives, proving divine presence.",
    numerologicalValues: { destiny: 4, soulUrge: 7, personality: 6 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Visible dignity, clear purpose, accountability to be present for others.",
      emotionalExpressionStyle: "Measured and steady; observant of physical and environmental details.",
      psychosomaticTendency: "Visual eye strain and tension headaches from intense focus and observation.",
      balancingVirtue: "Eye relaxation exercises, spending time looking at distant highland horizons, and restful sleep.",
    },
  },

  // ==================== GE'EZ & ECCLESIASTICAL NAMES ====================
  {
    name: "Tekle Haymanot",
    geezFidel: "ተክለ ሃይማኖት",
    language: "Ge'ez",
    meaning: "Plant of Faith — deeply rooted in sacred ground",
    gender: "male",
    originEtymology: "Compound of 'Tekle' (ተክለ - plant/sapling) and 'Haymanot' (ሃይማኖት - faith).",
    culturalContext: "Honors Ethiopia's great 13th-century monk-healer saint Abune Tekle Haymanot of Debre Libanos.",
    numerologicalValues: { destiny: 33, soulUrge: 11, personality: 22 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Sacred healer and ascetic servant; immense spiritual endurance.",
      emotionalExpressionStyle: "Reverent, meditative, and self-sacrificing.",
      psychosomaticTendency: "Musculoskeletal fatigue from standing or kneeling for hours; joint stress in knees.",
      balancingVirtue: "Sacred spring holy water (Tsebel) immersion, restorative joint oils, and balanced nutrition.",
    },
  },
  {
    name: "Gebre Meskel",
    geezFidel: "ገብረ መስቀል",
    language: "Ge'ez",
    meaning: "Servant of the Cross — steadfast protector",
    gender: "male",
    originEtymology: "Compound of 'Gebre' (ገብረ - servant/maker) and 'Meskel' (መስቀል - cross).",
    culturalContext: "Ancient royal and ecclesiastical name invoking steadfast protection and service.",
    numerologicalValues: { destiny: 22, soulUrge: 6, personality: 7 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Protective shield, unwavering duty, structural foundation for community survival.",
      emotionalExpressionStyle: "Stoic and duty-bound; rarely vocalizes personal physical distress.",
      psychosomaticTendency: "Chronic spinal compression and thoracic rigidity from bearing heavy burdens.",
      balancingVirtue: "Spinal decompression exercises, warm herbal compresses, and communal encouragement.",
    },
  },
  {
    name: "Wolde Mariam",
    geezFidel: "ወልደ ማርያም",
    language: "Ge'ez",
    meaning: "Son of Mary — under maternal sanctuary",
    gender: "male",
    originEtymology: "Compound of 'Wolde' (ወልደ - son of) and 'Mariam' (ማርያም - Mary).",
    culturalContext: "Dedicated to the Virgin Mary for lifetime protection and compassionate guidance.",
    numerologicalValues: { destiny: 9, soulUrge: 8, personality: 1 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Maternal protection, compassionate heart, receptive to intuitive wellbeing healing.",
      emotionalExpressionStyle: "Tender and protective; attentive to the emotional atmosphere of the household.",
      psychosomaticTendency: "Visceral digestive empathy; reacts strongly to emotional distress of close relatives.",
      balancingVirtue: "Gentle warm herbal teas (Damakesse, Koseret) and emotional grounding exercises.",
    },
  },
  {
    name: "Walatta Petros",
    geezFidel: "ወለተ ጴጥሮስ",
    language: "Ge'ez",
    meaning: "Daughter of Peter — rock of spiritual independence",
    gender: "female",
    originEtymology: "Compound of 'Walatta' (ወለተ - daughter of) and 'Petros' (ጴጥሮስ - Peter/Rock).",
    culturalContext: "Named after the historic 17th-century female monastic leader and saint who defended Ethiopian traditions.",
    numerologicalValues: { destiny: 11, soulUrge: 7, personality: 4 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Fierce spiritual integrity, intellectual fearlessness, leadership of women.",
      emotionalExpressionStyle: "Articulate and decisive; stands unshakable in defense of principles.",
      psychosomaticTendency: "High nervous system voltage, migraine headaches from high cognitive alertness.",
      balancingVirtue: "Regular quiet meditation, grounding herbal teas, and barefoot contact with earth.",
    },
  },
  {
    name: "Habte Selassie",
    geezFidel: "ሀብተ ሥላሴ",
    language: "Ge'ez",
    meaning: "Gift of the Holy Trinity",
    gender: "male",
    originEtymology: "Compound of 'Habte' (ሀብተ - gift/grace of) and 'Selassie' (ሥላሴ - Trinity).",
    culturalContext: "Signifies a child received as a miraculous gift from the Holy Trinity.",
    numerologicalValues: { destiny: 8, soulUrge: 11, personality: 6 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Consecrated purpose, high ethical standards, deep spiritual gratitude.",
      emotionalExpressionStyle: "Dignified and generous; acts as a pillar of emotional strength for family.",
      psychosomaticTendency: "Adrenal burnout from striving to live up to consecrated expectations.",
      balancingVirtue: "Humility in accepting personal physical limits, structured rest, and balanced nutrition.",
    },
  },

  // ==================== AFAAN OROMO NAMES ====================
  {
    name: "Chaltu",
    geezFidel: "ጫልቱ",
    language: "Afaan Oromo",
    meaning: "Superior, exquisite, and the foremost beauty",
    gender: "female",
    originEtymology: "From the Afaan Oromo root 'Caaluu' (to surpass, excel, or be superior).",
    culturalContext: "Given to a daughter celebrated for outstanding beauty, grace, and superior vitality.",
    numerologicalValues: { destiny: 5, soulUrge: 4, personality: 1 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Natural leadership among peers, high vitality, refusal to settle for mediocrity.",
      emotionalExpressionStyle: "Vibrant, dynamic, and direct; inspires energy in others.",
      psychosomaticTendency: "Restless tension in the legs, fast metabolic burn with sudden hunger dips.",
      balancingVirtue: "Sustained complex carbohydrates (Teff, Barley/Gesho), regular meal intervals.",
    },
  },
  {
    name: "Tolessa",
    geezFidel: "ቶለሳ",
    language: "Afaan Oromo",
    meaning: "Benevolent, generous, and doing good unto others",
    gender: "male",
    originEtymology: "From 'Tola' (goodness/kindness/grace) in Afaan Oromo.",
    culturalContext: "Celebrates the traditional Gadaa virtue of benevolence and community welfare.",
    numerologicalValues: { destiny: 6, soulUrge: 2, personality: 4 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Community benefactor, fair mediator, steady guardian of the vulnerable.",
      emotionalExpressionStyle: "Warm, supportive, and reconciliatory.",
      psychosomaticTendency: "Shoulder tension from carrying community problems, delayed self-care.",
      balancingVirtue: "Scheduled time for personal recreation, cardiovascular fitness, and quiet sanctuary.",
    },
  },
  {
    name: "Bona",
    geezFidel: "ቦና",
    language: "Afaan Oromo",
    meaning: "Dry sunny harvest season — pride and dignified sunshine",
    gender: "male",
    originEtymology: "From 'Bona' (the dry sunny harvest season / winter sun) in Afaan Oromo.",
    culturalContext: "Associated with golden sunshine, harvest abundance, and radiant personal dignity.",
    numerologicalValues: { destiny: 1, soulUrge: 7, personality: 3 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Solar confidence, proud posture, resilience against cold or gloomy conditions.",
      emotionalExpressionStyle: "Warm and authoritative; speaks with deliberate confidence.",
      psychosomaticTendency: "Prone to inflammatory heat, acute fever reactions, and sun-induced headaches.",
      balancingVirtue: "Cooling spring waters, hydrating herbal teas, and shaded midday rests.",
    },
  },
  {
    name: "Obsa",
    geezFidel: "ኦብሳ",
    language: "Afaan Oromo",
    meaning: "Patience, profound endurance, and steadfast composure",
    gender: "unisex",
    originEtymology: "From the verb 'Obsuu' (to endure with dignity and calm patience).",
    culturalContext: "A cornerstone virtue in Oromo Gadaa governance; leaders must possess boundless Obsa.",
    numerologicalValues: { destiny: 4, soulUrge: 7, personality: 6 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Immovable rock of composure; deep inner psychological stamina.",
      emotionalExpressionStyle: "Calm, slow to anger, thoughtful before responding.",
      psychosomaticTendency: "Internalizes somatic stress into the gut wall; risks digestive slow motility.",
      balancingVirtue: "Digestive warming spices (Ginger, Korerima) and expressing emotions openly.",
    },
  },
  {
    name: "Hawi",
    geezFidel: "ሀዊ",
    language: "Afaan Oromo",
    meaning: "Hope, aspiration, and long-cherished desire",
    gender: "female",
    originEtymology: "From 'Hawwii' (desire, wish, aspiration, hope) in Afaan Oromo.",
    culturalContext: "Given to embody a family's hope for a brighter future and generational prosperity.",
    numerologicalValues: { destiny: 3, soulUrge: 1, personality: 2 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Future-focused optimism, buoyant energy, radiant aspirational vision.",
      emotionalExpressionStyle: "Enthusiastic and encouraging; uplifts companions in distress.",
      psychosomaticTendency: "Respiratory sensitivity; can hyperventilate or sigh deeply when dreams are frustrated.",
      balancingVirtue: "Deep rhythmic pranayama breathwork, fresh air exposure, and outdoor hiking.",
    },
  },
  {
    name: "Biftu",
    geezFidel: "ቢፍቱ",
    language: "Afaan Oromo",
    meaning: "Dawn — the first golden light of sunrise",
    gender: "female",
    originEtymology: "From 'Biftuu' (the morning sun / sunrise light) in Afaan Oromo.",
    culturalContext: "Celebrates the arrival of dawn after dark night; symbolizes awakening and clean beginnings.",
    numerologicalValues: { destiny: 7, soulUrge: 3, personality: 4 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Awakened consciousness, early morning peak vitality, sensory alertness.",
      emotionalExpressionStyle: "Clear, illuminating, and insightful.",
      psychosomaticTendency: "Sensitive to circadian disruptions; performs poorly with irregular night shifts.",
      balancingVirtue: "Strict early-morning wake and sun-gazing routine, consistent bedtime.",
    },
  },
  {
    name: "Fayisa",
    geezFidel: "ፈይሳ",
    language: "Afaan Oromo",
    meaning: "The Healer — one who brings recovery, wellness, and salvation",
    gender: "male",
    originEtymology: "From 'Fayyisuu' (to heal, cure, restore wellbeing, or deliver) in Afaan Oromo.",
    culturalContext: "Given to a son born after illness or dedicated to the art of healing and restorative medicine.",
    numerologicalValues: { destiny: 9, soulUrge: 11, personality: 7 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Instinctive healer and caregiver; draws energy from restoring harmony to others.",
      emotionalExpressionStyle: "Compassionate, gentle, and biologically attuned.",
      psychosomaticTendency: "Vulnerable to somatic empathy fatigue, taking on patients' or relatives' aches.",
      balancingVirtue: "Energetic clearing with herbal baths, personal boundaries, and regular solitary walks.",
    },
  },
  {
    name: "Caala",
    geezFidel: "ጫላ",
    language: "Afaan Oromo",
    meaning: "The Greatest, best, and most excellent",
    gender: "male",
    originEtymology: "From 'Caaluu' (to surpass, prevail, or be the best).",
    culturalContext: "Bestowed with aspirations for top excellence in physical athletics, knowledge, and leadership.",
    numerologicalValues: { destiny: 8, soulUrge: 2, personality: 6 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Competitiveness, peak physical conditioning, desire to excel in stamina.",
      emotionalExpressionStyle: "Dynamic and goal-directed.",
      psychosomaticTendency: "Overtraining syndrome, tendon and ligament strain from relentless exercise.",
      balancingVirtue: "Mandatory rest and recovery days, anti-inflammatory nutrition, and stretching.",
    },
  },

  // ==================== TIGRINYA NAMES ====================
  {
    name: "Gidey",
    geezFidel: "ጊደይ",
    language: "Tigrinya",
    meaning: "My share, my destiny, and my rightful portion",
    gender: "unisex",
    originEtymology: "From Tigrinya 'Gide' (share/portion/destiny) with first-person possessive '-ey'.",
    culturalContext: "Expresses gratitude that the family has received their rightful blessing from Providence.",
    numerologicalValues: { destiny: 6, soulUrge: 5, personality: 1 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Contentment with one's rightful allotment; steady, resilient self-possession.",
      emotionalExpressionStyle: "Pragmatic, grounded, and appreciative of everyday blessings.",
      psychosomaticTendency: "Metabolic balance dependent on feeling satisfied and secure in life's baseline.",
      balancingVirtue: "Mindful gratitude practices, wholesome highland grain nutrition (Teff, Emmer wheat).",
    },
  },
  {
    name: "Berhane",
    geezFidel: "ብርሃነ",
    language: "Tigrinya",
    meaning: "My light — radiant illumination and clarity",
    gender: "male",
    originEtymology: "From Ge'ez/Tigrinya 'ብርሃን' (Birhan - light) with first-person suffix.",
    culturalContext: "Given to illuminate a household; represents intellect, clear vision, and spiritual insight.",
    numerologicalValues: { destiny: 1, soulUrge: 6, personality: 4 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Clarity of vision, radiant optimism, intellectual vitality.",
      emotionalExpressionStyle: "Direct, enlightened, and encouraging.",
      psychosomaticTendency: "Nerve strain from excessive cognitive effort, eye fatigue.",
      balancingVirtue: "Visual rest, high-antioxidant highland fruits, and outdoor sunlight immersion.",
    },
  },
  {
    name: "Senait",
    geezFidel: "ሰናይት",
    language: "Tigrinya",
    meaning: "Goodness, beauty, pleasantness, and virtue",
    gender: "female",
    originEtymology: "From Ge'ez/Tigrinya 'ሰናይ' (Sanay - good, pleasing, virtuous, fair).",
    culturalContext: "Celebrates moral virtue, aesthetic grace, and radiant goodness of spirit.",
    numerologicalValues: { destiny: 2, soulUrge: 6, personality: 5 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Inherent goodness and gentleness; creates a calm, soothing atmosphere for others.",
      emotionalExpressionStyle: "Soft-spoken, pleasant, and highly sensitive to disharmony.",
      psychosomaticTendency: "Digestive delicacy; upsets in relationships cause immediate appetite loss.",
      balancingVirtue: "Warm soothing herbal broths, calming Damakesse teas, and protective personal boundaries.",
    },
  },
  {
    name: "Semere",
    geezFidel: "ሰመረ",
    language: "Tigrinya",
    meaning: "He united, harmonized, prospered, and succeeded",
    gender: "male",
    originEtymology: "From 'ሰመረ' (Samara - to unite, succeed, or find harmonious completion).",
    culturalContext: "Given when an enterprise or reconciliation succeeds; represents unity and harvest.",
    numerologicalValues: { destiny: 4, soulUrge: 1, personality: 3 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Integrator and builder; finds vitality when disparate parts come together harmoniously.",
      emotionalExpressionStyle: "Constructive and collaborative; dislikes wasted effort.",
      psychosomaticTendency: "Physical tension in the diaphragm when projects or relationships stall.",
      balancingVirtue: "Core diaphragmatic breathing, cardiovascular team sports, and structured work-rest pacing.",
    },
  },
  {
    name: "Luwam",
    geezFidel: "ሉዋም",
    language: "Tigrinya",
    meaning: "Serenity, peace, sweet sleep, and restful calm",
    gender: "female",
    originEtymology: "From Tigrinya 'Luwam' (deep peacefulness, restful tranquility, and sweet slumber).",
    culturalContext: "Given with prayers for a tranquil life, undisturbed rest, and soothing peace.",
    numerologicalValues: { destiny: 7, soulUrge: 4, personality: 3 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Sanctuary of peace; naturally requires peaceful environments for cellular recuperation.",
      emotionalExpressionStyle: "Serene, tranquil, and contemplative.",
      psychosomaticTendency: "Severe somatic sensitivity to noise pollution, chaotic lighting, or loud conflict.",
      balancingVirtue: "Quiet bedtime rituals, soothing chamomile or Damakesse tea, and dim evening lighting.",
    },
  },
  {
    name: "Mehari",
    geezFidel: "መሐሪ",
    language: "Tigrinya",
    meaning: "Forgiving, merciful, and full of gracious compassion",
    gender: "male",
    originEtymology: "From Ge'ez/Tigrinya 'መሐረ' (Mahara - to have mercy, forgive, or show compassion).",
    culturalContext: "Honors divine forgiveness and human compassion; brings restorative reconciliation.",
    numerologicalValues: { destiny: 9, soulUrge: 6, personality: 3 },
    wellbeingIdentityCorrelation: {
      selfPerceptionTheme: "Compassionate healer and forgiver; releases grudges quickly to protect cardiovascular wellbeing.",
      emotionalExpressionStyle: "Gentle, forgiving, and open-hearted.",
      psychosomaticTendency: "Cardiovascular sensitivity; absorbs emotional grief if forgiveness is delayed.",
      balancingVirtue: "Emotional release practices, heart-healthy antioxidants, and brisk nature walks.",
    },
  },
];

export function findEthiopianNameRecord(name: string): EthiopianNameRecord | undefined {
  const norm = name.trim().toLowerCase();
  return ETHIOPIAN_NAMES_DATABASE.find(
    (item) => item.name.toLowerCase() === norm || (item.geezFidel && item.geezFidel === name.trim())
  );
}

export function searchEthiopianNames(query: string): EthiopianNameRecord[] {
  const q = query.trim().toLowerCase();
  if (!q) return ETHIOPIAN_NAMES_DATABASE.slice(0, 10);

  return ETHIOPIAN_NAMES_DATABASE.filter(
    (item) =>
      item.name.toLowerCase().includes(q) ||
      (item.geezFidel && item.geezFidel.includes(query.trim())) ||
      item.meaning.toLowerCase().includes(q) ||
      item.language.toLowerCase().includes(q)
  );
}
